package com.toir.dto.maintenanceaction;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;

@JsonIgnoreProperties("code")
@Schema(description = "Maintenance action request. Code is generated by backend as MA-YYYY-NNNN.")
public record MaintenanceActionRequest(
        @NotBlank @Size(max = 255) String name,
        @Size(max = 128) @Schema(description = "Free-text maintenance action category", example = "MECHANICAL")
        String category,
        @PositiveOrZero Double defaultDurationHours,
        @Size(max = 255) String requiredSkill,
        String safetyNotes,
        String toolsRequired,
        String sparePartsRequired,
        String consumablesRequired,
        Boolean active
) {}
