package com.toir.dto.workorder;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.toir.dto.materialusage.RepairMaterialUsageDto;
import com.toir.enums.PriorityLevel;
import com.toir.enums.DefectListStatus;
import com.toir.enums.WorkOrderStatus;
import com.toir.enums.WorkOrderType;
import com.toir.enums.WorkType;
import com.toir.dto.triad.DefectBriefDto;
import com.toir.dto.triad.RepairRequestBriefDto;
import com.toir.enums.EquipmentNodeType;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

public record WorkOrderDto(
        UUID id,
        String number,
        String title,
        UUID equipmentId,
        UUID equipmentNodeId,
        String equipmentNodeCode,
        String equipmentNodeName,
        EquipmentNodeType equipmentNodeType,
        UUID departmentId,
        String equipmentName,
        String departmentName,
        UUID locationId,
        String locationName,
        String workLocationNote,
        UUID repairRequestId,
        UUID defectId,
        UUID defectListId,
        String defectListNumber,
        DefectListStatus defectListStatus,
        UUID pprTaskId,
        UUID contractorId,
        ContractorRef contractor,
        UUID performerId,
        String performerName,
        WorkOrderStatus status,
        WorkOrderType type,
        WorkType workType,
        PriorityLevel priority,
        Instant startPlannedAt,
        Instant endPlannedAt,
        Instant startedAt,
        Instant completedAt,
        String summary,
        String result,
        String closureNotes,
        UUID createdById,
        UUID approvedById,
        UUID warehouseId,
        UUID replacementEquipmentId,
        String replacementEquipmentName,
        List<WorkOrderTaskDto> tasks,
        RepairRequestBriefDto repairRequest,
        DefectBriefDto defect,
        int operationsCount,
        int materialsCount,
        Boolean repairActRequired,
        Boolean stoppageActRequired,
        UUID repairActFileId,
        UUID stoppageActFileId,
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        List<RepairMaterialUsageDto> materialUsages,
        Instant updatedAt,
        UUID repairCampaignId,
        UUID repairCampaignStageId,
        String repairCampaignName,
        String repairCampaignStageName,
        UUID budgetLineId
) {
    public WorkOrderDto {
        repairActRequired = Boolean.TRUE.equals(repairActRequired);
        stoppageActRequired = Boolean.TRUE.equals(stoppageActRequired);
        materialUsages = materialUsages == null ? List.of() : List.copyOf(materialUsages);
    }

    public WorkOrderDto(UUID id,
                        String number,
                        String title,
                        UUID equipmentId,
                        UUID equipmentNodeId,
                        String equipmentNodeCode,
                        String equipmentNodeName,
                        EquipmentNodeType equipmentNodeType,
                        UUID departmentId,
                        String equipmentName,
                        String departmentName,
                        UUID locationId,
                        String locationName,
                        String workLocationNote,
                        UUID repairRequestId,
                        UUID defectId,
                        UUID defectListId,
                        String defectListNumber,
                        DefectListStatus defectListStatus,
                        UUID pprTaskId,
                        UUID contractorId,
                        ContractorRef contractor,
                        UUID performerId,
                        String performerName,
                        WorkOrderStatus status,
                        WorkOrderType type,
                        WorkType workType,
                        PriorityLevel priority,
                        Instant startPlannedAt,
                        Instant endPlannedAt,
                        Instant startedAt,
                        Instant completedAt,
                        String summary,
                        String result,
                        String closureNotes,
                        UUID createdById,
                        UUID approvedById,
                        UUID warehouseId,
                        UUID replacementEquipmentId,
                        String replacementEquipmentName,
                        List<WorkOrderTaskDto> tasks,
                        RepairRequestBriefDto repairRequest,
                        DefectBriefDto defect,
                        int operationsCount,
                        int materialsCount,
                        Boolean repairActRequired,
                        Boolean stoppageActRequired,
                        UUID repairActFileId,
                        UUID stoppageActFileId,
                        List<RepairMaterialUsageDto> materialUsages,
                        Instant updatedAt) {
        this(id, number, title, equipmentId, equipmentNodeId, equipmentNodeCode, equipmentNodeName,
                equipmentNodeType, departmentId, equipmentName, departmentName, locationId, locationName,
                workLocationNote, repairRequestId, defectId, defectListId, defectListNumber, defectListStatus,
                pprTaskId, contractorId, contractor, performerId, performerName, status, type, workType, priority,
                startPlannedAt, endPlannedAt, startedAt, completedAt, summary, result, closureNotes, createdById,
                approvedById, warehouseId, replacementEquipmentId, replacementEquipmentName, tasks, repairRequest,
                defect, operationsCount, materialsCount, repairActRequired, stoppageActRequired, repairActFileId,
                stoppageActFileId, materialUsages, updatedAt, null, null, null, null, null);
    }

    public WorkOrderDto(UUID id,
                        String number,
                        String title,
                        UUID equipmentId,
                        UUID equipmentNodeId,
                        String equipmentNodeCode,
                        String equipmentNodeName,
                        EquipmentNodeType equipmentNodeType,
                        UUID departmentId,
                        String equipmentName,
                        String departmentName,
                        UUID locationId,
                        String locationName,
                        String workLocationNote,
                        UUID repairRequestId,
                        UUID defectId,
                        UUID defectListId,
                        String defectListNumber,
                        DefectListStatus defectListStatus,
                        UUID pprTaskId,
                        UUID contractorId,
                        ContractorRef contractor,
                        UUID performerId,
                        String performerName,
                        WorkOrderStatus status,
                        WorkOrderType type,
                        WorkType workType,
                        PriorityLevel priority,
                        Instant startPlannedAt,
                        Instant endPlannedAt,
                        Instant startedAt,
                        Instant completedAt,
                        String summary,
                        String result,
                        String closureNotes,
                        UUID createdById,
                        UUID approvedById,
                        UUID warehouseId,
                        UUID replacementEquipmentId,
                        String replacementEquipmentName,
                        List<WorkOrderTaskDto> tasks,
                        RepairRequestBriefDto repairRequest,
                        DefectBriefDto defect,
                        int operationsCount,
                        int materialsCount,
                        Boolean repairActRequired,
                        Boolean stoppageActRequired,
                        UUID repairActFileId,
                        UUID stoppageActFileId,
                        List<RepairMaterialUsageDto> materialUsages,
                        Instant updatedAt,
                        UUID repairCampaignId,
                        UUID repairCampaignStageId,
                        String repairCampaignName,
                        String repairCampaignStageName) {
        this(id, number, title, equipmentId, equipmentNodeId, equipmentNodeCode, equipmentNodeName,
                equipmentNodeType, departmentId, equipmentName, departmentName, locationId, locationName,
                workLocationNote, repairRequestId, defectId, defectListId, defectListNumber, defectListStatus,
                pprTaskId, contractorId, contractor, performerId, performerName, status, type, workType, priority,
                startPlannedAt, endPlannedAt, startedAt, completedAt, summary, result, closureNotes, createdById,
                approvedById, warehouseId, replacementEquipmentId, replacementEquipmentName, tasks, repairRequest,
                defect, operationsCount, materialsCount, repairActRequired, stoppageActRequired, repairActFileId,
                stoppageActFileId, materialUsages, updatedAt, repairCampaignId, repairCampaignStageId,
                repairCampaignName, repairCampaignStageName, null);
    }

    public WorkOrderDto(UUID id,
                        String number,
                        String title,
                        UUID equipmentId,
                        UUID equipmentNodeId,
                        String equipmentNodeCode,
                        String equipmentNodeName,
                        EquipmentNodeType equipmentNodeType,
                        UUID departmentId,
                        String equipmentName,
                        String departmentName,
                        UUID repairRequestId,
                        UUID defectId,
                        UUID pprTaskId,
                        UUID contractorId,
                        WorkOrderStatus status,
                        WorkOrderType type,
                        WorkType workType,
                        PriorityLevel priority,
                        Instant startPlannedAt,
                        Instant endPlannedAt,
                        Instant startedAt,
                        Instant completedAt,
                        String summary,
                        String result,
                        String closureNotes,
                        UUID createdById,
                        UUID approvedById,
                        UUID warehouseId,
                        UUID replacementEquipmentId,
                        String replacementEquipmentName,
                        List<WorkOrderTaskDto> tasks,
                        RepairRequestBriefDto repairRequest,
                        DefectBriefDto defect,
                        int operationsCount,
                        int materialsCount) {
        this(id, number, title, equipmentId, equipmentNodeId, equipmentNodeCode, equipmentNodeName,
                equipmentNodeType, departmentId, equipmentName, departmentName, null, null, null, repairRequestId, defectId,
                null, null, null, pprTaskId, contractorId, null, null, null, status, type, workType, priority, startPlannedAt, endPlannedAt,
                startedAt, completedAt, summary, result, closureNotes, createdById, approvedById, warehouseId,
                replacementEquipmentId, replacementEquipmentName, tasks, repairRequest, defect, operationsCount,
                materialsCount, false, false, null, null, List.of(), null);
    }

    public WorkOrderDto(UUID id,
                        String number,
                        String title,
                        UUID equipmentId,
                        UUID equipmentNodeId,
                        String equipmentNodeCode,
                        String equipmentNodeName,
                        EquipmentNodeType equipmentNodeType,
                        UUID departmentId,
                        String equipmentName,
                        String departmentName,
                        UUID repairRequestId,
                        UUID defectId,
                        UUID pprTaskId,
                        UUID contractorId,
                        UUID performerId,
                        String performerName,
                        WorkOrderStatus status,
                        WorkOrderType type,
                        WorkType workType,
                        PriorityLevel priority,
                        Instant startPlannedAt,
                        Instant endPlannedAt,
                        Instant startedAt,
                        Instant completedAt,
                        String summary,
                        String result,
                        String closureNotes,
                        UUID createdById,
                        UUID approvedById,
                        UUID warehouseId,
                        UUID replacementEquipmentId,
                        String replacementEquipmentName,
                        List<WorkOrderTaskDto> tasks,
                        RepairRequestBriefDto repairRequest,
                        DefectBriefDto defect,
                        int operationsCount,
                        int materialsCount) {
        this(id, number, title, equipmentId, equipmentNodeId, equipmentNodeCode, equipmentNodeName,
                equipmentNodeType, departmentId, equipmentName, departmentName, null, null, null, repairRequestId, defectId,
                null, null, null, pprTaskId, contractorId, null, performerId, performerName, status, type, workType, priority, startPlannedAt, endPlannedAt,
                startedAt, completedAt, summary, result, closureNotes, createdById, approvedById, warehouseId,
                replacementEquipmentId, replacementEquipmentName, tasks, repairRequest, defect, operationsCount,
                materialsCount, false, false, null, null, List.of(), null);
    }

    public WorkOrderDto(UUID id,
                        String number,
                        String title,
                        UUID equipmentId,
                        UUID departmentId,
                        String equipmentName,
                        String departmentName,
                        UUID repairRequestId,
                        UUID defectId,
                        UUID pprTaskId,
                        UUID contractorId,
                        WorkOrderStatus status,
                        WorkOrderType type,
                        WorkType workType,
                        PriorityLevel priority,
                        Instant startPlannedAt,
                        Instant endPlannedAt,
                        Instant startedAt,
                        Instant completedAt,
                        String summary,
                        String result,
                        String closureNotes,
                        UUID createdById,
                        UUID approvedById,
                        UUID warehouseId,
                        UUID replacementEquipmentId,
                        String replacementEquipmentName,
                        List<WorkOrderTaskDto> tasks,
                        RepairRequestBriefDto repairRequest,
                        DefectBriefDto defect,
                        int operationsCount,
                        int materialsCount) {
        this(id, number, title, equipmentId, null, null, null, null, departmentId, equipmentName, departmentName,
                null, null, null,
                repairRequestId, defectId, null, null, null, pprTaskId, contractorId, null, null, null, status, type, workType, priority,
                startPlannedAt, endPlannedAt, startedAt, completedAt, summary, result, closureNotes,
                createdById, approvedById, warehouseId, replacementEquipmentId, replacementEquipmentName,
                tasks, repairRequest, defect, operationsCount, materialsCount, false, false, null, null, List.of(), null);
    }

    public WorkOrderDto(UUID id,
                        String number,
                        String title,
                        UUID equipmentId,
                        UUID departmentId,
                        String equipmentName,
                        String departmentName,
                        UUID repairRequestId,
                        UUID defectId,
                        UUID pprTaskId,
                        UUID contractorId,
                        UUID performerId,
                        String performerName,
                        WorkOrderStatus status,
                        WorkOrderType type,
                        WorkType workType,
                        PriorityLevel priority,
                        Instant startPlannedAt,
                        Instant endPlannedAt,
                        Instant startedAt,
                        Instant completedAt,
                        String summary,
                        String result,
                        String closureNotes,
                        UUID createdById,
                        UUID approvedById,
                        UUID warehouseId,
                        UUID replacementEquipmentId,
                        String replacementEquipmentName,
                        List<WorkOrderTaskDto> tasks,
                        RepairRequestBriefDto repairRequest,
                        DefectBriefDto defect,
                        int operationsCount,
                        int materialsCount) {
        this(id, number, title, equipmentId, null, null, null, null, departmentId, equipmentName, departmentName,
                null, null, null,
                repairRequestId, defectId, null, null, null, pprTaskId, contractorId, null, performerId, performerName, status, type, workType, priority,
                startPlannedAt, endPlannedAt, startedAt, completedAt, summary, result, closureNotes,
                createdById, approvedById, warehouseId, replacementEquipmentId, replacementEquipmentName,
                tasks, repairRequest, defect, operationsCount, materialsCount, false, false, null, null, List.of(), null);
    }

    public record ContractorRef(UUID id, String code, String name) {
    }
//    public static WorkOrderDto from(WorkOrder w) {
//        return new WorkOrderDto(
//                w.getId(), w.getNumber(), w.getTitle(), w.getEquipmentId(), w.getDepartmentId(),
//                w.getRepairRequestId(), w.getPprTaskId(), w.getContractorId(),
//                w.getStatus(), w.getType(), w.getPriority(),
//                w.getStartPlannedAt(), w.getEndPlannedAt(), w.getStartedAt(), w.getCompletedAt(),
//                w.getSummary(), w.getResult(), w.getClosureNotes(),
//                w.getCreatedById(), w.getApprovedById(),
//                w.getTasks().stream().map(WorkOrderTaskDto::from).toList()
//        );
//    }

}
