package com.toir.service;

import com.toir.dto.brigade.BrigadeRequest;
import com.toir.exception.RestException;
import com.toir.repository.projects.BrigadeMemberRepository;
import com.toir.repository.projects.BrigadeRepository;
import com.toir.util.AuditBuilderService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
class BrigadeServiceTest {

    @Mock
    BrigadeRepository brigadeRepo;

    @Mock
    BrigadeMemberRepository memberRepo;

    @Mock
    CertificationGuard certificationGuard;

    @Mock
    SparePartService sparePartService;

    @Mock
    AuditBuilderService auditBuilderService;

    @InjectMocks
    BrigadeService service;

    @Test
    void createRejectsClientProvidedCode() {
        BrigadeRequest request = new BrigadeRequest(
                "BR-CLIENT",
                "Repair Brigade",
                null,
                null,
                "mechanical",
                true
        );

        assertThatThrownBy(() -> service.create(request))
                .isInstanceOfSatisfying(RestException.class, ex -> {
                    assertThat(ex.getStatus()).isEqualTo(HttpStatus.BAD_REQUEST);
                    assertThat(ex.getMessage()).contains("code is generated by backend");
                });

        verify(brigadeRepo, never()).save(any());
    }
}
