workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

variables:
  CHART_VERSION: 10.2-full
  CI_DEBUG_TRACE: "false"
  SERVICE_NAME: mycoal-toir-backend


stages:
  - compile
  - build
  - deploy

compile:
  image: maven:3.9.9-eclipse-temurin-21
  stage: compile
  script:
    - mvn clean package -Dmaven.test.skip=true --no-transfer-progress
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 days

build:
  stage: build
  image: docker:24.0.9
  script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker build -t "${CI_REGISTRY_IMAGE}:latest" .
    - docker push "${CI_REGISTRY_IMAGE}:latest"


deploy:
  stage: deploy
  image: alpine:latest
  script:
    - chmod og= $SSH_PRIVATE_KEY
    - apk add openssh-client
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no -p $SSH_PORT_TENZOR $SSH_USER@$SERVER_HOST_TENZOR "docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD}"
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no -p $SSH_PORT_TENZOR $SSH_USER@$SERVER_HOST_TENZOR "docker pull ${CI_REGISTRY_IMAGE}:latest"
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no -p $SSH_PORT_TENZOR $SSH_USER@$SERVER_HOST_TENZOR "docker stop ${SERVICE_NAME} || true"
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no -p $SSH_PORT_TENZOR $SSH_USER@$SERVER_HOST_TENZOR "docker rm ${SERVICE_NAME} || true"
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no -p $SSH_PORT_TENZOR $SSH_USER@$SERVER_HOST_TENZOR "docker run -d --name ${SERVICE_NAME} --restart unless-stopped -p 10260:8080 ${CI_REGISTRY_IMAGE}:latest"

