package com.toir.service;

import com.toir.dto.pprplanning.*;
import com.toir.entity.Department;
import com.toir.entity.PprPlan;
import com.toir.entity.PprTask;
import com.toir.enums.AuditAction;
import com.toir.enums.AuditModule;
import com.toir.enums.PlanStatus;
import com.toir.enums.PprTaskStatus;
import com.toir.exception.RestException;
import com.toir.repository.PprPlanRepository;
import com.toir.repository.PprPlanStatsProjection;
import com.toir.repository.PprTaskRepository;
import com.toir.repository.department.DepartmentRepository;
import com.toir.util.AuditBuilderService;
import com.toir.util.AuditSerializationService;
import com.toir.util.PaginationUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Year;
import java.util.EnumSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@Transactional
@RequiredArgsConstructor
public class PprPlanService {

    private final PprPlanRepository planRepository;
    private final PprTaskRepository taskRepository;
    private final DepartmentRepository departmentRepository;
    private final AuditBuilderService auditBuilderService;
    private final AuditSerializationService auditSerializationService;
    private static final int MAX_PLAN_CODE_GENERATION_ATTEMPTS = 50;
    private static final int MAX_TASK_CODE_GENERATION_ATTEMPTS = 50;
    private static final String CLIENT_CODE_REJECT_MESSAGE =
            "code is generated by backend and must not be provided";
    private static final Set<PlanStatus> PLAN_TASK_EDIT_STATUSES =
            EnumSet.of(PlanStatus.DRAFT, PlanStatus.GENERATED);
    private static final Set<PlanStatus> PLAN_EXECUTION_STATUSES =
            EnumSet.of(PlanStatus.APPROVED, PlanStatus.IN_PROGRESS);


    @Transactional(readOnly = true)
    public List<PprPlanDto> findAll() {
        return toDtos(planRepository.findAllByIsDeletedFalseOrderByUpdatedAtDesc());
    }

    @Transactional(readOnly = true)
    public Page<PprPlanDto> findAll(Integer year, Integer month, UUID departmentId, int page, int size) {
        Page<PprPlan> plans = planRepository.searchPlans(
                        year,
                        month,
                        departmentId,
                        PaginationUtils.pageRequest(page, size)
                );
        Map<UUID, String> departmentNames = resolveDepartmentNames(plans.getContent());
        return plans.map(plan -> PprPlanDto.from(plan, departmentNames.get(plan.getDepartmentId())));
    }

    @Transactional(readOnly = true)
    public PprPlanStatsResponse getStats(Integer year, Integer month, UUID departmentId) {
        PprPlanStatsProjection stats = planRepository.getStats(year, month, departmentId);
        if (stats == null) {
            return new PprPlanStatsResponse(0, 0, 0, 0, 0, 0, 0);
        }
        return new PprPlanStatsResponse(
                safe(stats.getTotalPlans()),
                safe(stats.getDraftPlans()),
                safe(stats.getGeneratedPlans()),
                safe(stats.getApprovedPlans()),
                safe(stats.getPlannedTasks()),
                safe(stats.getInProgressTasks()),
                safe(stats.getCompletedTasks())
        );
    }

    @Transactional(readOnly = true)
    public PprPlanDto findById(UUID id) {
        return toDto(getPlan(id));
    }

    @Transactional
    public PprPlanDto create(PprPlanRequest request) {
        PprPlan saved = saveWithGeneratedPlanCode(request);

        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.CREATE,
                AuditModule.PPR_PLAN,
                "ППР план создан",
                null,
                saved
        );

        return toDto(saved);
    }

    public PprPlanDto update(UUID id, PprPlanRequest request) {
        PprPlan plan = getPlan(id);
        if (plan.getStatus() != PlanStatus.DRAFT) {
            throw RestException.badRequest("Only DRAFT plans can be edited");
        }
        plan.setName(request.name());
        plan.setYear(request.year());
        plan.setMonth(request.month());
        plan.setDepartmentId(request.departmentId());
        plan.setNotes(request.notes());

        PprPlan saved = planRepository.save(plan);
        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.UPDATE,
                AuditModule.PPR_PLAN,
                "ППР план обновлен",
                plan,
                saved
        );
        return toDto(plan);
    }

    @Transactional
    public void delete(UUID id) {
        PprPlan plan = getPlan(id);
        if (plan.getStatus() != PlanStatus.DRAFT) {
            throw RestException.badRequest("Only DRAFT plans can be deleted");
        }
        plan.setDeleted(true);
        PprPlan saved = planRepository.save(plan);

        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.DELETE,
                AuditModule.PPR_PLAN,
                "ППР план удален",
                saved,
                null
        );
    }

    public PprPlanDto approve(UUID planId, UUID approverId) {
        PprPlan plan = getPlan(planId);
        if (plan.getStatus() != PlanStatus.DRAFT && plan.getStatus() != PlanStatus.GENERATED) {
            throw RestException.badRequest("Only DRAFT/GENERATED plans can be approved");
        }
        plan.setStatus(PlanStatus.APPROVED);
        plan.setApprovedById(approverId);
        return toDto(plan);
    }

    public PprTaskDto addTask(UUID planId, PprTaskRequest request) {
        validateClientProvidedTaskCode(request.code());
        PprPlan plan = getPlan(planId);
        assertPlanAllowsTaskEdit(plan);
        return PprTaskDto.from(saveManualTaskWithGeneratedCode(plan, request));
    }

    public PprTaskDto postponeTask(UUID taskId, PostponeTaskRequest request) {
        PprTask task = getTask(taskId);
        if (request.reason() == null || request.reason().isBlank()) {
            throw RestException.badRequest("Postpone reason is required");
        }
        if (task.getStatus() == PprTaskStatus.COMPLETED || task.getStatus() == PprTaskStatus.CANCELLED) {
            throw RestException.badRequest("Cannot postpone completed/cancelled PPR task");
        }
        task.setDueDate(request.newDueDate());
        task.setPostponeReason(request.reason());
        task.setStatus(PprTaskStatus.POSTPONED);

        PprTask saved = taskRepository.save(task);
        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.UPDATE,
                AuditModule.PPR_PLAN,
                "Задача ППР перенесена",
                task,
                saved
        );

        return PprTaskDto.from(task);
    }

    public PprTaskDto approveTask(UUID taskId) {
        PprTask task = getTask(taskId);
        assertPlanAllowsTaskApproval(task.getPlan());
        if (task.getStatus() != PprTaskStatus.PLANNED && task.getStatus() != PprTaskStatus.POSTPONED) {
            throw RestException.badRequest("Only PLANNED/POSTPONED PPR tasks can be approved");
        }
        task.setStatus(PprTaskStatus.APPROVED);

        PprTask saved = taskRepository.save(task);
        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.APPROVE,
                AuditModule.PPR_PLAN,
                "Задача ППР утверждена",
                task,
                saved
        );

        return PprTaskDto.from(task);
    }

    public PprTaskDto startTask(UUID taskId) {
        PprTask task = getTask(taskId);
        PprPlan plan = task.getPlan();
        assertPlanAllowsTaskStart(plan);
        assertTaskAllowsStart(task);

        if (plan.getStatus() == PlanStatus.APPROVED) {
            plan.setStatus(PlanStatus.IN_PROGRESS);
            planRepository.save(plan);
            auditBuilderService.log(
                    "ppr_plan",
                    plan.getId().toString(),
                    AuditAction.UPDATE,
                    AuditModule.PPR_PLAN,
                    "ППР план переведен в работу",
                    plan,
                    plan
            );
        }
        task.setStatus(PprTaskStatus.IN_PROGRESS);

        PprTask saved = taskRepository.save(task);
        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.UPDATE,
                AuditModule.PPR_PLAN,
                "Задача ППР начата",
                task,
                saved
        );

        return PprTaskDto.from(task);
    }

    public PprTaskDto completeTask(UUID taskId, Double actualLaborHours) {
        PprTask task = getTask(taskId);
        if (task.getStatus() != PprTaskStatus.IN_PROGRESS) {
            throw RestException.badRequest("Only IN_PROGRESS PPR tasks can be completed");
        }
        if (actualLaborHours != null && actualLaborHours < 0) {
            throw RestException.badRequest("Actual labor hours cannot be negative");
        }
        task.setStatus(PprTaskStatus.COMPLETED);
        task.setActualLaborHours(actualLaborHours);

        PprTask saved = taskRepository.save(task);

        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.UPDATE,
                AuditModule.PPR_PLAN,
                "Задача ППР завершена",
                task,
                saved
        );

        return PprTaskDto.from(task);
    }

    public PprTaskDto cancelTask(UUID taskId, String reason) {
        PprTask task = getTask(taskId);
        if (task.getStatus() == PprTaskStatus.COMPLETED || task.getStatus() == PprTaskStatus.CANCELLED) {
            throw RestException.badRequest("Cannot cancel completed/cancelled PPR task");
        }
        task.setStatus(PprTaskStatus.CANCELLED);
        if (reason != null && !reason.isBlank()) {
            task.setPostponeReason(reason);
        }

        PprTask saved = taskRepository.save(task);

        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.CANCEL,
                AuditModule.PPR_PLAN,
                "Задача ППР отменена",
                task,
                saved
        );
        return PprTaskDto.from(task);
    }

    @Transactional(readOnly = true)
    public List<PprTaskDto> findTasksByPlan(UUID planId) {
        return taskRepository.findAllByPlanIdAndIsDeletedFalseOrderByScheduledStartAscIdAsc(planId)
                .stream()
                .map(PprTaskDto::from)
                .toList();
    }

    private PprPlan getPlan(UUID id) {
        return planRepository.findByIdAndIsDeletedFalse(id)
                .orElseThrow(() -> RestException.notFound("PPR plan not found: " + id));
    }

    private PprPlanDto toDto(PprPlan plan) {
        Map<UUID, String> departmentNames = resolveDepartmentNames(List.of(plan));
        return PprPlanDto.from(plan, departmentNames.get(plan.getDepartmentId()));
    }

    private List<PprPlanDto> toDtos(List<PprPlan> plans) {
        Map<UUID, String> departmentNames = resolveDepartmentNames(plans);
        return plans.stream()
                .map(plan -> PprPlanDto.from(plan, departmentNames.get(plan.getDepartmentId())))
                .toList();
    }

    private Map<UUID, String> resolveDepartmentNames(List<PprPlan> plans) {
        List<UUID> departmentIds = plans.stream()
                .map(PprPlan::getDepartmentId)
                .filter(Objects::nonNull)
                .distinct()
                .toList();
        if (departmentIds.isEmpty()) {
            return Map.of();
        }
        List<Department> departments = departmentRepository.findAllByIdInAndIsDeletedFalse(departmentIds);
        if (departments == null || departments.isEmpty()) {
            return Map.of();
        }
        return departments.stream()
                .collect(Collectors.toMap(
                        Department::getId,
                        Department::getName,
                        (left, right) -> left
                ));
    }

    private PprTask getTask(UUID id) {
        return taskRepository.findByIdAndIsDeletedFalse(id)
                .orElseThrow(() -> RestException.notFound("PPR task not found: " + id));
    }

    private void applyTaskMutableFields(PprTask task, PprPlan plan, PprTaskRequest request) {
        LocalDateTime scheduledStart = resolveScheduledStart(request);
        LocalDateTime scheduledEnd = resolveScheduledEnd(request);
        validateTaskDateRange(scheduledStart, scheduledEnd);

        task.setPlan(plan);
        task.setRegulationId(request.regulationId());
        task.setEquipmentId(request.equipmentId());
        task.setTitle(request.title());
        task.setScheduledStart(scheduledStart);
        task.setScheduledEnd(scheduledEnd);
        task.setDueDate(request.dueDate() != null ? request.dueDate() : scheduledEnd);
        task.setPlannedLaborHours(request.plannedLaborHours());
        if (request.priority() != null) {
            task.setPriority(request.priority());
        }
    }

    private LocalDateTime resolveScheduledStart(PprTaskRequest request) {
        if (request.scheduledStart() != null) {
            return request.scheduledStart();
        }
        if (request.startDate() != null) {
            return request.startDate().atStartOfDay();
        }
        throw RestException.badRequest("PPR task startDate or scheduledStart is required");
    }

    private LocalDateTime resolveScheduledEnd(PprTaskRequest request) {
        if (request.scheduledEnd() != null) {
            return request.scheduledEnd();
        }
        if (request.endDate() != null) {
            return request.endDate().atTime(LocalTime.of(23, 59, 59));
        }
        throw RestException.badRequest("PPR task endDate or scheduledEnd is required");
    }

    private void validateTaskDateRange(LocalDateTime scheduledStart, LocalDateTime scheduledEnd) {
        if (scheduledEnd.isBefore(scheduledStart)) {
            throw RestException.badRequest("PPR task end date must not be before start date");
        }
    }

    private void validateClientProvidedTaskCode(String code) {
        if (code != null && !code.isBlank()) {
            throw RestException.badRequest(CLIENT_CODE_REJECT_MESSAGE);
        }
    }

    private void assertPlanAllowsTaskEdit(PprPlan plan) {
        if (!isPlanEditable(plan.getStatus())) {
            throw RestException.badRequest("PPR tasks can be edited only while parent plan is DRAFT or GENERATED");
        }
    }

    private void assertPlanAllowsTaskApproval(PprPlan plan) {
        if (!isPlanExecutionAllowed(plan.getStatus())) {
            throw RestException.badRequest("PPR task can be approved only after the parent PPR plan is approved");
        }
    }

    private void assertPlanAllowsTaskStart(PprPlan plan) {
        if (!isPlanExecutionAllowed(plan.getStatus())) {
            throw RestException.badRequest("Task can start only after the parent PPR plan is approved");
        }
    }

    private void assertTaskAllowsStart(PprTask task) {
        if (task.getStatus() != PprTaskStatus.APPROVED) {
            throw RestException.badRequest("Only APPROVED PPR tasks can be started");
        }
    }

    private boolean isPlanExecutionAllowed(PlanStatus status) {
        return PLAN_EXECUTION_STATUSES.contains(status);
    }

    private boolean isPlanEditable(PlanStatus status) {
        return PLAN_TASK_EDIT_STATUSES.contains(status);
    }

    private PprTask saveManualTaskWithGeneratedCode(PprPlan plan, PprTaskRequest request) {
        int year = Year.now().getValue();
        String codePrefix = "PPR-TASK-" + year + "-";
        long sequence = taskRepository.maxSequenceByCodePrefix(codePrefix) + 1;

        for (int attempt = 0; attempt < MAX_TASK_CODE_GENERATION_ATTEMPTS; attempt++) {
            String code = formatCode("PPR-TASK", year, sequence + attempt);
            if (taskRepository.existsByCode(code)) {
                continue;
            }

            PprTask task = new PprTask();
            task.setCode(code);
            applyTaskMutableFields(task, plan, request);

            try {
                PprTask saved = taskRepository.save(task);
                plan.getTasks().add(saved);
                return saved;
            } catch (DataIntegrityViolationException ex) {
                if (isTaskCodeConflict(ex)) {
                    continue;
                }
                throw ex;
            }
        }

        throw RestException.conflict("Could not generate unique PPR task code");
    }

    private boolean isTaskCodeConflict(DataIntegrityViolationException ex) {
        Throwable root = ex.getMostSpecificCause();
        String message = root != null ? root.getMessage() : ex.getMessage();
        if (message == null) {
            return false;
        }
        String normalized = message.toLowerCase(Locale.ROOT);
        return normalized.contains("ppr_tasks_code_key")
                || (normalized.contains("ppr_tasks")
                && normalized.contains("duplicate")
                && normalized.contains("code"));
    }

    private PprPlan saveWithGeneratedPlanCode(PprPlanRequest request) {
        int year = Year.now().getValue();
        String codePrefix = "PPR-" + year + "-";
        long sequence = planRepository.maxSequenceByCodePrefix(codePrefix) + 1;

        for (int attempt = 0; attempt < MAX_PLAN_CODE_GENERATION_ATTEMPTS; attempt++) {
            String code = formatCode("PPR", year, sequence + attempt);
            if (planRepository.existsByCodeAndIsDeletedFalse(code)) {
                continue;
            }

            PprPlan plan = new PprPlan();
            plan.setCode(code);
            applyPlanMutableFields(plan, request);

            try {
                return planRepository.save(plan);
            } catch (DataIntegrityViolationException ex) {
                if (isPlanCodeConflict(ex)) {
                    continue;
                }
                throw ex;
            }
        }

        throw RestException.conflict("Could not generate unique PPR plan code");
    }

    private void applyPlanMutableFields(PprPlan plan, PprPlanRequest request) {
        plan.setName(request.name());
        plan.setYear(request.year());
        plan.setMonth(request.month());
        plan.setDepartmentId(request.departmentId());
        plan.setCreatedById(request.createdById());
        plan.setNotes(request.notes());
    }

    private boolean isPlanCodeConflict(DataIntegrityViolationException ex) {
        Throwable root = ex.getMostSpecificCause();
        String message = root != null ? root.getMessage() : ex.getMessage();
        if (message == null) {
            return false;
        }
        String normalized = message.toLowerCase(Locale.ROOT);
        return normalized.contains("ppr_plans_code_key")
                || (normalized.contains("ppr_plans")
                && normalized.contains("duplicate")
                && normalized.contains("code"));
    }

    private String formatCode(String prefix, int year, long sequence) {
        return "%s-%d-%04d".formatted(prefix, year, sequence);
    }

    private long safe(Long value) {
        return value == null ? 0L : value;
    }

}
