package com.toir.service;

import com.toir.dto.pprplanning.*;
import com.toir.entity.Department;
import com.toir.entity.PprPlan;
import com.toir.entity.PprPlanTarget;
import com.toir.entity.PprTask;
import com.toir.entity.equipment.Equipment;
import com.toir.entity.equipment.EquipmentType;
import com.toir.entity.maintenance.EquipmentMaintenanceRule;
import com.toir.entity.maintenance.MaintenanceRegulation;
import com.toir.entity.maintenance.WorkOrder;
import com.toir.enums.AuditAction;
import com.toir.enums.AuditModule;
import com.toir.enums.PlanStatus;
import com.toir.enums.PprFrequency;
import com.toir.enums.PprScheduleType;
import com.toir.enums.PprScopeType;
import com.toir.enums.PprTargetType;
import com.toir.enums.PprTaskStatus;
import com.toir.enums.PprType;
import com.toir.exception.RestException;
import com.toir.repository.PprPlanRepository;
import com.toir.repository.PprPlanStatsProjection;
import com.toir.repository.PprTaskRepository;
import com.toir.repository.WorkOrderRepository;
import com.toir.repository.department.DepartmentRepository;
import com.toir.repository.equipment.EquipmentRepository;
import com.toir.repository.equipment.EquipmentTypeRepository;
import com.toir.repository.maintenance.EquipmentMaintenanceRuleRepository;
import com.toir.repository.maintenance.MaintenanceRegulationRepository;
import com.toir.util.AuditBuilderService;
import com.toir.util.AuditSerializationService;
import com.toir.util.PaginationUtils;
import com.toir.service.repair.RepairMaterialUsageService;
import jakarta.persistence.EntityManager;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Year;
import java.util.Comparator;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.LinkedHashSet;
import java.util.stream.Collectors;

@Service
@Transactional
@RequiredArgsConstructor
@Slf4j
public class PprPlanService {

    private final PprPlanRepository planRepository;
    private final PprTaskRepository taskRepository;
    private final WorkOrderRepository workOrderRepository;
    private final DepartmentRepository departmentRepository;
    private final EquipmentRepository equipmentRepository;
    private final EquipmentTypeRepository equipmentTypeRepository;
    private final EquipmentMaintenanceRuleRepository equipmentMaintenanceRuleRepository;
    private final MaintenanceRegulationRepository maintenanceRegulationRepository;
    private final PprGeneratorService generatorService;
    private final AuditBuilderService auditBuilderService;
    private final AuditSerializationService auditSerializationService;
    private final RepairMaterialUsageService repairMaterialUsageService;
    private final EntityManager entityManager;
    private static final int MAX_PLAN_CODE_GENERATION_ATTEMPTS = 50;
    private static final int MAX_TASK_CODE_GENERATION_ATTEMPTS = 50;
    private static final String CLIENT_CODE_REJECT_MESSAGE =
            "code is generated by backend and must not be provided";
    private static final Set<PlanStatus> PLAN_TASK_EDIT_STATUSES =
            EnumSet.of(PlanStatus.DRAFT, PlanStatus.GENERATED);
    private static final Set<PlanStatus> PLAN_EXECUTION_STATUSES =
            EnumSet.of(PlanStatus.APPROVED, PlanStatus.IN_PROGRESS);
    private static final Set<String> LIST_SORT_FIELDS = Set.of("taskCount", "intervalHours", "status", "fromDate", "pprType");


    @Transactional(readOnly = true)
    public List<PprPlanDto> findAll() {
        return toDtos(planRepository.findAllByIsDeletedFalseOrderByUpdatedAtDesc());
    }

    @Transactional(readOnly = true)
    public List<PprPlanDto> findAll(Integer year, Integer month, Integer day, UUID departmentId) {
        validateDateFilterParts(year, month, day);
        return toDtos(planRepository.searchPlans(year, month, day, departmentId));
    }

    @Transactional(readOnly = true)
    public List<PprPlanDto> findAll(Integer year, Integer month, Integer day, UUID departmentId, UUID equipmentId) {
        if (equipmentId == null) {
            return findAll(year, month, day, departmentId);
        }
        validateDateFilterParts(year, month, day);
        return toDtos(planRepository.searchPlans(year, month, day, departmentId, equipmentId), equipmentId);
    }

    @Transactional(readOnly = true)
    public Page<PprPlanDto> findAllUnpaged(Integer year, Integer month, Integer day, UUID departmentId) {
        return findAllUnpaged(year, month, day, departmentId, null, "asc");
    }

    @Transactional(readOnly = true)
    public Page<PprPlanDto> findAllUnpaged(Integer year, Integer month, Integer day, UUID departmentId, String sortBy, String sortDir) {
        List<PprPlanDto> plans = findAll(year, month, day, departmentId);
        plans = sortIfRequested(plans, sortBy, sortDir);
        return PaginationUtils.page(plans, 0, PaginationUtils.pageSizeFromList(0, plans.size()), plans.size());
    }

    @Transactional(readOnly = true)
    public Page<PprPlanDto> findAllUnpaged(Integer year, Integer month, Integer day, UUID departmentId, UUID equipmentId) {
        return findAllUnpaged(year, month, day, departmentId, equipmentId, null, "asc");
    }

    @Transactional(readOnly = true)
    public Page<PprPlanDto> findAllUnpaged(Integer year, Integer month, Integer day, UUID departmentId, UUID equipmentId, String sortBy, String sortDir) {
        if (equipmentId == null) {
            return findAllUnpaged(year, month, day, departmentId, sortBy, sortDir);
        }
        List<PprPlanDto> plans = findAll(year, month, day, departmentId, equipmentId);
        plans = sortIfRequested(plans, sortBy, sortDir);
        return PaginationUtils.page(plans, 0, PaginationUtils.pageSizeFromList(0, plans.size()), plans.size());
    }

    @Transactional(readOnly = true)
    public Page<PprPlanDto> findAll(Integer year, Integer month, Integer day, UUID departmentId, int page, int size) {
        return findAll(year, month, day, departmentId, page, size, null, "asc");
    }

    @Transactional(readOnly = true)
    public Page<PprPlanDto> findAll(Integer year, Integer month, Integer day, UUID departmentId, int page, int size, String sortBy, String sortDir) {
        if (isListSort(sortBy)) {
            return PaginationUtils.page(sortIfRequested(findAll(year, month, day, departmentId), sortBy, sortDir), page, size);
        }
        validateDateFilterParts(year, month, day);
        Page<PprPlan> plans = planRepository.searchPlans(
                        year,
                        month,
                        day,
                        departmentId,
                        PaginationUtils.pageRequest(page, size)
                );
        Map<UUID, String> departmentNames = resolveDepartmentNames(plans.getContent());
        List<PprTask> tasks = collectTasks(plans.getContent());
        Map<UUID, String> equipmentNames = resolveEquipmentNames(plans.getContent(), tasks);
        Map<UUID, String> equipmentTypeNames = resolveEquipmentTypeNames(plans.getContent());
        Map<UUID, String> regulationNames = resolveRegulationNames(plans.getContent(), tasks);
        Map<UUID, EquipmentMaintenanceRule> ruleById = loadMaintenanceRuleById(tasks);
        return plans.map(plan -> PprPlanDto.from(
                plan,
                departmentName(departmentNames, plan),
                ruleById,
                equipmentNames,
                equipmentTypeNames,
                regulationNames
        ));
    }

    @Transactional(readOnly = true)
    public Page<PprPlanDto> findAll(Integer year, Integer month, Integer day, UUID departmentId, UUID equipmentId, int page, int size) {
        return findAll(year, month, day, departmentId, equipmentId, page, size, null, "asc");
    }

    @Transactional(readOnly = true)
    public Page<PprPlanDto> findAll(Integer year, Integer month, Integer day, UUID departmentId, UUID equipmentId, int page, int size, String sortBy, String sortDir) {
        if (equipmentId == null) {
            return findAll(year, month, day, departmentId, page, size, sortBy, sortDir);
        }
        if (isListSort(sortBy)) {
            return PaginationUtils.page(sortIfRequested(findAll(year, month, day, departmentId, equipmentId), sortBy, sortDir), page, size);
        }
        validateDateFilterParts(year, month, day);
        Page<PprPlan> plans = planRepository.searchPlans(
                        year,
                        month,
                        day,
                        departmentId,
                        equipmentId,
                        PaginationUtils.pageRequest(page, size)
                );
        Map<UUID, String> departmentNames = resolveDepartmentNames(plans.getContent());
        List<PprTask> tasks = collectTasks(plans.getContent(), equipmentId);
        Map<UUID, String> equipmentNames = resolveEquipmentNames(plans.getContent(), tasks);
        Map<UUID, String> equipmentTypeNames = resolveEquipmentTypeNames(plans.getContent());
        Map<UUID, String> regulationNames = resolveRegulationNames(plans.getContent(), tasks);
        Map<UUID, EquipmentMaintenanceRule> ruleById = loadMaintenanceRuleById(tasks);
        return plans.map(plan -> PprPlanDto.from(
                plan,
                departmentName(departmentNames, plan),
                ruleById,
                equipmentNames,
                equipmentTypeNames,
                regulationNames,
                equipmentId
        ));
    }

    private boolean isListSort(String sortBy) {
        if (sortBy == null || sortBy.isBlank()) {
            return false;
        }
        return LIST_SORT_FIELDS.contains(sortBy.trim());
    }

    private List<PprPlanDto> sortIfRequested(List<PprPlanDto> plans, String sortBy, String sortDir) {
        if (!isListSort(sortBy)) {
            return plans;
        }
        Comparator<PprPlanDto> comparator = switch (sortBy.trim()) {
            case "taskCount" -> Comparator.comparingLong(PprPlanDto::taskCount);
            case "intervalHours" -> Comparator.comparing(
                    PprPlanDto::intervalHours,
                    Comparator.nullsLast(Comparator.naturalOrder())
            );
            case "status" -> Comparator.comparing(
                    PprPlanDto::status,
                    Comparator.nullsLast(Comparator.naturalOrder())
            );
            case "fromDate" -> Comparator.comparing(
                    PprPlanDto::fromDate,
                    Comparator.nullsLast(Comparator.naturalOrder())
            );
            case "pprType" -> Comparator.comparing(
                    PprPlanDto::pprType,
                    Comparator.nullsLast(Comparator.naturalOrder())
            );
            default -> throw RestException.badRequest("Unsupported PPR plan sort: " + sortBy);
        };
        if ("desc".equalsIgnoreCase(sortDir)) {
            comparator = comparator.reversed();
        }
        return plans.stream().sorted(comparator).toList();
    }

    @Transactional(readOnly = true)
    public PprPlanStatsResponse getStats(Integer year, Integer month, Integer day, UUID departmentId) {
        validateDateFilterParts(year, month, day);
        PprPlanStatsProjection stats = planRepository.getStats(year, month, day, departmentId);
        if (stats == null) {
            return new PprPlanStatsResponse(0, 0, 0, 0, 0, 0, 0, 0);
        }
        return new PprPlanStatsResponse(
                safe(stats.getTotalPlans()),
                safe(stats.getDraftPlans()),
                safe(stats.getGeneratedPlans()),
                safe(stats.getApprovedPlans()),
                safe(stats.getPlannedTasks()),
                safe(stats.getInProgressTasks()),
                safe(stats.getCompletedTasks()),
                safe(stats.getOverdueTasks())
        );
    }

    @Transactional(readOnly = true)
    public Page<PprTaskDto> findTasks(UUID departmentId,
                                      UUID equipmentId,
                                      PprTaskStatus status,
                                      int page,
                                      int size) {
        Page<PprTask> tasks = taskRepository.searchTasks(
                departmentId,
                equipmentId,
                status,
                PageRequest.of(page, size)
        );
        List<PprTask> content = tasks.getContent();
        Map<UUID, EquipmentMaintenanceRule> ruleById = loadMaintenanceRuleById(content);
        Map<UUID, String> equipmentNames = resolveEquipmentNames(List.of(), content);
        Map<UUID, String> regulationNames = resolveRegulationNames(List.of(), content);
        return tasks.map(task -> PprTaskDto.from(task, ruleById, equipmentNames, regulationNames));
    }

    @Transactional(readOnly = true)
    public PprTaskStatsResponse getTaskStats(UUID departmentId, UUID equipmentId, PprTaskStatus status) {
        List<PprTask> tasks = taskRepository.searchTasks(departmentId, equipmentId, status);
        Map<PprTaskStatus, Long> statusBreakdown = new EnumMap<>(PprTaskStatus.class);
        for (PprTaskStatus taskStatus : PprTaskStatus.values()) {
            statusBreakdown.put(taskStatus, 0L);
        }
        for (PprTask task : tasks) {
            statusBreakdown.computeIfPresent(task.getStatus(), (ignored, count) -> count + 1);
        }
        long totalTasks = tasks.size();
        long completedTasks = statusBreakdown.get(PprTaskStatus.COMPLETED);
        double completionRate = totalTasks > 0 ? (double) completedTasks / totalTasks * 100 : 0;
        return new PprTaskStatsResponse(totalTasks, completedTasks, completionRate, statusBreakdown);
    }

    @Transactional(readOnly = true)
    public PprPlanDto findById(UUID id) {
        return toDto(getPlan(id));
    }

    @Transactional
    public PprPlanDto create(PprPlanRequest request) {
        PprPlan saved = saveWithGeneratedPlanCode(request);
        log.info("Calling PprGeneratorService.generateForPlan after PPR plan create: planId={} planCode={} status={} departmentId={}",
                saved.getId(), saved.getCode(), saved.getStatus(), saved.getDepartmentId());
        PprGeneratorService.GenerationResult generationResult = generatorService.generateForPlan(saved.getId());

        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.CREATE,
                AuditModule.PPR_PLAN,
                "ППР план создан",
                null,
                saved
        );

        PprPlanDto dto = toDto(reloadPlan(saved.getId()));
        if (generationResult.created() == 0) {
            String message = generationResult.message() != null
                    ? generationResult.message()
                    : "PPR plan was created, but no PPR tasks were generated. Check plan targets, schedule, frequency, equipment status, and maintenance due conditions.";
            return dto.withGenerationMessage(message)
                    .withGenerationDiagnostics(generationResult.generationDiagnostics());
        }
        String message = generationResult.message() != null
                ? generationResult.message()
                : "PPR plan was created and %d PPR task(s) were generated.".formatted(generationResult.created());
        return dto.withGenerationMessage(message)
                .withGenerationDiagnostics(generationResult.generationDiagnostics());
    }

    @Transactional
    public PprPlanDto update(UUID id, PprPlanRequest request) {
        PprPlan plan = getPlan(id);
        if (plan.getStatus() != PlanStatus.DRAFT) {
            throw RestException.badRequest("Only DRAFT plans can be edited");
        }
        applyPlanMutableFields(plan, request);

        PprPlan saved = planRepository.saveAndFlush(plan);
        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.UPDATE,
                AuditModule.PPR_PLAN,
                "ППР план обновлен",
                plan,
                saved
        );
        return toDto(reloadPlan(saved.getId()));
    }

    @Transactional
    public void delete(UUID id) {
        PprPlan plan = getPlan(id);
        if (plan.getStatus() != PlanStatus.DRAFT) {
            throw RestException.badRequest("Only DRAFT plans can be deleted");
        }
        plan.setDeleted(true);
        PprPlan saved = planRepository.save(plan);

        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.DELETE,
                AuditModule.PPR_PLAN,
                "ППР план удален",
                saved,
                null
        );
    }

    public PprPlanDto finalizeApprovalFromApprovalRequest(UUID planId, UUID approverId) {
        PprPlan plan = getPlan(planId);
        validateCanApprove(plan);
        plan.setStatus(PlanStatus.APPROVED);
        plan.setApprovedById(approverId);
        PprPlan saved = planRepository.saveAndFlush(plan);
        return toDto(reloadPlan(saved.getId()));
    }

    /**
     * @deprecated Approval decisions must go through ApprovalService. This wrapper remains for tests and
     * compatibility with older internal callers; approval handlers should call
     * {@link #finalizeApprovalFromApprovalRequest(UUID, UUID)}.
     */
    @Deprecated(forRemoval = false)
    public PprPlanDto approve(UUID planId, UUID approverId) {
        return finalizeApprovalFromApprovalRequest(planId, approverId);
    }

    public PprPlanDto validateCanApprove(UUID planId) {
        PprPlan plan = getPlan(planId);
        validateCanApprove(plan);
        return toDto(plan);
    }

    private void validateCanApprove(PprPlan plan) {
        if (plan.getStatus() != PlanStatus.DRAFT && plan.getStatus() != PlanStatus.GENERATED) {
            throw RestException.badRequest("Only DRAFT/GENERATED plans can be approved");
        }
    }

    public PprTaskDto addTask(UUID planId, PprTaskRequest request) {
        validateClientProvidedTaskCode(request.code());
        PprPlan plan = getPlan(planId);
        assertPlanAllowsTaskEdit(plan);
        return PprTaskDto.from(saveManualTaskWithGeneratedCode(plan, request));
    }

    public PprTaskDto postponeTask(UUID taskId, PostponeTaskRequest request) {
        PprTask task = getTask(taskId);
        if (request.reason() == null || request.reason().isBlank()) {
            throw RestException.badRequest("Postpone reason is required");
        }
        if (task.getStatus() == PprTaskStatus.COMPLETED || task.getStatus() == PprTaskStatus.CANCELLED) {
            throw RestException.badRequest("Cannot postpone completed/cancelled PPR task");
        }
        task.setDueDate(request.newDueDate());
        task.setPostponeReason(request.reason());
        task.setStatus(PprTaskStatus.POSTPONED);

        PprTask saved = taskRepository.save(task);
        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.UPDATE,
                AuditModule.PPR_PLAN,
                "Задача ППР перенесена",
                task,
                saved
        );

        return PprTaskDto.from(task);
    }

    public PprTaskDto approveTask(UUID taskId) {
        PprTask task = getTask(taskId);
        assertPlanAllowsTaskApproval(task.getPlan());
        if (task.getStatus() != PprTaskStatus.PLANNED && task.getStatus() != PprTaskStatus.POSTPONED) {
            throw RestException.badRequest("Only PLANNED/POSTPONED PPR tasks can be approved");
        }
        task.setStatus(PprTaskStatus.APPROVED);

        PprTask saved = taskRepository.save(task);
        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.APPROVE,
                AuditModule.PPR_PLAN,
                "Задача ППР утверждена",
                task,
                saved
        );

        return PprTaskDto.from(task);
    }

    public PprTaskDto startTask(UUID taskId) {
        PprTask task = getTask(taskId);
        PprPlan plan = task.getPlan();
        assertPlanAllowsTaskStart(plan);
        assertTaskAllowsStart(task);

        if (plan.getStatus() == PlanStatus.APPROVED) {
            plan.setStatus(PlanStatus.IN_PROGRESS);
            planRepository.save(plan);
            auditBuilderService.log(
                    "ppr_plan",
                    plan.getId().toString(),
                    AuditAction.UPDATE,
                    AuditModule.PPR_PLAN,
                    "ППР план переведен в работу",
                    plan,
                    plan
            );
        }
        task.setStatus(PprTaskStatus.IN_PROGRESS);

        PprTask saved = taskRepository.save(task);
        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.UPDATE,
                AuditModule.PPR_PLAN,
                "Задача ППР начата",
                task,
                saved
        );

        return PprTaskDto.from(task);
    }

    public PprTaskDto completeTask(UUID taskId, Double actualLaborHours) {
        return completeTask(taskId, new CompletePprTaskRequest(actualLaborHours, null));
    }

    public PprTaskDto completeTask(UUID taskId, CompletePprTaskRequest request) {
        PprTask task = getTask(taskId);
        if (task.getStatus() != PprTaskStatus.IN_PROGRESS) {
            throw RestException.badRequest("Only IN_PROGRESS PPR tasks can be completed");
        }
        Double actualLaborHours = request == null ? null : request.actualLaborHours();
        if (actualLaborHours != null && actualLaborHours < 0) {
            throw RestException.badRequest("Actual labor hours cannot be negative");
        }
        issueTaskCompletionMaterials(taskId, request);
        task.setStatus(PprTaskStatus.COMPLETED);
        task.setActualLaborHours(actualLaborHours);

        PprTask saved = taskRepository.save(task);

        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.UPDATE,
                AuditModule.PPR_PLAN,
                "Задача ППР завершена",
                task,
                saved
        );

        return PprTaskDto.from(task);
    }

    private void issueTaskCompletionMaterials(UUID taskId, CompletePprTaskRequest request) {
        if (request == null || request.materialUsages() == null || request.materialUsages().isEmpty()) {
            return;
        }
        WorkOrder workOrder = workOrderRepository.findFirstByPprTaskIdAndIsDeletedFalseOrderByUpdatedAtDesc(taskId)
                .orElseThrow(() -> RestException.badRequest("Material usage requires a linked Work Order"));
        request.materialUsages().forEach(usage -> repairMaterialUsageService.register(workOrder.getId(), usage));
    }

    public PprTaskDto cancelTask(UUID taskId, String reason) {
        PprTask task = getTask(taskId);
        if (task.getStatus() == PprTaskStatus.COMPLETED || task.getStatus() == PprTaskStatus.CANCELLED) {
            throw RestException.badRequest("Cannot cancel completed/cancelled PPR task");
        }
        task.setStatus(PprTaskStatus.CANCELLED);
        if (reason != null && !reason.isBlank()) {
            task.setPostponeReason(reason);
        }

        PprTask saved = taskRepository.save(task);

        auditBuilderService.log(
                "ppr_plan",
                saved.getId().toString(),
                AuditAction.CANCEL,
                AuditModule.PPR_PLAN,
                "Задача ППР отменена",
                task,
                saved
        );
        return PprTaskDto.from(task);
    }

    @Transactional(readOnly = true)
    public List<PprTaskDto> findTasksByPlan(UUID planId) {
        List<PprTask> tasks = taskRepository.findAllByPlanIdAndIsDeletedFalseOrderByScheduledStartAscIdAsc(planId);
        Map<UUID, EquipmentMaintenanceRule> ruleById = loadMaintenanceRuleById(tasks);
        Map<UUID, String> equipmentNames = resolveEquipmentNames(List.of(), tasks);
        Map<UUID, String> regulationNames = resolveRegulationNames(List.of(), tasks);
        return tasks.stream()
                .map(task -> PprTaskDto.from(task, ruleById, equipmentNames, regulationNames))
                .toList();
    }

    private PprPlan getPlan(UUID id) {
        return planRepository.findByIdAndIsDeletedFalse(id)
                .orElseThrow(() -> RestException.notFound("PPR plan not found: " + id));
    }

    private PprPlan reloadPlan(UUID id) {
        entityManager.clear();
        return getPlan(id);
    }

    private PprPlanDto toDto(PprPlan plan) {
        Map<UUID, String> departmentNames = resolveDepartmentNames(List.of(plan));
        List<PprTask> tasks = plan.getTasks();
        return PprPlanDto.from(
                plan,
                departmentName(departmentNames, plan),
                loadMaintenanceRuleById(tasks),
                resolveEquipmentNames(List.of(plan), tasks),
                resolveEquipmentTypeNames(List.of(plan)),
                resolveRegulationNames(List.of(plan), tasks)
        );
    }

    private List<PprPlanDto> toDtos(List<PprPlan> plans) {
        return toDtos(plans, null);
    }

    private List<PprPlanDto> toDtos(List<PprPlan> plans, UUID equipmentId) {
        Map<UUID, String> departmentNames = resolveDepartmentNames(plans);
        List<PprTask> tasks = collectTasks(plans, equipmentId);
        Map<UUID, EquipmentMaintenanceRule> ruleById = loadMaintenanceRuleById(tasks);
        Map<UUID, String> equipmentNames = resolveEquipmentNames(plans, tasks);
        Map<UUID, String> equipmentTypeNames = resolveEquipmentTypeNames(plans);
        Map<UUID, String> regulationNames = resolveRegulationNames(plans, tasks);
        return plans.stream()
                .map(plan -> PprPlanDto.from(
                        plan,
                        departmentName(departmentNames, plan),
                        ruleById,
                        equipmentNames,
                        equipmentTypeNames,
                        regulationNames,
                        equipmentId
                ))
                .toList();
    }

    private List<PprTask> collectTasks(List<PprPlan> plans) {
        return collectTasks(plans, null);
    }

    private List<PprTask> collectTasks(List<PprPlan> plans, UUID equipmentId) {
        return plans.stream()
                .flatMap(plan -> plan.getTasks().stream())
                .filter(task -> !task.isDeleted())
                .filter(task -> equipmentId == null || equipmentId.equals(task.getEquipmentId()))
                .toList();
    }

    private Map<UUID, EquipmentMaintenanceRule> loadMaintenanceRuleById(List<PprTask> tasks) {
        List<UUID> ruleIds = tasks.stream()
                .map(PprTask::getEquipmentMaintenanceRuleId)
                .filter(Objects::nonNull)
                .distinct()
                .toList();
        if (ruleIds.isEmpty()) {
            return Map.of();
        }
        return equipmentMaintenanceRuleRepository.findAllByIdInAndIsDeletedFalse(ruleIds).stream()
                .collect(Collectors.toMap(EquipmentMaintenanceRule::getId, rule -> rule, (left, right) -> left));
    }

    private Map<UUID, String> resolveEquipmentNames(List<PprPlan> plans, List<PprTask> tasks) {
        List<UUID> equipmentIds = distinctUuidStream(java.util.stream.Stream.concat(
                tasks.stream().map(PprTask::getEquipmentId),
                plans.stream()
                        .flatMap(plan -> plan.getTargets().stream())
                        .map(PprPlanTarget::getEquipmentId)
        ));
        if (equipmentIds.isEmpty()) {
            return Map.of();
        }
        return equipmentRepository.findAllByIdInAndIsDeletedFalse(equipmentIds).stream()
                .filter(equipment -> equipment.getName() != null)
                .collect(Collectors.toMap(Equipment::getId, Equipment::getName, (left, right) -> left));
    }

    private Map<UUID, String> resolveEquipmentTypeNames(List<PprPlan> plans) {
        List<UUID> equipmentTypeIds = distinctUuidStream(plans.stream()
                .flatMap(plan -> plan.getTargets().stream())
                .map(PprPlanTarget::getEquipmentTypeId));
        if (equipmentTypeIds.isEmpty()) {
            return Map.of();
        }
        return equipmentTypeRepository.findAllByIdInAndIsDeletedFalse(equipmentTypeIds).stream()
                .filter(equipmentType -> equipmentType.getName() != null)
                .collect(Collectors.toMap(EquipmentType::getId, EquipmentType::getName, (left, right) -> left));
    }

    private Map<UUID, String> resolveRegulationNames(List<PprPlan> plans, List<PprTask> tasks) {
        List<UUID> regulationIds = distinctUuidStream(java.util.stream.Stream.concat(
                tasks.stream().map(PprTask::getRegulationId),
                plans.stream()
                        .flatMap(plan -> plan.getTargets().stream())
                        .map(PprPlanTarget::getRegulationId)
        ));
        if (regulationIds.isEmpty()) {
            return Map.of();
        }
        return maintenanceRegulationRepository.findAllByIdInAndIsDeletedFalse(regulationIds).stream()
                .filter(regulation -> regulation.getName() != null)
                .collect(Collectors.toMap(MaintenanceRegulation::getId, MaintenanceRegulation::getName, (left, right) -> left));
    }

    private List<UUID> distinctUuidStream(java.util.stream.Stream<UUID> ids) {
        return ids.filter(Objects::nonNull)
                .distinct()
                .toList();
    }

    private String departmentName(Map<UUID, String> departmentNames, PprPlan plan) {
        return plan.getDepartmentId() == null ? null : departmentNames.get(plan.getDepartmentId());
    }

    private Map<UUID, String> resolveDepartmentNames(List<PprPlan> plans) {
        List<UUID> departmentIds = plans.stream()
                .map(PprPlan::getDepartmentId)
                .filter(Objects::nonNull)
                .distinct()
                .toList();
        if (departmentIds.isEmpty()) {
            return Map.of();
        }
        List<Department> departments = departmentRepository.findAllByIdInAndIsDeletedFalse(departmentIds);
        if (departments == null || departments.isEmpty()) {
            return Map.of();
        }
        return departments.stream()
                .collect(Collectors.toMap(
                        Department::getId,
                        Department::getName,
                        (left, right) -> left
                ));
    }

    private PprTask getTask(UUID id) {
        return taskRepository.findByIdAndIsDeletedFalse(id)
                .orElseThrow(() -> RestException.notFound("PPR task not found: " + id));
    }

    private void applyTaskMutableFields(PprTask task, PprPlan plan, PprTaskRequest request) {
        LocalDateTime scheduledStart = resolveScheduledStart(request);
        LocalDateTime scheduledEnd = resolveScheduledEnd(request);
        validateTaskDateRange(scheduledStart, scheduledEnd);

        task.setPlan(plan);
        task.setRegulationId(request.regulationId());
        task.setEquipmentId(request.equipmentId());
        task.setTitle(request.title());
        task.setScheduledStart(scheduledStart);
        task.setScheduledEnd(scheduledEnd);
        task.setDueDate(request.dueDate() != null ? request.dueDate() : scheduledEnd);
        task.setPlannedLaborHours(request.plannedLaborHours());
        if (request.priority() != null) {
            task.setPriority(request.priority());
        }
    }

    private LocalDateTime resolveScheduledStart(PprTaskRequest request) {
        if (request.scheduledStart() != null) {
            return request.scheduledStart();
        }
        if (request.startDate() != null) {
            return request.startDate().atStartOfDay();
        }
        throw RestException.badRequest("PPR task startDate or scheduledStart is required");
    }

    private LocalDateTime resolveScheduledEnd(PprTaskRequest request) {
        if (request.scheduledEnd() != null) {
            return request.scheduledEnd();
        }
        if (request.endDate() != null) {
            return request.endDate().atTime(LocalTime.of(23, 59, 59));
        }
        throw RestException.badRequest("PPR task endDate or scheduledEnd is required");
    }

    private void validateTaskDateRange(LocalDateTime scheduledStart, LocalDateTime scheduledEnd) {
        if (scheduledEnd.isBefore(scheduledStart)) {
            throw RestException.badRequest("PPR task end date must not be before start date");
        }
    }

    private void validateClientProvidedTaskCode(String code) {
        if (code != null && !code.isBlank()) {
            throw RestException.badRequest(CLIENT_CODE_REJECT_MESSAGE);
        }
    }

    private void assertPlanAllowsTaskEdit(PprPlan plan) {
        if (!isPlanEditable(plan.getStatus())) {
            throw RestException.badRequest("PPR tasks can be edited only while parent plan is DRAFT or GENERATED");
        }
    }

    private void assertPlanAllowsTaskApproval(PprPlan plan) {
        if (!isPlanExecutionAllowed(plan.getStatus())) {
            throw RestException.badRequest("PPR task can be approved only after the parent PPR plan is approved");
        }
    }

    private void assertPlanAllowsTaskStart(PprPlan plan) {
        if (!isPlanExecutionAllowed(plan.getStatus())) {
            throw RestException.badRequest("Task can start only after the parent PPR plan is approved");
        }
    }

    private void assertTaskAllowsStart(PprTask task) {
        if (task.getStatus() != PprTaskStatus.APPROVED) {
            throw RestException.badRequest("Only APPROVED PPR tasks can be started");
        }
    }

    private boolean isPlanExecutionAllowed(PlanStatus status) {
        return PLAN_EXECUTION_STATUSES.contains(status);
    }

    private boolean isPlanEditable(PlanStatus status) {
        return PLAN_TASK_EDIT_STATUSES.contains(status);
    }

    private PprTask saveManualTaskWithGeneratedCode(PprPlan plan, PprTaskRequest request) {
        int year = Year.now().getValue();
        String codePrefix = "PPR-TASK-" + year + "-";
        long sequence = taskRepository.maxSequenceByCodePrefix(codePrefix) + 1;

        for (int attempt = 0; attempt < MAX_TASK_CODE_GENERATION_ATTEMPTS; attempt++) {
            String code = formatCode("PPR-TASK", year, sequence + attempt);
            if (taskRepository.existsByCode(code)) {
                continue;
            }

            PprTask task = new PprTask();
            task.setCode(code);
            applyTaskMutableFields(task, plan, request);

            try {
                PprTask saved = taskRepository.save(task);
                plan.getTasks().add(saved);
                return saved;
            } catch (DataIntegrityViolationException ex) {
                if (isTaskCodeConflict(ex)) {
                    continue;
                }
                throw ex;
            }
        }

        throw RestException.conflict("Could not generate unique PPR task code");
    }

    private boolean isTaskCodeConflict(DataIntegrityViolationException ex) {
        Throwable root = ex.getMostSpecificCause();
        String message = root != null ? root.getMessage() : ex.getMessage();
        if (message == null) {
            return false;
        }
        String normalized = message.toLowerCase(Locale.ROOT);
        return normalized.contains("ppr_tasks_code_key")
                || (normalized.contains("ppr_tasks")
                && normalized.contains("duplicate")
                && normalized.contains("code"));
    }

    private PprPlan saveWithGeneratedPlanCode(PprPlanRequest request) {
        int year = Year.now().getValue();
        String codePrefix = "PPR-" + year + "-";
        long sequence = planRepository.maxSequenceByCodePrefix(codePrefix) + 1;

        for (int attempt = 0; attempt < MAX_PLAN_CODE_GENERATION_ATTEMPTS; attempt++) {
            String code = formatCode("PPR", year, sequence + attempt);
            if (planRepository.existsByCodeAndIsDeletedFalse(code)) {
                continue;
            }

            PprPlan plan = new PprPlan();
            plan.setCode(code);
            applyPlanMutableFields(plan, request);

            try {
                return planRepository.saveAndFlush(plan);
            } catch (DataIntegrityViolationException ex) {
                if (isPlanCodeConflict(ex)) {
                    continue;
                }
                throw ex;
            }
        }

        throw RestException.conflict("Could not generate unique PPR plan code");
    }

    private void applyPlanMutableFields(PprPlan plan, PprPlanRequest request) {
        LocalDate fromDate = resolvePlanStartDate(request);
        LocalDate toDate = resolvePlanEndDate(request);
        validatePlanDateRange(fromDate, toDate);

        plan.setName(request.name());
        plan.setStartDate(fromDate);
        plan.setEndDate(toDate);
        plan.setDepartmentId(request.departmentId());
        plan.setNotes(request.notes());
        applyPlanContractFields(plan, request);
        replacePlanTargets(plan, request);
    }

    private void applyPlanContractFields(PprPlan plan, PprPlanRequest request) {
        PprType pprType = request.pprType() != null ? request.pprType() : PprType.PREVENTIVE_MAINTENANCE;
        PprScheduleType scheduleType = request.scheduleType() != null ? request.scheduleType() : PprScheduleType.CALENDAR;
        PprScopeType scopeType = request.scopeType() != null
                ? request.scopeType()
                : (request.departmentId() != null ? PprScopeType.DEPARTMENT : PprScopeType.ENTERPRISE);

        validateSchedule(scheduleType, request.frequency(), request.intervalHours());
        validateScope(pprType, scopeType, request.departmentId());

        plan.setPprType(pprType);
        plan.setScheduleType(scheduleType);
        plan.setFrequency(scheduleType == PprScheduleType.CALENDAR ? request.frequency() : null);
        plan.setIntervalHours(scheduleType == PprScheduleType.OPERATING_HOURS ? request.intervalHours() : null);
        plan.setScopeType(scopeType);
    }

    private void validateSchedule(PprScheduleType scheduleType, PprFrequency frequency, Long intervalHours) {
        if (scheduleType == PprScheduleType.CALENDAR) {
            if (intervalHours != null) {
                throw RestException.badRequest("intervalHours is allowed only for OPERATING_HOURS PPR schedule");
            }
            return;
        }
        if (scheduleType == PprScheduleType.OPERATING_HOURS) {
            if (frequency != null) {
                throw RestException.badRequest("frequency is allowed only for CALENDAR PPR schedule");
            }
            if (intervalHours == null || intervalHours <= 0) {
                throw RestException.badRequest("intervalHours must be positive for OPERATING_HOURS PPR schedule");
            }
            return;
        }
        if (scheduleType == PprScheduleType.ONE_TIME) {
            if (frequency != null) {
                throw RestException.badRequest("frequency is allowed only for CALENDAR PPR schedule");
            }
            if (intervalHours != null) {
                throw RestException.badRequest("intervalHours is allowed only for OPERATING_HOURS PPR schedule");
            }
        }
    }

    private void validateScope(PprType pprType, PprScopeType scopeType, UUID departmentId) {
        if (scopeType == PprScopeType.DEPARTMENT && departmentId == null) {
            throw RestException.badRequest("departmentId is required when PPR scopeType is DEPARTMENT");
        }
        if (pprType == PprType.CAPITAL_REPAIR
                && scopeType != PprScopeType.DEPARTMENT
                && scopeType != PprScopeType.ENTERPRISE) {
            throw RestException.badRequest("CAPITAL_REPAIR PPR scopeType must be DEPARTMENT or ENTERPRISE");
        }
    }

    private void replacePlanTargets(PprPlan plan, PprPlanRequest request) {
        if (request.equipmentIds() == null && request.equipmentTypeIds() == null && request.regulationIds() == null) {
            return;
        }

        List<UUID> equipmentIds = distinctIds(request.equipmentIds());
        List<UUID> equipmentTypeIds = distinctIds(request.equipmentTypeIds());
        List<UUID> regulationIds = distinctIds(request.regulationIds());

        validateNoDuplicateIds("equipmentIds", request.equipmentIds(), equipmentIds);
        validateNoDuplicateIds("equipmentTypeIds", request.equipmentTypeIds(), equipmentTypeIds);
        validateNoDuplicateIds("regulationIds", request.regulationIds(), regulationIds);

        Map<UUID, Equipment> equipmentById = resolveEquipmentTargets(equipmentIds, plan.getDepartmentId());
        validateEquipmentTypeTargets(equipmentTypeIds);
        validateRegulationTargets(regulationIds);

        plan.getTargets().clear();
        for (UUID equipmentId : equipmentIds) {
            PprPlanTarget target = new PprPlanTarget();
            target.setPlan(plan);
            target.setTargetType(PprTargetType.EQUIPMENT);
            target.setEquipmentId(equipmentById.get(equipmentId).getId());
            plan.getTargets().add(target);
        }
        for (UUID equipmentTypeId : equipmentTypeIds) {
            PprPlanTarget target = new PprPlanTarget();
            target.setPlan(plan);
            target.setTargetType(PprTargetType.EQUIPMENT_TYPE);
            target.setEquipmentTypeId(equipmentTypeId);
            plan.getTargets().add(target);
        }
        for (UUID regulationId : regulationIds) {
            PprPlanTarget target = new PprPlanTarget();
            target.setPlan(plan);
            target.setTargetType(PprTargetType.REGULATION);
            target.setRegulationId(regulationId);
            plan.getTargets().add(target);
        }
    }

    private List<UUID> distinctIds(List<UUID> ids) {
        if (ids == null || ids.isEmpty()) {
            return List.of();
        }
        return ids.stream()
                .filter(Objects::nonNull)
                .collect(Collectors.collectingAndThen(
                        Collectors.toCollection(LinkedHashSet::new),
                        List::copyOf
                ));
    }

    private void validateNoDuplicateIds(String fieldName, List<UUID> requestedIds, List<UUID> distinctIds) {
        if (requestedIds == null || requestedIds.isEmpty()) {
            return;
        }
        long nonNullCount = requestedIds.stream().filter(Objects::nonNull).count();
        if (nonNullCount != requestedIds.size()) {
            throw RestException.badRequest(fieldName + " must not contain null values");
        }
        if (distinctIds.size() != requestedIds.size()) {
            throw RestException.badRequest(fieldName + " must not contain duplicate values");
        }
    }

    private Map<UUID, Equipment> resolveEquipmentTargets(List<UUID> equipmentIds, UUID departmentId) {
        if (equipmentIds.isEmpty()) {
            return Map.of();
        }
        List<Equipment> equipment = equipmentRepository.findAllByIdInAndIsDeletedFalse(equipmentIds);
        Map<UUID, Equipment> equipmentById = equipment.stream()
                .collect(Collectors.toMap(Equipment::getId, item -> item));
        for (UUID equipmentId : equipmentIds) {
            Equipment item = equipmentById.get(equipmentId);
            if (item == null) {
                throw RestException.notFound("Equipment not found: " + equipmentId);
            }
            if (departmentId != null && !departmentId.equals(item.getDepartmentId())) {
                throw RestException.badRequest("PPR equipment target belongs to a different department: " + equipmentId);
            }
        }
        return equipmentById;
    }

    private void validateEquipmentTypeTargets(List<UUID> equipmentTypeIds) {
        if (equipmentTypeIds.isEmpty()) {
            return;
        }
        Set<UUID> existingIds = equipmentTypeRepository.findAllByIdInAndIsDeletedFalse(equipmentTypeIds).stream()
                .map(type -> type.getId())
                .collect(Collectors.toSet());
        for (UUID equipmentTypeId : equipmentTypeIds) {
            if (!existingIds.contains(equipmentTypeId)) {
                throw RestException.notFound("Equipment type not found: " + equipmentTypeId);
            }
        }
    }

    private void validateRegulationTargets(List<UUID> regulationIds) {
        if (regulationIds.isEmpty()) {
            return;
        }
        Set<UUID> existingIds = maintenanceRegulationRepository.findAllByIdInAndIsDeletedFalse(regulationIds).stream()
                .map(MaintenanceRegulation::getId)
                .collect(Collectors.toSet());
        for (UUID regulationId : regulationIds) {
            if (!existingIds.contains(regulationId)) {
                throw RestException.notFound("Maintenance regulation not found: " + regulationId);
            }
        }
    }

    private LocalDate resolvePlanStartDate(PprPlanRequest request) {
        return request.fromDate();
    }

    private LocalDate resolvePlanEndDate(PprPlanRequest request) {
        return request.toDate();
    }

    private void validatePlanDateRange(LocalDate fromDate, LocalDate toDate) {
        if (toDate.isBefore(fromDate)) {
            throw RestException.badRequest("PPR plan toDate must not be before fromDate");
        }
    }

    private void validateDateFilterParts(Integer year, Integer month, Integer day) {
        if (year != null && year < 1) {
            throw RestException.badRequest("PPR plan year filter must be positive");
        }
        if (month != null && (month < 1 || month > 12)) {
            throw RestException.badRequest("PPR plan month filter must be between 1 and 12");
        }
        if (day != null && (day < 1 || day > 31)) {
            throw RestException.badRequest("PPR plan day filter must be between 1 and 31");
        }
    }

    private boolean isPlanCodeConflict(DataIntegrityViolationException ex) {
        Throwable root = ex.getMostSpecificCause();
        String message = root != null ? root.getMessage() : ex.getMessage();
        if (message == null) {
            return false;
        }
        String normalized = message.toLowerCase(Locale.ROOT);
        return normalized.contains("ppr_plans_code_key")
                || (normalized.contains("ppr_plans")
                && normalized.contains("duplicate")
                && normalized.contains("code"));
    }

    private String formatCode(String prefix, int year, long sequence) {
        return "%s-%d-%04d".formatted(prefix, year, sequence);
    }

    private long safe(Long value) {
        return value == null ? 0L : value;
    }

}
