package com.toir.util;

import com.toir.exception.RestException;

import java.time.Year;
import java.util.function.LongSupplier;
import java.util.function.Predicate;

public final class CodeGenerationUtils {
    public static final int DEFAULT_MAX_ATTEMPTS = 50;
    public static final String CLIENT_CODE_REJECT_MESSAGE =
            "code is generated by backend and must not be provided";

    private CodeGenerationUtils() {
    }

    public static void rejectClientProvidedCode(String code) {
        if (code != null && !code.isBlank()) {
            throw RestException.badRequest(CLIENT_CODE_REJECT_MESSAGE);
        }
    }

    public static String nextYearSequenceCode(String prefix,
                                              LongSupplier maxSequenceSupplier,
                                              Predicate<String> exists) {
        int year = Year.now().getValue();
        String codePrefix = prefix + "-" + year + "-";
        long sequence = maxSequenceSupplier.getAsLong() + 1;
        for (int attempt = 0; attempt < DEFAULT_MAX_ATTEMPTS; attempt++) {
            String code = "%s%04d".formatted(codePrefix, sequence + attempt);
            if (!exists.test(code)) {
                return code;
            }
        }
        throw RestException.conflict("Could not generate unique " + prefix + " code");
    }
}
