server:
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${TOIR_DB_URL}
    username: ${TOIR_DB_USERNAME}
    password: ${TOIR_DB_PASSWORD}
    driver-class-name: ${TOIR_DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: false
    show-sql: false
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB

springdoc:
  cache:
    disabled: true
  api-docs:
    path: /api/v1/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  security:
    jwt:
      secret: ${TOIR_JWT_SECRET}
      expiration-minutes: ${TOIR_JWT_EXPIRATION_MINUTES:720}
      issuer: ${TOIR_JWT_ISSUER:toir-backend}
  jackson:
    instant-default-zone: Asia/Tashkent
  cors:
    allowed-origin-patterns:
      - http://localhost:3000
      - http://localhost:8080
      - http://localhost:5173
      - https://toir.tenzorsoft.uz
      - https://api-toir.tenzorsoft.uz
      - https://api-mes.tenzorsoft.uz
  files:
    storage-path: ./uploads
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://api-toir.tenzorsoft.uz
  bootstrap:
    create-default-admin: ${TOIR_CREATE_DEFAULT_ADMIN:false}
    admin-username: ${TOIR_ADMIN_USERNAME}
    admin-password: ${TOIR_ADMIN_PASSWORD}
    admin-email: ${TOIR_ADMIN_EMAIL}
    admin-full-name: ${TOIR_ADMIN_FULL_NAME:System Administrator}

logging:
  level:
    root: INFO
    com.toir: INFO
