spring:
  application:
    name: toir-backend
  profiles:
    default: prod
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true

springdoc:
  cache:
    disabled: true

app:
  features:
    manual-attributes:
      write-enabled: ${APP_FEATURES_MANUAL_ATTRIBUTES_WRITE_ENABLED:false}
  firebase:
    enabled: ${APP_FIREBASE_ENABLED:false}
    project-id: ${APP_FIREBASE_PROJECT_ID:}
    service-account-file: ${APP_FIREBASE_SERVICE_ACCOUNT_FILE:}
    service-account-json: ${APP_FIREBASE_SERVICE_ACCOUNT_JSON:}
    service-account-base64: ${APP_FIREBASE_SERVICE_ACCOUNT_BASE64:}

minio:
  endpoint: https://s3.tenzorsoft.uz
  access-key: s3_tenzorsoft_minio_user
  secret-key: b7Qbuf8DpyAdZmlok2X3PSlD6n9jilSuhctZRd2b
  bucket-name: s3-toir
  public-url: https://s3.tenzorsoft.uz
