package com.toir.service.maintanance;

import com.toir.dto.maintenancetemplate.MaintenanceOperationDto;
import com.toir.dto.maintenancetemplate.MaintenanceTemplateDto;
import com.toir.dto.maintenancetemplate.MaintenanceTemplateRequest;
import com.toir.dto.maintenancetemplate.MaintenanceTemplateStatsResponse;
import com.toir.entity.maintenance.MaintenanceAction;
import com.toir.entity.maintenance.MaintenanceOperation;
import com.toir.entity.maintenance.MaintenanceTemplate;
import com.toir.enums.AuditAction;
import com.toir.enums.AuditModule;
import com.toir.enums.MaintenanceKind;
import com.toir.exception.RestException;
import com.toir.entity.equipment.EquipmentType;
import com.toir.repository.equipment.EquipmentTypeRepository;
import com.toir.repository.maintenance.MaintenanceOperationRepository;
import com.toir.repository.maintenance.MaintenanceActionRepository;
import com.toir.repository.maintenance.MaintenanceTemplateRepository;
import com.toir.repository.maintenance.MaintenanceTemplateStatsProjection;
import com.toir.service.SparePartService;
import com.toir.util.AuditBuilderService;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Year;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class MaintenanceTemplateService {

    private final MaintenanceTemplateRepository repository;
    private final MaintenanceOperationRepository operationRepository;
    private final MaintenanceActionRepository actionRepository;
    private final EquipmentTypeRepository equipmentTypeRepository;
    private final SparePartService sparePartService;
    private final AuditBuilderService auditBuilderService;
    private static final int MAX_CODE_GENERATION_ATTEMPTS = 50;
    private static final String CLIENT_CODE_REJECT_MESSAGE =
            "code is generated by backend and must not be provided";


    @Transactional(readOnly = true)
    public MaintenanceTemplateStatsResponse getStats(String search, MaintenanceKind type) {
        String searchPattern = search != null && !search.isBlank() ? sparePartService.toSearchPattern(search) : null;
        String typeStr = type != null ? type.name() : null;
        MaintenanceTemplateStatsProjection stats = repository.getTemplateStats(searchPattern, typeStr);
        if (stats == null) {
            return new MaintenanceTemplateStatsResponse(0, 0, 0, 0.0f);
        }
        return new MaintenanceTemplateStatsResponse(
                stats.getTotalTemplates() != null ? stats.getTotalTemplates() : 0L,
                stats.getWithOperations() != null ? stats.getWithOperations() : 0L,
                stats.getTotalOperations() != null ? stats.getTotalOperations() : 0L,
                stats.getAvgOperationsPerTemplate() != null ? stats.getAvgOperationsPerTemplate() : 0.0f
        );
    }

    @Transactional(readOnly = true)
    public List<MaintenanceTemplateDto> findAll(String search, MaintenanceKind type) {
        return toDtoList(repository.findAllByIsDeletedFalseAndMaintenanceKindAndSearch(sparePartService.toSearchPattern(search), type));
    }

    @Transactional(readOnly = true)
    public MaintenanceTemplateDto findById(UUID id) {
        return toDto(getOrThrow(id));
    }

    @Transactional
    public MaintenanceTemplateDto create(MaintenanceTemplateRequest r) {
        validateClientProvidedCode(r.code());
        MaintenanceTemplate saved = saveWithGeneratedCode(r);

        auditBuilderService.log(
                "maintenance_template",
                saved.getId().toString(),
                AuditAction.CREATE,
                AuditModule.MAINTENANCE_TEMPLATE,
                "Шаблон обслуживания создан",
                null,
                saved);

        return toDto(saved);
    }

    @Transactional
    public MaintenanceTemplateDto update(UUID id, MaintenanceTemplateRequest r) {
        validateClientProvidedCode(r.code());
        MaintenanceTemplate t = getOrThrow(id);
        applyMutableFields(t, r);

        MaintenanceTemplate saved = repository.save(t);

        auditBuilderService.log(
                "maintenance_template",
                saved.getId().toString(),
                AuditAction.UPDATE,
                AuditModule.MAINTENANCE_TEMPLATE,
                "Шаблон обслуживания обновлен",
                t,
                saved);

        return toDto(t);
    }

    @Transactional
    public void delete(UUID id) { var entity = getOrThrow(id);
        entity.setDeleted(true);
        MaintenanceTemplate saved = repository.save(entity);

        auditBuilderService.log(
                "maintenance_template",
                saved.getId().toString(),
                AuditAction.DELETE,
                AuditModule.MAINTENANCE_TEMPLATE,
                "Шаблон обслуживания удален",
                saved,
                null);

    }

    @Transactional
    public MaintenanceOperationDto addOperation(UUID templateId, MaintenanceOperationDto r) {
        MaintenanceTemplate t = getOrThrow(templateId);
        MaintenanceAction action = null;
        if (r.actionId() != null) {
            action = actionRepository.findByIdAndIsDeletedFalse(r.actionId())
                    .orElseThrow(() -> RestException.notFound("Maintenance action not found: " + r.actionId()));
            if (!action.isActive()) {
                throw RestException.badRequest("Maintenance action is inactive: " + r.actionId());
            }
        }
        MaintenanceOperation op = new MaintenanceOperation();
        op.setTemplate(t);
        op.setAction(action);
        op.setSequence(r.sequence());
        String operationName = firstText(r.name(), action != null ? action.getName() : null);
        if (operationName == null) {
            throw RestException.badRequest("Maintenance operation name is required");
        }
        op.setName(operationName);
        op.setDescription(r.description());
        op.setDurationHours(r.durationHours() > 0 ? r.durationHours()
                : action != null && action.getDefaultDurationHours() != null
                ? action.getDefaultDurationHours()
                : 0);
        op.setRequiredSkill(firstText(r.requiredSkill(), action != null ? action.getRequiredSkill() : null));
        op.setSafetyNotes(firstText(r.safetyNotes(), action != null ? action.getSafetyNotes() : null));
        op.setToolsRequired(firstText(r.toolsRequired(), action != null ? action.getToolsRequired() : null));
        op.setSparePartsRequired(firstText(r.sparePartsRequired(), action != null ? action.getSparePartsRequired() : null));
        op.setConsumablesRequired(firstText(r.consumablesRequired(), action != null ? action.getConsumablesRequired() : null));
        op.setControlParameter(r.controlParameter());
        op.setControlUnit(r.controlUnit());
        op.setControlMin(r.controlMin());
        op.setControlMax(r.controlMax());
        op.setInstructionUrl(r.instructionUrl());
        t.getOperations().add(op);
        return MaintenanceOperationDto.from(operationRepository.save(op));
    }

    @Transactional
    public void removeOperation(UUID operationId) {
        operationRepository.findByIdAndIsDeletedFalse(operationId).ifPresent(entity -> {
            entity.setDeleted(true);
            operationRepository.save(entity);
        });
    }

    private MaintenanceTemplate getOrThrow(UUID id) {
        return repository.findByIdAndIsDeletedFalse(id)
                .orElseThrow(() -> RestException.notFound("Template not found: " + id));
    }

    private String firstText(String preferred, String fallback) {
        if (preferred != null && !preferred.isBlank()) {
            return preferred.trim();
        }
        return fallback != null && !fallback.isBlank() ? fallback.trim() : null;
    }

    private void applyMutableFields(MaintenanceTemplate t, MaintenanceTemplateRequest r) {
        t.setName(r.name());
        t.setDescription(r.description());
        t.setEquipmentTypeId(r.equipmentTypeId());
        t.setMaintenanceKind(r.maintenanceKind());
        t.setNormativeLaborHours(r.normativeLaborHours());
        if (r.active() != null) t.setActive(r.active());
    }

    private void validateClientProvidedCode(String code) {
        if (code != null && !code.isBlank()) {
            throw RestException.badRequest(CLIENT_CODE_REJECT_MESSAGE);
        }
    }

    private MaintenanceTemplate saveWithGeneratedCode(MaintenanceTemplateRequest request) {
        int year = Year.now().getValue();
        String codePrefix = "MT-" + year + "-";
        long sequence = repository.maxSequenceByCodePrefix(codePrefix) + 1;

        for (int attempt = 0; attempt < MAX_CODE_GENERATION_ATTEMPTS; attempt++) {
            String code = formatCode("MT", year, sequence + attempt);
            if (repository.existsByCode(code)) {
                continue;
            }

            MaintenanceTemplate entity = new MaintenanceTemplate();
            entity.setCode(code);
            applyMutableFields(entity, request);

            try {
                return repository.save(entity);
            } catch (DataIntegrityViolationException ex) {
                if (isCodeConflict(ex)) {
                    continue;
                }
                throw ex;
            }
        }

        throw RestException.conflict("Could not generate unique maintenance template code");
    }

    private String formatCode(String prefix, int year, long sequence) {
        return "%s-%d-%04d".formatted(prefix, year, sequence);
    }

    private boolean isCodeConflict(DataIntegrityViolationException ex) {
        Throwable root = ex.getMostSpecificCause();
        String message = root != null ? root.getMessage() : ex.getMessage();
        if (message == null) {
            return false;
        }
        String normalized = message.toLowerCase(Locale.ROOT);
        return normalized.contains("maintenance_templates_code_key")
                || (normalized.contains("maintenance_templates")
                && normalized.contains("duplicate")
                && normalized.contains("code"));
    }

    private MaintenanceTemplateDto toDto(MaintenanceTemplate t) {
        if (t == null) return null;
        if (t.getEquipmentTypeId() == null) {
            return MaintenanceTemplateDto.from(t, null);
        }
        String equipmentTypeName = equipmentTypeRepository.findByIdAndIsDeletedFalse(t.getEquipmentTypeId())
                .map(EquipmentType::getName)
                .orElse(null);
        return MaintenanceTemplateDto.from(t, equipmentTypeName);
    }

    private List<MaintenanceTemplateDto> toDtoList(List<MaintenanceTemplate> templates) {
        if (templates == null || templates.isEmpty()) return List.of();
        Set<UUID> eqTypeIds = templates.stream()
                .map(MaintenanceTemplate::getEquipmentTypeId)
                .filter(Objects::nonNull)
                .collect(Collectors.toSet());
        Map<UUID, String> eqTypeNames = equipmentTypeRepository.findAllByIdInAndIsDeletedFalse(eqTypeIds).stream()
                .collect(Collectors.toMap(EquipmentType::getId, EquipmentType::getName));
        return templates.stream()
                .map(t -> MaintenanceTemplateDto.from(t, eqTypeNames.getOrDefault(t.getEquipmentTypeId(), null)))
                .toList();
    }
}
