package com.toir.service.maintanance;

import com.toir.dto.maintenanceregulation.MaintenanceRegulationDto;
import com.toir.dto.maintenanceregulation.MaintenanceRegulationRequest;
import com.toir.entity.maintenance.MaintenanceRegulation;
import com.toir.enums.AuditAction;
import com.toir.enums.AuditModule;
import com.toir.exception.RestException;
import com.toir.repository.maintenance.MaintenanceRegulationRepository;
import com.toir.util.AuditBuilderService;
import com.toir.util.PaginationUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Year;
import java.util.List;
import java.util.Locale;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class MaintenanceRegulationService {

    private final MaintenanceRegulationRepository repository;
    private final AuditBuilderService auditBuilderService;
    private static final int MAX_CODE_GENERATION_ATTEMPTS = 50;
    private static final String CLIENT_CODE_REJECT_MESSAGE =
            "code is generated by backend and must not be provided";


    @Transactional(readOnly = true)
    public List<MaintenanceRegulationDto> findAll() {
        return repository.findAllByIsDeletedFalseOrderByUpdatedAtDesc().stream().map(MaintenanceRegulationDto::from).toList();
    }

    @Transactional(readOnly = true)
    public Page<MaintenanceRegulationDto> search(int page, int pageSize, String search) {
        var pageable = PaginationUtils.pageRequest(page, pageSize);
        return repository.searchPaginated(
                search,
                pageable
        ).map(MaintenanceRegulationDto::from);
    }

    @Transactional(readOnly = true)
    public MaintenanceRegulationDto findById(UUID id) {
        return MaintenanceRegulationDto.from(getOrThrow(id));
    }


    @Transactional(readOnly = true)
    public List<MaintenanceRegulation> findActiveByEquipmentType(UUID equipmentTypeId) {
        return repository.findAllByEquipmentTypeIdAndActiveTrueAndIsDeletedFalse(equipmentTypeId);
    }

    @Transactional
    public MaintenanceRegulationDto create(MaintenanceRegulationRequest request) {
        validateClientProvidedCode(request.code());
        MaintenanceRegulation saved = saveWithGeneratedCode(request);

        auditBuilderService.log(
                "maintenance_regulation",
                saved.getId().toString(),
                AuditAction.CREATE,
                AuditModule.MAINTENANCE_REGULATION,
                "Регламент обслуживания создан",
                null,
                saved);

        return MaintenanceRegulationDto.from(saved);
    }

    @Transactional
    public MaintenanceRegulationDto update(UUID id, MaintenanceRegulationRequest request) {
        validateClientProvidedCode(request.code());
        MaintenanceRegulation entity = getOrThrow(id);
        applyMutableFields(entity, request);

        MaintenanceRegulation save = repository.save(entity);

        auditBuilderService.log(
                "maintenance_regulation",
                id != null ? id.toString() : null,
                AuditAction.UPDATE,
                AuditModule.MAINTENANCE_REGULATION,
                "Регламент обслуживания обновлен",
                entity,
                save);

        return MaintenanceRegulationDto.from(entity);
    }

    @Transactional
    public void delete(UUID id) {
        var entity = getOrThrow(id);
        entity.setDeleted(true);
        MaintenanceRegulation saved = repository.save(entity);

        auditBuilderService.log(
                "maintenance_regulation",
                saved.getId().toString(),
                AuditAction.DELETE,
                AuditModule.MAINTENANCE_REGULATION,
                "Регламент обслуживания удален",
                saved,
                null);

    }

    private MaintenanceRegulation getOrThrow(UUID id) {
        return repository.findByIdAndIsDeletedFalse(id)
                .orElseThrow(() -> RestException.notFound("Maintenance regulation not found: " + id));
    }

    private void applyMutableFields(MaintenanceRegulation entity, MaintenanceRegulationRequest request) {
        entity.setName(request.name());
        entity.setDescription(request.description());
        entity.setEquipmentTypeId(request.equipmentTypeId());
        entity.setMaintenanceKind(request.maintenanceKind());
        entity.setNormativeLaborHours(request.normativeLaborHours());
        if (request.active() != null) entity.setActive(request.active());
        entity.setPeriodicityUnit(request.periodicityUnit());
        entity.setPeriodicityValue(request.periodicityValue());
        entity.setToleranceDays(request.toleranceDays());
        entity.setRequiresShutdown(request.requiresShutdown());
        entity.setTriggerMeterType(request.triggerMeterType());
        entity.setTriggerMeterInterval(request.triggerMeterInterval());
    }

    private void validateClientProvidedCode(String code) {
        if (code != null && !code.isBlank()) {
            throw RestException.badRequest(CLIENT_CODE_REJECT_MESSAGE);
        }
    }

    private MaintenanceRegulation saveWithGeneratedCode(MaintenanceRegulationRequest request) {
        int year = Year.now().getValue();
        String codePrefix = "MR-" + year + "-";
        long sequence = repository.maxSequenceByCodePrefix(codePrefix) + 1;

        for (int attempt = 0; attempt < MAX_CODE_GENERATION_ATTEMPTS; attempt++) {
            String code = formatCode("MR", year, sequence + attempt);
            if (repository.existsByCode(code)) {
                continue;
            }

            MaintenanceRegulation entity = new MaintenanceRegulation();
            entity.setCode(code);
            applyMutableFields(entity, request);

            try {
                return repository.save(entity);
            } catch (DataIntegrityViolationException ex) {
                if (isCodeConflict(ex)) {
                    continue;
                }
                throw ex;
            }
        }

        throw RestException.conflict("Could not generate unique maintenance regulation code");
    }

    private String formatCode(String prefix, int year, long sequence) {
        return "%s-%d-%04d".formatted(prefix, year, sequence);
    }

    private boolean isCodeConflict(DataIntegrityViolationException ex) {
        Throwable root = ex.getMostSpecificCause();
        String message = root != null ? root.getMessage() : ex.getMessage();
        if (message == null) {
            return false;
        }
        String normalized = message.toLowerCase(Locale.ROOT);
        return normalized.contains("maintenance_regulations_code_key")
                || (normalized.contains("maintenance_regulations")
                && normalized.contains("duplicate")
                && normalized.contains("code"));
    }
}
