package com.toir.service.maintanance;

import com.toir.dto.maintenanceregulation.MaintenanceRegulationDto;
import com.toir.dto.maintenanceregulation.MaintenanceRegulationAttributeConditionDto;
import com.toir.dto.maintenanceregulation.MaintenanceRegulationAttributeConditionRequest;
import com.toir.dto.maintenanceregulation.MaintenanceRegulationRequest;
import com.toir.entity.maintenance.MaintenanceRegulationAttributeCondition;
import com.toir.entity.maintenance.MaintenanceRegulation;
import com.toir.enums.AuditAction;
import com.toir.enums.AuditModule;
import com.toir.enums.MaintenanceRegulationConditionOperator;
import com.toir.exception.RestException;
import com.toir.entity.equipment.EquipmentType;
import com.toir.repository.equipment.EquipmentAttributeDefinitionRepository;
import com.toir.repository.equipment.EquipmentTypeRepository;
import com.toir.repository.maintenance.MaintenanceRegulationAttributeConditionRepository;
import com.toir.repository.maintenance.MaintenanceRegulationRepository;
import com.toir.util.AuditBuilderService;
import com.toir.util.PaginationUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Year;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class MaintenanceRegulationService {

    private final MaintenanceRegulationRepository repository;
    private final MaintenanceRegulationAttributeConditionRepository conditionRepository;
    private final EquipmentTypeRepository equipmentTypeRepository;
    private final EquipmentAttributeDefinitionRepository attributeDefinitionRepository;
    private final AuditBuilderService auditBuilderService;
    private static final int MAX_CODE_GENERATION_ATTEMPTS = 50;
    private static final String CLIENT_CODE_REJECT_MESSAGE =
            "code is generated by backend and must not be provided";


    @Transactional(readOnly = true)
    public List<MaintenanceRegulationDto> findAll() {
        return toDtoList(repository.findAllByIsDeletedFalseOrderByUpdatedAtDesc());
    }

    @Transactional(readOnly = true)
    public Page<MaintenanceRegulationDto> search(int page, int pageSize, String search) {
        var pageable = PaginationUtils.pageRequest(page, pageSize);
        return repository.searchPaginated(
                search,
                pageable
        ).map(this::toDto);
    }

    @Transactional(readOnly = true)
    public MaintenanceRegulationDto findById(UUID id) {
        return toDto(getOrThrow(id));
    }


    @Transactional(readOnly = true)
    public List<MaintenanceRegulation> findActiveByEquipmentType(UUID equipmentTypeId) {
        return repository.findAllByEquipmentTypeIdAndActiveTrueAndIsDeletedFalse(equipmentTypeId);
    }

    @Transactional
    public MaintenanceRegulationDto create(MaintenanceRegulationRequest request) {
        validateClientProvidedCode(request.code());
        MaintenanceRegulation saved = saveWithGeneratedCode(request);
        replaceConditions(saved.getId(), saved.getEquipmentTypeId(), request.attributeConditions());

        auditBuilderService.log(
                "maintenance_regulation",
                saved.getId().toString(),
                AuditAction.CREATE,
                AuditModule.MAINTENANCE_REGULATION,
                "Регламент обслуживания создан",
                null,
                saved);

        return toDto(saved);
    }

    @Transactional
    public MaintenanceRegulationDto update(UUID id, MaintenanceRegulationRequest request) {
        validateClientProvidedCode(request.code());
        MaintenanceRegulation entity = getOrThrow(id);
        applyMutableFields(entity, request);

        MaintenanceRegulation save = repository.save(entity);
        replaceConditions(save.getId(), save.getEquipmentTypeId(), request.attributeConditions());

        auditBuilderService.log(
                "maintenance_regulation",
                id != null ? id.toString() : null,
                AuditAction.UPDATE,
                AuditModule.MAINTENANCE_REGULATION,
                "Регламент обслуживания обновлен",
                entity,
                save);

        return toDto(entity);
    }

    @Transactional
    public void delete(UUID id) {
        var entity = getOrThrow(id);
        entity.setDeleted(true);
        MaintenanceRegulation saved = repository.save(entity);

        auditBuilderService.log(
                "maintenance_regulation",
                saved.getId().toString(),
                AuditAction.DELETE,
                AuditModule.MAINTENANCE_REGULATION,
                "Регламент обслуживания удален",
                saved,
                null);

    }

    private MaintenanceRegulation getOrThrow(UUID id) {
        return repository.findByIdAndIsDeletedFalse(id)
                .orElseThrow(() -> RestException.notFound("Maintenance regulation not found: " + id));
    }

    private void applyMutableFields(MaintenanceRegulation entity, MaintenanceRegulationRequest request) {
        entity.setName(request.name());
        entity.setDescription(request.description());
        entity.setEquipmentTypeId(request.equipmentTypeId());
        entity.setMaintenanceKind(request.maintenanceKind());
        entity.setNormativeLaborHours(request.normativeLaborHours());
        if (request.active() != null) entity.setActive(request.active());
        entity.setPeriodicityUnit(request.periodicityUnit());
        entity.setPeriodicityValue(request.periodicityValue());
        entity.setToleranceDays(request.toleranceDays());
        entity.setRequiresShutdown(request.requiresShutdown());
        entity.setTriggerMeterType(request.triggerMeterType());
        entity.setTriggerMeterInterval(request.triggerMeterInterval());
    }

    private void replaceConditions(UUID regulationId,
                                   UUID equipmentTypeId,
                                   List<MaintenanceRegulationAttributeConditionRequest> requests) {
        if (requests == null) {
            return;
        }
        if (conditionRepository == null) {
            return;
        }
        List<MaintenanceRegulationAttributeCondition> existing =
                conditionRepository.findAllByRegulationIdAndIsDeletedFalse(regulationId);
        for (MaintenanceRegulationAttributeCondition condition : existing) {
            condition.setDeleted(true);
        }
        if (!existing.isEmpty()) {
            conditionRepository.saveAll(existing);
        }

        List<MaintenanceRegulationAttributeCondition> toSave = requests.stream()
                .map(request -> toCondition(regulationId, equipmentTypeId, request))
                .toList();
        if (!toSave.isEmpty()) {
            conditionRepository.saveAll(toSave);
        }
    }

    private MaintenanceRegulationAttributeCondition toCondition(UUID regulationId,
                                                               UUID equipmentTypeId,
                                                               MaintenanceRegulationAttributeConditionRequest request) {
        if (request == null) {
            throw RestException.badRequest("Attribute condition is required");
        }
        String key = normalizeAttributeKey(request.attributeKey());
        if (!attributeDefinitionRepository.existsActiveByEquipmentTypeIdAndKey(equipmentTypeId, key)) {
            throw RestException.badRequest("Unknown equipment attribute key for regulation type: " + key);
        }
        validateConditionValue(request);

        MaintenanceRegulationAttributeCondition condition = new MaintenanceRegulationAttributeCondition();
        condition.setRegulationId(regulationId);
        condition.setAttributeKey(key);
        condition.setOperator(request.operator());
        condition.setValueText(request.valueText());
        condition.setValueNumber(request.valueNumber());
        condition.setValueDate(request.valueDate());
        condition.setValueBoolean(request.valueBoolean());
        condition.setValueOption(request.valueOption());
        return condition;
    }

    private void validateConditionValue(MaintenanceRegulationAttributeConditionRequest request) {
        if (request.operator() == null) {
            throw RestException.badRequest("Condition operator is required");
        }
        if (request.operator() == MaintenanceRegulationConditionOperator.EXISTS
                || request.operator() == MaintenanceRegulationConditionOperator.NOT_EXISTS) {
            return;
        }
        boolean hasValue = request.valueText() != null
                || request.valueNumber() != null
                || request.valueDate() != null
                || request.valueBoolean() != null
                || request.valueOption() != null;
        if (!hasValue) {
            throw RestException.badRequest("Condition value is required");
        }
    }

    private String normalizeAttributeKey(String key) {
        if (key == null || key.isBlank()) {
            throw RestException.badRequest("Attribute condition key is required");
        }
        return key.trim().toLowerCase(Locale.ROOT);
    }

    private void validateClientProvidedCode(String code) {
        if (code != null && !code.isBlank()) {
            throw RestException.badRequest(CLIENT_CODE_REJECT_MESSAGE);
        }
    }

    private MaintenanceRegulation saveWithGeneratedCode(MaintenanceRegulationRequest request) {
        int year = Year.now().getValue();
        String codePrefix = "MR-" + year + "-";
        long sequence = repository.maxSequenceByCodePrefix(codePrefix) + 1;

        for (int attempt = 0; attempt < MAX_CODE_GENERATION_ATTEMPTS; attempt++) {
            String code = formatCode("MR", year, sequence + attempt);
            if (repository.existsByCode(code)) {
                continue;
            }

            MaintenanceRegulation entity = new MaintenanceRegulation();
            entity.setCode(code);
            applyMutableFields(entity, request);

            try {
                return repository.save(entity);
            } catch (DataIntegrityViolationException ex) {
                if (isCodeConflict(ex)) {
                    continue;
                }
                throw ex;
            }
        }

        throw RestException.conflict("Could not generate unique maintenance regulation code");
    }

    private String formatCode(String prefix, int year, long sequence) {
        return "%s-%d-%04d".formatted(prefix, year, sequence);
    }

    private boolean isCodeConflict(DataIntegrityViolationException ex) {
        Throwable root = ex.getMostSpecificCause();
        String message = root != null ? root.getMessage() : ex.getMessage();
        if (message == null) {
            return false;
        }
        String normalized = message.toLowerCase(Locale.ROOT);
        return normalized.contains("maintenance_regulations_code_key")
                || (normalized.contains("maintenance_regulations")
                && normalized.contains("duplicate")
                && normalized.contains("code"));
    }

    private MaintenanceRegulationDto toDto(MaintenanceRegulation r) {
        if (r == null) return null;
        List<MaintenanceRegulationAttributeConditionDto> conditions = conditionDtos(r.getId());
        if (r.getEquipmentTypeId() == null) {
            return MaintenanceRegulationDto.from(r, null, conditions);
        }
        String equipmentTypeName = equipmentTypeRepository.findByIdAndIsDeletedFalse(r.getEquipmentTypeId())
                .map(EquipmentType::getName)
                .orElse(null);
        return MaintenanceRegulationDto.from(r, equipmentTypeName, conditions);
    }

    private List<MaintenanceRegulationDto> toDtoList(List<MaintenanceRegulation> regulations) {
        if (regulations == null || regulations.isEmpty()) return List.of();
        Set<UUID> eqTypeIds = regulations.stream()
                .map(MaintenanceRegulation::getEquipmentTypeId)
                .filter(Objects::nonNull)
                .collect(Collectors.toSet());
        Map<UUID, String> eqTypeNames = equipmentTypeRepository.findAllByIdInAndIsDeletedFalse(eqTypeIds).stream()
                .collect(Collectors.toMap(EquipmentType::getId, EquipmentType::getName));
        Set<UUID> regulationIds = regulations.stream().map(MaintenanceRegulation::getId).collect(Collectors.toSet());
        Map<UUID, List<MaintenanceRegulationAttributeConditionDto>> conditionsByRegulationId =
                conditionDtosByRegulationId(regulationIds);
        return regulations.stream()
                .map(r -> MaintenanceRegulationDto.from(
                        r,
                        eqTypeNames.getOrDefault(r.getEquipmentTypeId(), null),
                        conditionsByRegulationId.getOrDefault(r.getId(), List.of())
                ))
                .toList();
    }

    private List<MaintenanceRegulationAttributeConditionDto> conditionDtos(UUID regulationId) {
        if (conditionRepository == null) {
            return List.of();
        }
        List<MaintenanceRegulationAttributeCondition> conditions =
                conditionRepository.findAllByRegulationIdAndIsDeletedFalse(regulationId);
        if (conditions == null || conditions.isEmpty()) {
            return List.of();
        }
        return conditions.stream()
                .map(MaintenanceRegulationAttributeConditionDto::from)
                .toList();
    }

    private Map<UUID, List<MaintenanceRegulationAttributeConditionDto>> conditionDtosByRegulationId(Set<UUID> regulationIds) {
        if (conditionRepository == null || regulationIds.isEmpty()) {
            return Map.of();
        }
        List<MaintenanceRegulationAttributeCondition> conditions =
                conditionRepository.findAllByRegulationIdInAndIsDeletedFalse(regulationIds);
        if (conditions == null || conditions.isEmpty()) {
            return Map.of();
        }
        return conditions.stream()
                .collect(Collectors.groupingBy(
                        MaintenanceRegulationAttributeCondition::getRegulationId,
                        Collectors.mapping(MaintenanceRegulationAttributeConditionDto::from, Collectors.toList())
                ));
    }
}
