package com.toir.service.maintanance;

import com.toir.dto.maintenanceregulation.MaintenanceRegulationDto;
import com.toir.dto.maintenanceregulation.EquipmentWithRegulationsDto;
import com.toir.dto.maintenanceregulation.MaintenanceRegulationAttributeConditionDto;
import com.toir.dto.maintenanceregulation.MaintenanceRegulationAttributeConditionRequest;
import com.toir.dto.maintenanceregulation.MaintenanceRegulationRequest;
import com.toir.dto.maintenanceregulation.MaintenanceRegulationSummaryDto;
import com.toir.entity.equipment.Equipment;
import com.toir.entity.maintenance.MaintenanceRegulationAttributeCondition;
import com.toir.entity.maintenance.MaintenanceRegulation;
import com.toir.entity.maintenance.MaintenanceOperation;
import com.toir.entity.maintenance.MaintenanceTemplate;
import com.toir.enums.AuditAction;
import com.toir.enums.AuditModule;
import com.toir.enums.MaintenanceRecalculationPolicy;
import com.toir.enums.MaintenanceRegulationConditionOperator;
import com.toir.enums.MaintenanceTriggerPolicy;
import com.toir.exception.RestException;
import com.toir.entity.equipment.EquipmentType;
import com.toir.repository.equipment.EquipmentRepository;
import com.toir.repository.equipment.EquipmentAttributeDefinitionRepository;
import com.toir.repository.equipment.EquipmentTypeRepository;
import com.toir.repository.maintenance.MaintenanceOperationRepository;
import com.toir.repository.maintenance.MaintenanceRegulationAttributeConditionRepository;
import com.toir.repository.maintenance.MaintenanceRegulationRepository;
import com.toir.repository.maintenance.MaintenanceTemplateRepository;
import com.toir.util.AuditBuilderService;
import com.toir.util.PaginationUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Year;
import java.util.Collection;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class MaintenanceRegulationService {

    private final MaintenanceRegulationRepository repository;
    private final MaintenanceRegulationAttributeConditionRepository conditionRepository;
    private final EquipmentRepository equipmentRepository;
    private final EquipmentTypeRepository equipmentTypeRepository;
    private final EquipmentAttributeDefinitionRepository attributeDefinitionRepository;
    private final MaintenanceTemplateRepository templateRepository;
    private final MaintenanceOperationRepository operationRepository;
    private final AuditBuilderService auditBuilderService;
    private static final int MAX_CODE_GENERATION_ATTEMPTS = 50;
    private static final String CLIENT_CODE_REJECT_MESSAGE =
            "code is generated by backend and must not be provided";


    @Transactional(readOnly = true)
    public List<MaintenanceRegulationDto> findAll() {
        return toDtoList(repository.findAllByIsDeletedFalseOrderByUpdatedAtDesc());
    }

    @Transactional(readOnly = true)
    public Page<MaintenanceRegulationDto> search(int page,
                                                 int pageSize,
                                                 String search,
                                                 UUID equipmentTypeId,
                                                 Boolean active,
                                                 String category) {
        validateEquipmentTypeIfProvided(equipmentTypeId);
        var pageable = PaginationUtils.pageRequest(page, pageSize);
        return repository.searchPaginated(
                equipmentTypeId,
                active,
                blankToNull(category),
                search,
                pageable
        ).map(this::toDto);
    }

    @Transactional(readOnly = true)
    public Page<EquipmentWithRegulationsDto> equipmentWithRegulations(UUID equipmentTypeId,
                                                                      Boolean active,
                                                                      Integer page,
                                                                      Integer size) {
        validateEquipmentTypeIfProvided(equipmentTypeId);
        List<EquipmentWithRegulationsDto> items = equipmentWithRegulations(equipmentTypeId, active);
        if (page == null && size == null) {
            int pageSize = PaginationUtils.pageSizeFromList(0, items.size());
            return new PageImpl<>(items, PaginationUtils.pageRequest(0, pageSize), items.size());
        }
        if (page == null || size == null) {
            throw RestException.badRequest("Both page and size must be provided for paginated equipment regulation list");
        }
        return PaginationUtils.page(items, page, size);
    }

    @Transactional(readOnly = true)
    public MaintenanceRegulationDto findById(UUID id) {
        return toDto(getOrThrow(id));
    }


    @Transactional(readOnly = true)
    public List<MaintenanceRegulation> findActiveByEquipmentType(UUID equipmentTypeId) {
        return repository.findAllByEquipmentTypeIdAndActiveTrueAndIsDeletedFalse(equipmentTypeId);
    }

    @Transactional
    public MaintenanceRegulationDto create(MaintenanceRegulationRequest request) {
        validateClientProvidedCode(request.code());
        MaintenanceRegulation saved = saveWithGeneratedCode(request);
        replaceConditions(saved.getId(), saved.getEquipmentTypeId(), request.attributeConditions());

        auditBuilderService.log(
                "maintenance_regulation",
                saved.getId().toString(),
                AuditAction.CREATE,
                AuditModule.MAINTENANCE_REGULATION,
                "Регламент обслуживания создан",
                null,
                saved);

        return toDto(saved);
    }

    @Transactional
    public MaintenanceRegulationDto update(UUID id, MaintenanceRegulationRequest request) {
        validateClientProvidedCode(request.code());
        MaintenanceRegulation entity = getOrThrow(id);
        applyMutableFields(entity, request);

        MaintenanceRegulation save = repository.save(entity);
        replaceConditions(save.getId(), save.getEquipmentTypeId(), request.attributeConditions());

        auditBuilderService.log(
                "maintenance_regulation",
                id != null ? id.toString() : null,
                AuditAction.UPDATE,
                AuditModule.MAINTENANCE_REGULATION,
                "Регламент обслуживания обновлен",
                entity,
                save);

        return toDto(entity);
    }

    @Transactional
    public void delete(UUID id) {
        var entity = getOrThrow(id);
        entity.setDeleted(true);
        MaintenanceRegulation saved = repository.save(entity);

        auditBuilderService.log(
                "maintenance_regulation",
                saved.getId().toString(),
                AuditAction.DELETE,
                AuditModule.MAINTENANCE_REGULATION,
                "Регламент обслуживания удален",
                saved,
                null);

    }

    private MaintenanceRegulation getOrThrow(UUID id) {
        return repository.findByIdAndIsDeletedFalse(id)
                .orElseThrow(() -> RestException.notFound("Maintenance regulation not found: " + id));
    }

    private List<EquipmentWithRegulationsDto> equipmentWithRegulations(UUID equipmentTypeId, Boolean active) {
        List<Equipment> equipment = equipmentRepository.findAllForMaintenanceRegulations(equipmentTypeId);
        if (equipment == null || equipment.isEmpty()) {
            return List.of();
        }

        Set<UUID> equipmentTypeIds = equipment.stream()
                .filter(Objects::nonNull)
                .map(Equipment::getEquipmentTypeId)
                .filter(Objects::nonNull)
                .collect(Collectors.toSet());
        List<EquipmentType> equipmentTypes = equipmentTypeIds.isEmpty()
                ? List.of()
                : safeList(equipmentTypeRepository.findAllByIdInAndIsDeletedFalse(equipmentTypeIds));
        Map<UUID, EquipmentType> typeById = equipmentTypes
                        .stream()
                        .filter(Objects::nonNull)
                        .collect(Collectors.toMap(EquipmentType::getId, type -> type, (left, right) -> left));
        List<MaintenanceRegulation> regulations = equipmentTypeIds.isEmpty()
                ? List.of()
                : safeList(repository.findAllByEquipmentTypeIdInAndOptionalActive(equipmentTypeIds, active));
        Map<UUID, List<MaintenanceRegulation>> regulationsByTypeId =
                regulations.stream()
                        .filter(regulation -> regulation != null && regulation.getEquipmentTypeId() != null)
                        .collect(Collectors.groupingBy(MaintenanceRegulation::getEquipmentTypeId));
        Map<UUID, MaintenanceRegulationSummaryDto.OperationSummary> operationSummaryByTemplateId =
                operationSummaryByTemplateId(regulationsByTypeId.values().stream()
                        .flatMap(Collection::stream)
                        .map(MaintenanceRegulation::getTemplateId)
                        .filter(Objects::nonNull)
                        .collect(Collectors.toSet()));

        return equipment.stream()
                .filter(Objects::nonNull)
                .map(item -> {
                    EquipmentType type = typeById.get(item.getEquipmentTypeId());
                    List<MaintenanceRegulationSummaryDto> regulations1 = regulationsByTypeId
                            .getOrDefault(item.getEquipmentTypeId(), List.of())
                            .stream()
                            .map(regulation -> MaintenanceRegulationSummaryDto.from(
                                    regulation,
                                    operationSummaryByTemplateId.get(regulation.getTemplateId())
                            ))
                            .filter(Objects::nonNull)
                            .toList();
                    return new EquipmentWithRegulationsDto(
                            item.getId(),
                            item.getName(),
                            item.getCode(),
                            item.getEquipmentTypeId(),
                            type == null ? null : type.getName(),
                            regulations1
                    );
                })
                .toList();
    }

    private Map<UUID, MaintenanceRegulationSummaryDto.OperationSummary> operationSummaryByTemplateId(Set<UUID> templateIds) {
        if (templateIds.isEmpty()) {
            return Map.of();
        }
        return safeList(operationRepository.findAllByTemplateIdInAndIsDeletedFalse(templateIds))
                .stream()
                .filter(Objects::nonNull)
                .filter(operation -> operation.getTemplate() != null && operation.getTemplate().getId() != null)
                .collect(Collectors.groupingBy(operation -> operation.getTemplate().getId()))
                .entrySet()
                .stream()
                .collect(Collectors.toMap(
                        Map.Entry::getKey,
                        entry -> new MaintenanceRegulationSummaryDto.OperationSummary(
                                joinDistinct(entry.getValue(), MaintenanceOperation::getRequiredSkill),
                                joinDistinct(entry.getValue(), MaintenanceOperation::getSafetyNotes),
                                joinDistinct(entry.getValue(), MaintenanceOperation::getToolsRequired),
                                joinDistinct(entry.getValue(), MaintenanceOperation::getSparePartsRequired),
                                joinDistinct(entry.getValue(), MaintenanceOperation::getConsumablesRequired)
                        )
                ));
    }

    private String joinDistinct(List<MaintenanceOperation> operations,
                                java.util.function.Function<MaintenanceOperation, String> getter) {
        String joined = operations.stream()
                .map(getter)
                .filter(value -> value != null && !value.isBlank())
                .map(String::trim)
                .distinct()
                .collect(Collectors.joining("; "));
        return joined.isBlank() ? null : joined;
    }

    private <T> List<T> safeList(List<T> values) {
        return values == null ? List.of() : values;
    }

    private void validateEquipmentTypeIfProvided(UUID equipmentTypeId) {
        if (equipmentTypeId == null) {
            return;
        }
        if (!equipmentTypeRepository.existsByIdAndIsDeletedFalse(equipmentTypeId)) {
            throw RestException.notFound("Equipment type not found: " + equipmentTypeId);
        }
    }

    private void applyMutableFields(MaintenanceRegulation entity, MaintenanceRegulationRequest request) {
        entity.setName(request.name());
        entity.setDescription(request.description());
        entity.setEquipmentTypeId(request.equipmentTypeId());
        entity.setMaintenanceKind(request.maintenanceKind());
        entity.setTemplateId(validatedTemplateId(request));
        entity.setNormativeLaborHours(request.normativeLaborHours());
        if (request.active() != null) entity.setActive(request.active());
        entity.setPeriodicityUnit(request.periodicityUnit());
        entity.setPeriodicityValue(request.periodicityValue());
        entity.setToleranceDays(request.toleranceDays());
        entity.setRequiresShutdown(request.requiresShutdown());
        entity.setTriggerMeterType(request.triggerMeterType());
        entity.setTriggerMeterInterval(request.triggerMeterInterval());
        entity.setTriggerPolicy(request.triggerPolicy() == null ? MaintenanceTriggerPolicy.ANY : request.triggerPolicy());
        entity.setRecalculationPolicy(request.recalculationPolicy() == null
                ? MaintenanceRecalculationPolicy.FROM_ACTUAL_COMPLETION
                : request.recalculationPolicy());
    }

    private void replaceConditions(UUID regulationId,
                                   UUID equipmentTypeId,
                                   List<MaintenanceRegulationAttributeConditionRequest> requests) {
        if (requests == null) {
            return;
        }
        if (conditionRepository == null) {
            return;
        }
        List<MaintenanceRegulationAttributeCondition> existing =
                conditionRepository.findAllByRegulationIdAndIsDeletedFalse(regulationId);
        for (MaintenanceRegulationAttributeCondition condition : existing) {
            condition.setDeleted(true);
        }
        if (!existing.isEmpty()) {
            conditionRepository.saveAll(existing);
        }

        List<MaintenanceRegulationAttributeCondition> toSave = requests.stream()
                .map(request -> toCondition(regulationId, equipmentTypeId, request))
                .toList();
        if (!toSave.isEmpty()) {
            conditionRepository.saveAll(toSave);
        }
    }

    private MaintenanceRegulationAttributeCondition toCondition(UUID regulationId,
                                                               UUID equipmentTypeId,
                                                               MaintenanceRegulationAttributeConditionRequest request) {
        if (request == null) {
            throw RestException.badRequest("Attribute condition is required");
        }
        String key = normalizeAttributeKey(request.attributeKey());
        if (!attributeDefinitionRepository.existsActiveByEquipmentTypeIdAndKey(equipmentTypeId, key)) {
            throw RestException.badRequest("Unknown equipment attribute key for regulation type: " + key);
        }
        validateConditionValue(request);

        MaintenanceRegulationAttributeCondition condition = new MaintenanceRegulationAttributeCondition();
        condition.setRegulationId(regulationId);
        condition.setAttributeKey(key);
        condition.setOperator(request.operator());
        condition.setValueText(request.valueText());
        condition.setValueNumber(request.valueNumber());
        condition.setValueDate(request.valueDate());
        condition.setValueBoolean(request.valueBoolean());
        condition.setValueOption(request.valueOption());
        return condition;
    }

    private void validateConditionValue(MaintenanceRegulationAttributeConditionRequest request) {
        if (request.operator() == null) {
            throw RestException.badRequest("Condition operator is required");
        }
        if (request.operator() == MaintenanceRegulationConditionOperator.EXISTS
                || request.operator() == MaintenanceRegulationConditionOperator.NOT_EXISTS) {
            return;
        }
        boolean hasValue = request.valueText() != null
                || request.valueNumber() != null
                || request.valueDate() != null
                || request.valueBoolean() != null
                || request.valueOption() != null;
        if (!hasValue) {
            throw RestException.badRequest("Condition value is required");
        }
    }

    private String normalizeAttributeKey(String key) {
        if (key == null || key.isBlank()) {
            throw RestException.badRequest("Attribute condition key is required");
        }
        return key.trim().toLowerCase(Locale.ROOT);
    }

    private void validateClientProvidedCode(String code) {
        if (code != null && !code.isBlank()) {
            throw RestException.badRequest(CLIENT_CODE_REJECT_MESSAGE);
        }
    }

    private String blankToNull(String value) {
        return value == null || value.isBlank() ? null : value.trim();
    }

    private MaintenanceRegulation saveWithGeneratedCode(MaintenanceRegulationRequest request) {
        int year = Year.now().getValue();
        String codePrefix = "MR-" + year + "-";
        long sequence = repository.maxSequenceByCodePrefix(codePrefix) + 1;

        for (int attempt = 0; attempt < MAX_CODE_GENERATION_ATTEMPTS; attempt++) {
            String code = formatCode("MR", year, sequence + attempt);
            if (repository.existsByCode(code)) {
                continue;
            }

            MaintenanceRegulation entity = new MaintenanceRegulation();
            entity.setCode(code);
            applyMutableFields(entity, request);

            try {
                return repository.save(entity);
            } catch (DataIntegrityViolationException ex) {
                if (isCodeConflict(ex)) {
                    continue;
                }
                throw ex;
            }
        }

        throw RestException.conflict("Could not generate unique maintenance regulation code");
    }

    private String formatCode(String prefix, int year, long sequence) {
        return "%s-%d-%04d".formatted(prefix, year, sequence);
    }

    private boolean isCodeConflict(DataIntegrityViolationException ex) {
        Throwable root = ex.getMostSpecificCause();
        String message = root != null ? root.getMessage() : ex.getMessage();
        if (message == null) {
            return false;
        }
        String normalized = message.toLowerCase(Locale.ROOT);
        return normalized.contains("maintenance_regulations_code_key")
                || (normalized.contains("maintenance_regulations")
                && normalized.contains("duplicate")
                && normalized.contains("code"));
    }

    private MaintenanceRegulationDto toDto(MaintenanceRegulation r) {
        if (r == null) return null;
        List<MaintenanceRegulationAttributeConditionDto> conditions = conditionDtos(r.getId());
        String equipmentTypeName = r.getEquipmentTypeId() == null ? null : equipmentTypeRepository.findByIdAndIsDeletedFalse(r.getEquipmentTypeId())
                .map(EquipmentType::getName)
                .orElse(null);
        MaintenanceTemplate template = r.getTemplateId() == null ? null : templateRepository.findByIdAndIsDeletedFalse(r.getTemplateId())
                .orElse(null);
        return MaintenanceRegulationDto.from(
                r,
                equipmentTypeName,
                template == null ? null : template.getCode(),
                template == null ? null : template.getName(),
                conditions
        );
    }

    private UUID validatedTemplateId(MaintenanceRegulationRequest request) {
        UUID templateId = request.templateId();
        if (templateId == null) {
            return null;
        }

        MaintenanceTemplate template = templateRepository.findByIdAndIsDeletedFalse(templateId)
                .orElseThrow(() -> RestException.notFound("Maintenance template not found: " + templateId));
        if (!Objects.equals(template.getEquipmentTypeId(), request.equipmentTypeId())) {
            throw RestException.badRequest("Maintenance template equipment type must match regulation equipment type");
        }
        if (template.getMaintenanceKind() != request.maintenanceKind()) {
            throw RestException.badRequest("Maintenance template kind must match regulation maintenance kind");
        }
        if (!template.isActive()) {
            throw RestException.badRequest("Maintenance template must be active");
        }
        return templateId;
    }

    private List<MaintenanceRegulationDto> toDtoList(List<MaintenanceRegulation> regulations) {
        if (regulations == null || regulations.isEmpty()) return List.of();
        Set<UUID> eqTypeIds = regulations.stream()
                .map(MaintenanceRegulation::getEquipmentTypeId)
                .filter(Objects::nonNull)
                .collect(Collectors.toSet());
        Map<UUID, String> eqTypeNames = equipmentTypeRepository.findAllByIdInAndIsDeletedFalse(eqTypeIds).stream()
                .collect(Collectors.toMap(EquipmentType::getId, EquipmentType::getName));
        Set<UUID> templateIds = regulations.stream()
                .map(MaintenanceRegulation::getTemplateId)
                .filter(Objects::nonNull)
                .collect(Collectors.toSet());
        Map<UUID, MaintenanceTemplate> templates = templateIds.isEmpty()
                ? Map.of()
                : templateRepository.findAllByIdInAndIsDeletedFalse(templateIds).stream()
                .collect(Collectors.toMap(MaintenanceTemplate::getId, template -> template));
        Set<UUID> regulationIds = regulations.stream().map(MaintenanceRegulation::getId).collect(Collectors.toSet());
        Map<UUID, List<MaintenanceRegulationAttributeConditionDto>> conditionsByRegulationId =
                conditionDtosByRegulationId(regulationIds);
        return regulations.stream()
                .map(r -> {
                    MaintenanceTemplate template = templates.get(r.getTemplateId());
                    return MaintenanceRegulationDto.from(
                            r,
                            eqTypeNames.getOrDefault(r.getEquipmentTypeId(), null),
                            template == null ? null : template.getCode(),
                            template == null ? null : template.getName(),
                            conditionsByRegulationId.getOrDefault(r.getId(), List.of())
                    );
                })
                .toList();
    }

    private List<MaintenanceRegulationAttributeConditionDto> conditionDtos(UUID regulationId) {
        if (conditionRepository == null) {
            return List.of();
        }
        List<MaintenanceRegulationAttributeCondition> conditions =
                conditionRepository.findAllByRegulationIdAndIsDeletedFalse(regulationId);
        if (conditions == null || conditions.isEmpty()) {
            return List.of();
        }
        return conditions.stream()
                .map(MaintenanceRegulationAttributeConditionDto::from)
                .toList();
    }

    private Map<UUID, List<MaintenanceRegulationAttributeConditionDto>> conditionDtosByRegulationId(Set<UUID> regulationIds) {
        if (conditionRepository == null || regulationIds.isEmpty()) {
            return Map.of();
        }
        List<MaintenanceRegulationAttributeCondition> conditions =
                conditionRepository.findAllByRegulationIdInAndIsDeletedFalse(regulationIds);
        if (conditions == null || conditions.isEmpty()) {
            return Map.of();
        }
        return conditions.stream()
                .collect(Collectors.groupingBy(
                        MaintenanceRegulationAttributeCondition::getRegulationId,
                        Collectors.mapping(MaintenanceRegulationAttributeConditionDto::from, Collectors.toList())
                ));
    }
}
