package com.toir.service.maintanance;

import com.toir.repository.equipment.EquipmentTypeRepository;

import com.toir.dto.maintenancetemplate.MaintenanceOperationDto;
import com.toir.dto.maintenancetemplate.MaintenanceTemplateDto;
import com.toir.dto.maintenancetemplate.MaintenanceTemplateRequest;
import com.toir.entity.equipment.EquipmentType;
import com.toir.entity.maintenance.MaintenanceOperation;
import com.toir.entity.maintenance.MaintenanceTemplate;
import com.toir.enums.MaintenanceKind;
import com.toir.exception.RestException;
import com.toir.repository.maintenance.MaintenanceActionRepository;
import com.toir.repository.maintenance.MaintenanceOperationRepository;
import com.toir.repository.maintenance.MaintenanceTemplateRepository;
import com.toir.repository.users.UserRepository;
import com.toir.service.SparePartService;
import com.toir.util.AuditBuilderService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;

import java.time.Year;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class MaintenanceTemplateServiceTest {

    @Mock
    MaintenanceTemplateRepository repository;

    @Mock
    MaintenanceOperationRepository operationRepository;

    @Mock
    MaintenanceActionRepository actionRepository;

    @Mock
    SparePartService sparePartService;

    @Mock
    AuditBuilderService auditBuilderService;

    @Mock
    EquipmentTypeRepository equipmentTypeRepository;

    @Mock
    UserRepository userRepository;

    @InjectMocks
    MaintenanceTemplateService service;

    @BeforeEach
    void setUpEquipmentTypeValidation() {
        lenient().when(equipmentTypeRepository.findAllByIdInAndIsDeletedFalse(any()))
                .thenAnswer(invocation -> {
                    Collection<UUID> ids = invocation.getArgument(0);
                    return ids.stream().map(id -> {
                        EquipmentType equipmentType = new EquipmentType();
                        equipmentType.setId(id);
                        equipmentType.setName("Equipment type");
                        return equipmentType;
                    }).toList();
                });
    }

    @Test
    void createWithoutCodeGeneratesCode() {
        int year = Year.now().getValue();
        String codePrefix = "MT-" + year + "-";
        String expectedCode = "MT-" + year + "-0001";

        when(repository.maxSequenceByCodePrefix(codePrefix)).thenReturn(0L);
        when(repository.existsByCode(expectedCode)).thenReturn(false);
        when(repository.save(any(MaintenanceTemplate.class))).thenAnswer(invocation -> {
            MaintenanceTemplate template = invocation.getArgument(0);
            template.setId(UUID.randomUUID());
            return template;
        });

        MaintenanceTemplateDto created = service.create(request(null));

        assertThat(created.code()).isEqualTo(expectedCode);
        verify(repository).maxSequenceByCodePrefix(codePrefix);

        ArgumentCaptor<MaintenanceTemplate> captor = ArgumentCaptor.forClass(MaintenanceTemplate.class);
        verify(repository).save(captor.capture());
        assertThat(captor.getValue().getCode()).isEqualTo(expectedCode);
    }

    @Test
    void createWithClientCodeReturns400() {
        assertThatThrownBy(() -> service.create(request("MT-2026-9999")))
                .isInstanceOfSatisfying(RestException.class, ex -> {
                    assertThat(ex.getStatus()).isEqualTo(HttpStatus.BAD_REQUEST);
                    assertThat(ex.getMessage()).isEqualTo("code is generated by backend and must not be provided");
                });

        verify(repository, never()).maxSequenceByCodePrefix(anyString());
        verify(repository, never()).save(any(MaintenanceTemplate.class));
    }

    @Test
    void updateDoesNotAllowChangingCode() {
        UUID templateId = UUID.randomUUID();
        MaintenanceTemplate existing = new MaintenanceTemplate();
        existing.setId(templateId);
        existing.setCode("MT-2026-0001");
        existing.setName("Template");
        existing.setEquipmentTypeId(UUID.randomUUID());
        existing.setMaintenanceKind(MaintenanceKind.PREVENTIVE);
        existing.setNormativeLaborHours(2.0);

        assertThatThrownBy(() -> service.update(templateId, request("MT-2026-0002")))
                .isInstanceOfSatisfying(RestException.class, ex -> {
                    assertThat(ex.getStatus()).isEqualTo(HttpStatus.BAD_REQUEST);
                    assertThat(ex.getMessage()).isEqualTo("code is generated by backend and must not be provided");
                });

        verify(repository, never()).save(any(MaintenanceTemplate.class));
    }

    @Test
    void generatedCodeIsUnique() {
        int year = Year.now().getValue();
        String codePrefix = "MT-" + year + "-";
        String firstCandidate = "MT-" + year + "-0001";
        String secondCandidate = "MT-" + year + "-0002";

        when(repository.maxSequenceByCodePrefix(codePrefix)).thenReturn(0L);
        when(repository.existsByCode(firstCandidate)).thenReturn(true);
        when(repository.existsByCode(secondCandidate)).thenReturn(false);
        when(repository.save(any(MaintenanceTemplate.class))).thenAnswer(invocation -> {
            MaintenanceTemplate template = invocation.getArgument(0);
            template.setId(UUID.randomUUID());
            return template;
        });

        MaintenanceTemplateDto created = service.create(request(null));

        assertThat(created.code()).isEqualTo(secondCandidate);
        verify(repository).existsByCode(firstCandidate);
        verify(repository).existsByCode(secondCandidate);
    }

    @Test
    void duplicateCodeDoesNotReturn500() {
        int year = Year.now().getValue();
        String codePrefix = "MT-" + year + "-";
        String firstCandidate = "MT-" + year + "-0001";
        String secondCandidate = "MT-" + year + "-0002";

        when(repository.maxSequenceByCodePrefix(codePrefix)).thenReturn(0L);
        when(repository.existsByCode(firstCandidate)).thenReturn(false);
        when(repository.existsByCode(secondCandidate)).thenReturn(false);
        when(repository.save(any(MaintenanceTemplate.class)))
                .thenThrow(new DataIntegrityViolationException(
                        "duplicate key value violates unique constraint \"maintenance_templates_code_key\""))
                .thenAnswer(invocation -> {
                    MaintenanceTemplate template = invocation.getArgument(0);
                    template.setId(UUID.randomUUID());
                    return template;
                });

        MaintenanceTemplateDto created = service.create(request(null));

        assertThat(created.code()).isEqualTo(secondCandidate);
        verify(repository, times(2)).save(any(MaintenanceTemplate.class));
    }

    @Test
    void addOperationWithDuplicateSequenceReturns400() {
        UUID templateId = UUID.randomUUID();
        MaintenanceTemplate template = template(templateId);
        when(repository.findByIdAndIsDeletedFalse(templateId)).thenReturn(Optional.of(template));
        when(operationRepository.existsByTemplateIdAndSequence(templateId, 1)).thenReturn(true);

        assertThatThrownBy(() -> service.addOperation(templateId, operationRequest(null, 1, "Inspect seal")))
                .isInstanceOfSatisfying(RestException.class, ex -> {
                    assertThat(ex.getStatus()).isEqualTo(HttpStatus.BAD_REQUEST);
                    assertThat(ex.getMessage()).isEqualTo("Checklist item sequence must be unique within the same template");
                });

        verify(operationRepository, never()).save(any(MaintenanceOperation.class));
    }

    @Test
    void addOperationWithoutSequenceGeneratesNextSequence() {
        UUID templateId = UUID.randomUUID();
        MaintenanceTemplate template = template(templateId);
        when(repository.findByIdAndIsDeletedFalse(templateId)).thenReturn(Optional.of(template));
        when(operationRepository.maxSequenceByTemplateId(templateId)).thenReturn(2);
        when(operationRepository.existsByTemplateIdAndSequence(templateId, 3)).thenReturn(false);
        when(operationRepository.save(any(MaintenanceOperation.class))).thenAnswer(invocation -> {
            MaintenanceOperation op = invocation.getArgument(0);
            op.setId(UUID.randomUUID());
            return op;
        });

        MaintenanceOperationDto created = service.addOperation(templateId, operationRequest(null, null, "Inspect seal"));

        assertThat(created.sequence()).isEqualTo(3);
    }

    @Test
    void addOperationWithExistingIdUpdatesInsteadOfAppendingDuplicateRow() {
        UUID templateId = UUID.randomUUID();
        UUID operationId = UUID.randomUUID();
        MaintenanceTemplate template = template(templateId);
        MaintenanceOperation existing = new MaintenanceOperation();
        existing.setId(operationId);
        existing.setTemplate(template);
        existing.setSequence(1);
        existing.setName("Old step");
        existing.setDurationHours(1.0);
        template.getOperations().add(existing);

        when(repository.findByIdAndIsDeletedFalse(templateId)).thenReturn(Optional.of(template));
        when(operationRepository.findByIdAndIsDeletedFalse(operationId)).thenReturn(Optional.of(existing));
        when(operationRepository.existsByTemplateIdAndSequenceAndIdNot(templateId, 2, operationId)).thenReturn(false);
        when(operationRepository.save(any(MaintenanceOperation.class))).thenAnswer(invocation -> invocation.getArgument(0));

        MaintenanceOperationDto updated = service.addOperation(templateId, operationRequest(operationId, 2, "Updated step"));

        assertThat(updated.id()).isEqualTo(operationId);
        assertThat(updated.sequence()).isEqualTo(2);
        assertThat(updated.name()).isEqualTo("Updated step");
        assertThat(template.getOperations()).hasSize(1);
    }

    private MaintenanceTemplateRequest request(String code) {
        return new MaintenanceTemplateRequest(
                code,
                "Pump monthly PM",
                "Template description",
                UUID.randomUUID(),
                MaintenanceKind.PREVENTIVE,
                4.5,
                true
        );
    }

    private MaintenanceOperationDto operationRequest(UUID id, Integer sequence, String name) {
        return new MaintenanceOperationDto(
                id,
                null,
                null,
                null,
                sequence,
                name,
                "Description",
                1.0,
                "Mechanic",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        );
    }

    private MaintenanceTemplate template(UUID templateId) {
        MaintenanceTemplate template = new MaintenanceTemplate();
        template.setId(templateId);
        template.setCode("MT-2026-0001");
        template.setName("Template");
        template.setEquipmentTypeId(UUID.randomUUID());
        template.setMaintenanceKind(MaintenanceKind.PREVENTIVE);
        template.setNormativeLaborHours(2.0);
        return template;
    }
}
