package com.toir.service.maintanance;

import com.toir.repository.equipment.EquipmentTypeRepository;

import com.toir.dto.maintenanceregulation.MaintenanceRegulationAttributeConditionRequest;
import com.toir.dto.maintenanceregulation.MaintenanceRegulationDto;
import com.toir.dto.maintenanceregulation.MaintenanceRegulationRequest;
import com.toir.entity.maintenance.MaintenanceRegulation;
import com.toir.entity.maintenance.MaintenanceRegulationAttributeCondition;
import com.toir.enums.MaintenanceKind;
import com.toir.enums.MeterType;
import com.toir.enums.MaintenanceRegulationConditionOperator;
import com.toir.enums.PeriodicityUnit;
import com.toir.exception.RestException;
import com.toir.repository.equipment.EquipmentAttributeDefinitionRepository;
import com.toir.repository.maintenance.MaintenanceRegulationAttributeConditionRepository;
import com.toir.repository.maintenance.MaintenanceRegulationRepository;
import com.toir.util.AuditBuilderService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;

import java.time.Year;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class MaintenanceRegulationServiceTest {

    @Mock
    MaintenanceRegulationRepository repository;

    @Mock
    AuditBuilderService auditBuilderService;

    @Mock
    EquipmentTypeRepository equipmentTypeRepository;

    @Mock
    EquipmentAttributeDefinitionRepository attributeDefinitionRepository;

    @Mock
    MaintenanceRegulationAttributeConditionRepository conditionRepository;

    @InjectMocks
    MaintenanceRegulationService service;

    @Test
    void createWithoutCodeGeneratesCode() {
        int year = Year.now().getValue();
        String codePrefix = "MR-" + year + "-";
        String expectedCode = "MR-" + year + "-0001";

        when(repository.maxSequenceByCodePrefix(codePrefix)).thenReturn(0L);
        when(repository.existsByCode(expectedCode)).thenReturn(false);
        when(repository.save(any(MaintenanceRegulation.class))).thenAnswer(invocation -> {
            MaintenanceRegulation regulation = invocation.getArgument(0);
            regulation.setId(UUID.randomUUID());
            return regulation;
        });

        MaintenanceRegulationDto created = service.create(request(null));

        assertThat(created.code()).isEqualTo(expectedCode);
        verify(repository).maxSequenceByCodePrefix(codePrefix);

        ArgumentCaptor<MaintenanceRegulation> captor = ArgumentCaptor.forClass(MaintenanceRegulation.class);
        verify(repository).save(captor.capture());
        assertThat(captor.getValue().getCode()).isEqualTo(expectedCode);
    }

    @Test
    void createWithClientCodeReturns400() {
        assertThatThrownBy(() -> service.create(request("MR-2026-9999")))
                .isInstanceOfSatisfying(RestException.class, ex -> {
                    assertThat(ex.getStatus()).isEqualTo(HttpStatus.BAD_REQUEST);
                    assertThat(ex.getMessage()).isEqualTo("code is generated by backend and must not be provided");
                });

        verify(repository, never()).maxSequenceByCodePrefix(anyString());
        verify(repository, never()).save(any(MaintenanceRegulation.class));
    }

    @Test
    void updateDoesNotAllowChangingCode() {
        UUID regulationId = UUID.randomUUID();
        MaintenanceRegulation existing = new MaintenanceRegulation();
        existing.setId(regulationId);
        existing.setCode("MR-2026-0001");
        existing.setName("Regulation");
        existing.setEquipmentTypeId(UUID.randomUUID());
        existing.setMaintenanceKind(MaintenanceKind.PREVENTIVE);
        existing.setNormativeLaborHours(2.0);
        existing.setPeriodicityUnit(PeriodicityUnit.MONTH);
        existing.setPeriodicityValue(1);
        existing.setRequiresShutdown(false);

        assertThatThrownBy(() -> service.update(regulationId, request("MR-2026-0002")))
                .isInstanceOfSatisfying(RestException.class, ex -> {
                    assertThat(ex.getStatus()).isEqualTo(HttpStatus.BAD_REQUEST);
                    assertThat(ex.getMessage()).isEqualTo("code is generated by backend and must not be provided");
                });

        verify(repository, never()).save(any(MaintenanceRegulation.class));
    }

    @Test
    void generatedCodeIsUnique() {
        int year = Year.now().getValue();
        String codePrefix = "MR-" + year + "-";
        String firstCandidate = "MR-" + year + "-0001";
        String secondCandidate = "MR-" + year + "-0002";

        when(repository.maxSequenceByCodePrefix(codePrefix)).thenReturn(0L);
        when(repository.existsByCode(firstCandidate)).thenReturn(true);
        when(repository.existsByCode(secondCandidate)).thenReturn(false);
        when(repository.save(any(MaintenanceRegulation.class))).thenAnswer(invocation -> {
            MaintenanceRegulation regulation = invocation.getArgument(0);
            regulation.setId(UUID.randomUUID());
            return regulation;
        });

        MaintenanceRegulationDto created = service.create(request(null));

        assertThat(created.code()).isEqualTo(secondCandidate);
        verify(repository).existsByCode(firstCandidate);
        verify(repository).existsByCode(secondCandidate);
    }

    @Test
    void duplicateCodeDoesNotReturn500() {
        int year = Year.now().getValue();
        String codePrefix = "MR-" + year + "-";
        String firstCandidate = "MR-" + year + "-0001";
        String secondCandidate = "MR-" + year + "-0002";

        when(repository.maxSequenceByCodePrefix(codePrefix)).thenReturn(0L);
        when(repository.existsByCode(firstCandidate)).thenReturn(false);
        when(repository.existsByCode(secondCandidate)).thenReturn(false);
        when(repository.save(any(MaintenanceRegulation.class)))
                .thenThrow(new DataIntegrityViolationException(
                        "duplicate key value violates unique constraint \"maintenance_regulations_code_key\""))
                .thenAnswer(invocation -> {
                    MaintenanceRegulation regulation = invocation.getArgument(0);
                    regulation.setId(UUID.randomUUID());
                    return regulation;
                });

        MaintenanceRegulationDto created = service.create(request(null));

        assertThat(created.code()).isEqualTo(secondCandidate);
        verify(repository, times(2)).save(any(MaintenanceRegulation.class));
    }

    @Test
    void createWithAttributeConditionPersistsCondition() {
        int year = Year.now().getValue();
        String codePrefix = "MR-" + year + "-";
        String expectedCode = "MR-" + year + "-0001";
        UUID typeId = UUID.randomUUID();

        when(repository.maxSequenceByCodePrefix(codePrefix)).thenReturn(0L);
        when(repository.existsByCode(expectedCode)).thenReturn(false);
        when(repository.save(any(MaintenanceRegulation.class))).thenAnswer(invocation -> {
            MaintenanceRegulation regulation = invocation.getArgument(0);
            regulation.setId(UUID.randomUUID());
            regulation.setEquipmentTypeId(typeId);
            return regulation;
        });
        when(attributeDefinitionRepository.existsActiveByEquipmentTypeIdAndKey(typeId, "motor_power")).thenReturn(true);
        when(conditionRepository.findAllByRegulationIdAndIsDeletedFalse(any())).thenReturn(List.of());

        MaintenanceRegulationDto created = service.create(requestWithCondition(null, typeId, "motor_power"));

        assertThat(created.code()).isEqualTo(expectedCode);
        ArgumentCaptor<Iterable<MaintenanceRegulationAttributeCondition>> captor =
                ArgumentCaptor.forClass(Iterable.class);
        verify(conditionRepository).saveAll(captor.capture());
        MaintenanceRegulationAttributeCondition condition =
                ((List<MaintenanceRegulationAttributeCondition>) captor.getValue()).getFirst();
        assertThat(condition.getAttributeKey()).isEqualTo("motor_power");
        assertThat(condition.getOperator()).isEqualTo(MaintenanceRegulationConditionOperator.GREATER_THAN);
        assertThat(condition.getValueNumber()).isEqualTo(50.0);
    }

    @Test
    void createWithUnknownConditionAttributeReturns400() {
        int year = Year.now().getValue();
        String expectedCode = "MR-" + year + "-0001";
        UUID typeId = UUID.randomUUID();
        when(repository.maxSequenceByCodePrefix("MR-" + year + "-")).thenReturn(0L);
        when(repository.existsByCode(expectedCode)).thenReturn(false);
        when(repository.save(any(MaintenanceRegulation.class))).thenAnswer(invocation -> {
            MaintenanceRegulation regulation = invocation.getArgument(0);
            regulation.setId(UUID.randomUUID());
            regulation.setEquipmentTypeId(typeId);
            return regulation;
        });
        when(attributeDefinitionRepository.existsActiveByEquipmentTypeIdAndKey(typeId, "unknown_key")).thenReturn(false);
        when(conditionRepository.findAllByRegulationIdAndIsDeletedFalse(any())).thenReturn(List.of());

        assertThatThrownBy(() -> service.create(requestWithCondition(null, typeId, "unknown_key")))
                .isInstanceOfSatisfying(RestException.class, ex -> {
                    assertThat(ex.getStatus()).isEqualTo(HttpStatus.BAD_REQUEST);
                    assertThat(ex.getMessage()).contains("Unknown equipment attribute key");
                });
    }

    @Test
    void findByIdIncludesAttributeConditions() {
        UUID regulationId = UUID.randomUUID();
        UUID typeId = UUID.randomUUID();
        MaintenanceRegulation regulation = new MaintenanceRegulation();
        regulation.setId(regulationId);
        regulation.setCode("MR-2026-0001");
        regulation.setName("High-power pump regulation");
        regulation.setEquipmentTypeId(typeId);
        regulation.setMaintenanceKind(MaintenanceKind.PREVENTIVE);
        regulation.setNormativeLaborHours(4.0);
        regulation.setActive(true);
        regulation.setPeriodicityUnit(PeriodicityUnit.MONTH);
        regulation.setPeriodicityValue(1);
        regulation.setRequiresShutdown(false);

        MaintenanceRegulationAttributeCondition condition = new MaintenanceRegulationAttributeCondition();
        condition.setId(UUID.randomUUID());
        condition.setRegulationId(regulationId);
        condition.setAttributeKey("motor_power");
        condition.setOperator(MaintenanceRegulationConditionOperator.GREATER_THAN);
        condition.setValueNumber(50.0);

        when(repository.findByIdAndIsDeletedFalse(regulationId)).thenReturn(Optional.of(regulation));
        when(equipmentTypeRepository.findByIdAndIsDeletedFalse(typeId)).thenReturn(Optional.empty());
        when(conditionRepository.findAllByRegulationIdAndIsDeletedFalse(regulationId)).thenReturn(List.of(condition));

        MaintenanceRegulationDto dto = service.findById(regulationId);

        assertThat(dto.attributeConditions()).hasSize(1);
        assertThat(dto.attributeConditions().getFirst().attributeKey()).isEqualTo("motor_power");
        assertThat(dto.attributeConditions().getFirst().operator())
                .isEqualTo(MaintenanceRegulationConditionOperator.GREATER_THAN);
        assertThat(dto.attributeConditions().getFirst().valueNumber()).isEqualTo(50.0);
    }

    private MaintenanceRegulationRequest request(String code) {
        return new MaintenanceRegulationRequest(
                code,
                "Monthly pump regulation",
                "Regulation description",
                UUID.randomUUID(),
                MaintenanceKind.PREVENTIVE,
                3.0,
                true,
                PeriodicityUnit.MONTH,
                1,
                3,
                false,
                MeterType.CUSTOM,
                10.0
        );
    }

    private MaintenanceRegulationRequest requestWithCondition(String code, UUID typeId, String attributeKey) {
        return new MaintenanceRegulationRequest(
                code,
                "High-power pump regulation",
                "Only pumps above 50 kW",
                typeId,
                MaintenanceKind.PREVENTIVE,
                4.0,
                true,
                PeriodicityUnit.MONTH,
                1,
                3,
                false,
                MeterType.CUSTOM,
                10.0,
                List.of(new MaintenanceRegulationAttributeConditionRequest(
                        attributeKey,
                        MaintenanceRegulationConditionOperator.GREATER_THAN,
                        null,
                        50.0,
                        null,
                        null,
                        null
                ))
        );
    }
}
