package com.toir.controller;

import com.toir.controller.equipment.EquipmentController;
import com.toir.dto.equipment.EquipmentDto;
import com.toir.enums.EquipmentCategory;
import com.toir.enums.EquipmentStatus;
import com.toir.exception.GlobalExceptionHandler;
import com.toir.exception.RestException;
import com.toir.security.SecurityScope;
import com.toir.service.equipment.EquipmentService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.core.NestedExceptionUtils;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.util.UUID;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.fail;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@ExtendWith(MockitoExtension.class)
class EquipmentControllerContractTest {

    @Mock
    EquipmentService service;

    @Mock
    SecurityScope securityScope;

    private MockMvc mockMvc;

    @BeforeEach
    void setUp() {
        mockMvc = MockMvcBuilders.standaloneSetup(new EquipmentController(service, securityScope))
                .setControllerAdvice(new GlobalExceptionHandler())
                .build();
    }

    @Test
    void createWithoutCodeReturnsCreatedWithGeneratedCode() throws Exception {
        UUID id = UUID.randomUUID();
        UUID equipmentTypeId = UUID.randomUUID();
        UUID departmentId = UUID.randomUUID();
        EquipmentDto dto = new EquipmentDto(
                id,
                "EQ-2026-0020",
                "Compressor A",
                "INV-1",
                null,
                null,
                null,
                equipmentTypeId,
                departmentId,
                null,
                null,
                null,
                null,
                null,
                EquipmentStatus.ACTIVE,
                EquipmentCategory.PRODUCTION_EQUIPMENT,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        );
        when(service.create(any())).thenReturn(dto);

        mockMvc.perform(post("/api/v1/equipment")
                        .contentType("application/json")
                        .content("""
                                {
                                  "name": "Compressor A",
                                  "inventoryNumber": "INV-1",
                                  "equipmentTypeId": "%s",
                                  "departmentId": "%s"
                                }
                                """.formatted(equipmentTypeId, departmentId)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").value(id.toString()))
                .andExpect(jsonPath("$.code").value("EQ-2026-0020"));
    }

    @Test
    void createWithClientProvidedCodeReturnsBadRequest() throws Exception {
        UUID equipmentTypeId = UUID.randomUUID();
        UUID departmentId = UUID.randomUUID();
        when(service.create(any())).thenThrow(RestException.badRequest("Equipment code is generated by system and must not be provided"));

        mockMvc.perform(post("/api/v1/equipment")
                        .contentType("application/json")
                        .content("""
                                {
                                  "code": "EQ-2026-0017",
                                  "name": "Compressor A",
                                  "inventoryNumber": "INV-2",
                                  "equipmentTypeId": "%s",
                                  "departmentId": "%s"
                                }
                                """.formatted(equipmentTypeId, departmentId)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Equipment code is generated by system and must not be provided"));
    }

    @Test
    void updateWithClientProvidedCodeReturnsBadRequest() throws Exception {
        UUID id = UUID.randomUUID();
        UUID equipmentTypeId = UUID.randomUUID();
        UUID departmentId = UUID.randomUUID();
        when(service.update(eq(id), any())).thenThrow(RestException.badRequest("Equipment code is generated by system and must not be provided"));

        mockMvc.perform(put("/api/v1/equipment/{id}", id)
                        .contentType("application/json")
                        .content("""
                                {
                                  "code": "EQ-2026-0017",
                                  "name": "Compressor A",
                                  "inventoryNumber": "INV-2",
                                  "equipmentTypeId": "%s",
                                  "departmentId": "%s"
                                }
                                """.formatted(equipmentTypeId, departmentId)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Equipment code is generated by system and must not be provided"));
    }

    @Test
    void listShouldSupportBusinessSearchByCode() throws Exception {
        when(securityScope.enforceDepartmentScope(null)).thenReturn(null);
        when(service.search(null, null, null, null, null, false, "EQ-2026-0012", 0, 20))
                .thenReturn(Page.empty(PageRequest.of(0, 20)));

        MvcResult result = mockMvc.perform(get("/api/v1/equipment").param("search", "EQ-2026-0012"))
                .andDo(this::assertNoResolvedException)
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content").isArray())
                .andExpect(jsonPath("$.content").isEmpty())
                .andReturn();

        assertNull(result.getResolvedException());

        verify(service).search(null, null, null, null, null, false, "EQ-2026-0012", 0, 20);
    }

    @Test
    void listShouldSupportBusinessSearchByNameAndReturnEmptyPage() throws Exception {
        when(securityScope.enforceDepartmentScope(null)).thenReturn(null);
        when(service.search(null, null, null, null, null, false, "compressor", 0, 20))
                .thenReturn(Page.empty(PageRequest.of(0, 20)));

        MvcResult result = mockMvc.perform(get("/api/v1/equipment").param("search", "compressor"))
                .andDo(this::assertNoResolvedException)
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content").isArray())
                .andExpect(jsonPath("$.content").isEmpty())
                .andReturn();

        assertNull(result.getResolvedException());

        verify(service).search(null, null, null, null, null, false, "compressor", 0, 20);
    }

    private void assertNoResolvedException(MvcResult result) {
        Exception ex = result.getResolvedException();
        if (ex == null) {
            return;
        }
        Throwable root = NestedExceptionUtils.getMostSpecificCause(ex);
        String rootMessage = root != null ? root.getClass().getName() + ": " + root.getMessage() : "n/a";
        fail("Resolved exception: " + ex.getClass().getName() + ": " + ex.getMessage() + "; root cause: " + rootMessage);
    }
}
