package com.toir.controller;

import com.toir.controller.maintenance.MaintenanceTemplateController;
import com.toir.dto.maintenancetemplate.MaintenanceTemplateDto;
import com.toir.enums.MaintenanceKind;
import com.toir.exception.GlobalExceptionHandler;
import com.toir.exception.RestException;
import com.toir.service.maintanance.MaintenanceTemplateService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.time.Year;
import java.util.List;
import java.util.UUID;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@ExtendWith(MockitoExtension.class)
class MaintenanceTemplateControllerContractTest {

    @Mock
    MaintenanceTemplateService service;

    private MockMvc mockMvc;

    @BeforeEach
    void setUp() {
        mockMvc = MockMvcBuilders.standaloneSetup(new MaintenanceTemplateController(service))
                .setControllerAdvice(new GlobalExceptionHandler())
                .build();
    }

    @Test
    void createWithoutCodeReturnsGeneratedCode() throws Exception {
        UUID id = UUID.randomUUID();
        UUID equipmentTypeId = UUID.randomUUID();
        String generatedCode = "MT-" + Year.now().getValue() + "-0001";
        MaintenanceTemplateDto dto = new MaintenanceTemplateDto(
                id,
                generatedCode,
                "Pump monthly PM",
                "Template description",
                equipmentTypeId,
                MaintenanceKind.PREVENTIVE,
                4.5,
                true,
                List.of()
        );
        when(service.create(any())).thenReturn(dto);

        mockMvc.perform(post("/api/v1/maintenance-templates")
                        .contentType("application/json")
                        .content("""
                                {
                                  "name": "Pump monthly PM",
                                  "description": "Template description",
                                  "equipmentTypeId": "%s",
                                  "maintenanceKind": "PREVENTIVE",
                                  "normativeLaborHours": 4.5,
                                  "active": true
                                }
                                """.formatted(equipmentTypeId)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").value(id.toString()))
                .andExpect(jsonPath("$.code").value(generatedCode));
    }

    @Test
    void createWithCodeReturnsBadRequest() throws Exception {
        UUID equipmentTypeId = UUID.randomUUID();
        when(service.create(any())).thenThrow(RestException.badRequest(
                "code is generated by backend and must not be provided"));

        mockMvc.perform(post("/api/v1/maintenance-templates")
                        .contentType("application/json")
                        .content("""
                                {
                                  "code": "MT-2026-0099",
                                  "name": "Pump monthly PM",
                                  "description": "Template description",
                                  "equipmentTypeId": "%s",
                                  "maintenanceKind": "PREVENTIVE",
                                  "normativeLaborHours": 4.5,
                                  "active": true
                                }
                                """.formatted(equipmentTypeId)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message")
                        .value("code is generated by backend and must not be provided"));
    }

    @Test
    void updateWithCodeReturnsBadRequest() throws Exception {
        UUID id = UUID.randomUUID();
        UUID equipmentTypeId = UUID.randomUUID();
        when(service.update(eq(id), any())).thenThrow(RestException.badRequest(
                "code is generated by backend and must not be provided"));

        mockMvc.perform(put("/api/v1/maintenance-templates/{id}", id)
                        .contentType("application/json")
                        .content("""
                                {
                                  "code": "MT-2026-0012",
                                  "name": "Pump monthly PM",
                                  "description": "Template description",
                                  "equipmentTypeId": "%s",
                                  "maintenanceKind": "PREVENTIVE",
                                  "normativeLaborHours": 4.5,
                                  "active": true
                                }
                                """.formatted(equipmentTypeId)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message")
                        .value("code is generated by backend and must not be provided"));
    }
}
