package com.toir.controller;

import com.toir.dto.pprplanning.PprTaskDto;
import com.toir.enums.PprTaskStatus;
import com.toir.enums.PriorityLevel;
import com.toir.exception.GlobalExceptionHandler;
import com.toir.exception.RestException;
import com.toir.service.PprGeneratorService;
import com.toir.service.PprPlanService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.time.LocalDateTime;
import java.time.Year;
import java.util.UUID;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@ExtendWith(MockitoExtension.class)
class PprPlanControllerContractTest {

    @Mock
    PprPlanService service;

    @Mock
    PprGeneratorService generatorService;

    private MockMvc mockMvc;

    @BeforeEach
    void setUp() {
        mockMvc = MockMvcBuilders.standaloneSetup(new PprPlanController(service, generatorService))
                .setControllerAdvice(new GlobalExceptionHandler())
                .build();
    }

    @Test
    void createTaskWithoutCodeReturnsGeneratedCode() throws Exception {
        UUID planId = UUID.randomUUID();
        UUID taskId = UUID.randomUUID();
        UUID regulationId = UUID.randomUUID();
        UUID equipmentId = UUID.randomUUID();
        LocalDateTime start = LocalDateTime.of(2026, 6, 1, 9, 0);
        String generatedCode = "PPR-TASK-" + Year.now().getValue() + "-0001";
        PprTaskDto dto = new PprTaskDto(
                taskId,
                generatedCode,
                planId,
                regulationId,
                equipmentId,
                "Manual PPR task",
                start,
                start.plusHours(2),
                start.plusDays(1),
                PprTaskStatus.PLANNED,
                PriorityLevel.MEDIUM,
                2.0,
                null,
                null
        );
        when(service.addTask(eq(planId), any())).thenReturn(dto);

        mockMvc.perform(post("/api/v1/ppr-plans/{id}/tasks", planId)
                        .contentType("application/json")
                        .content("""
                                {
                                  "regulationId": "%s",
                                  "equipmentId": "%s",
                                  "title": "Manual PPR task",
                                  "scheduledStart": "2026-06-01T09:00:00",
                                  "scheduledEnd": "2026-06-01T11:00:00",
                                  "dueDate": "2026-06-02T09:00:00",
                                  "priority": "MEDIUM",
                                  "plannedLaborHours": 2.0
                                }
                                """.formatted(regulationId, equipmentId)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").value(taskId.toString()))
                .andExpect(jsonPath("$.code").value(generatedCode));
    }

    @Test
    void createTaskWithCodeReturnsBadRequest() throws Exception {
        UUID planId = UUID.randomUUID();
        UUID regulationId = UUID.randomUUID();
        UUID equipmentId = UUID.randomUUID();
        when(service.addTask(eq(planId), any())).thenThrow(RestException.badRequest(
                "code is generated by backend and must not be provided"));

        mockMvc.perform(post("/api/v1/ppr-plans/{id}/tasks", planId)
                        .contentType("application/json")
                        .content("""
                                {
                                  "code": "PPR-TASK-2026-0099",
                                  "regulationId": "%s",
                                  "equipmentId": "%s",
                                  "title": "Manual PPR task",
                                  "scheduledStart": "2026-06-01T09:00:00",
                                  "scheduledEnd": "2026-06-01T11:00:00",
                                  "dueDate": "2026-06-02T09:00:00",
                                  "priority": "MEDIUM",
                                  "plannedLaborHours": 2.0
                                }
                                """.formatted(regulationId, equipmentId)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message")
                        .value("code is generated by backend and must not be provided"));
    }
}
