package com.toir.security;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class RolePermissionDefaults {

    private RolePermissionDefaults() {
    }

    private static final Map<String, List<String>> DEFAULTS = buildDefaults();

    public static List<String> forRole(String roleCode) {
        return DEFAULTS.getOrDefault(roleCode, List.of(PermissionConstants.READ_LEGACY));
    }

    public static boolean hasDefaults(String roleCode) {
        return DEFAULTS.containsKey(roleCode);
    }

    private static Map<String, List<String>> buildDefaults() {
        Map<String, List<String>> defaults = new LinkedHashMap<>();
        defaults.put("SYSTEM_ADMIN", List.of(PermissionConstants.WILDCARD));
        defaults.put("PPR_ENGINEER", List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.PPR_PLAN_READ,
                PermissionConstants.PPR_PLAN_CREATE,
                PermissionConstants.PPR_PLAN_UPDATE,
                PermissionConstants.PPR_PLAN_GENERATE,
                PermissionConstants.PPR_TASK_READ,
                PermissionConstants.PPR_TASK_CREATE,
                PermissionConstants.PPR_TASK_START,
                PermissionConstants.PPR_TASK_COMPLETE,
                PermissionConstants.PPR_TASK_POSTPONE,
                PermissionConstants.EQUIPMENT_READ,
                PermissionConstants.METER_READ,
                PermissionConstants.METER_READING_CREATE,
                PermissionConstants.CALIBRATION_RECORD_READ,
                PermissionConstants.CALIBRATION_RECORD_CREATE,
                PermissionConstants.CALIBRATION_RECORD_UPDATE,
                PermissionConstants.WORK_ORDER_READ,
                PermissionConstants.REPAIR_REQUEST_READ,
                PermissionConstants.TIMESHEET_CREATE,
                PermissionConstants.KNOWLEDGE_READ
        ));
        defaults.put("RELIABILITY_ENGINEER", List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.EQUIPMENT_READ,
                PermissionConstants.EQUIPMENT_UPDATE,
                PermissionConstants.METER_READ,
                PermissionConstants.METER_CREATE,
                PermissionConstants.METER_UPDATE,
                PermissionConstants.METER_READING_CREATE,
                PermissionConstants.CALIBRATION_RECORD_READ,
                PermissionConstants.CALIBRATION_RECORD_CREATE,
                PermissionConstants.CALIBRATION_RECORD_UPDATE,
                PermissionConstants.DEFECT_READ,
                PermissionConstants.DEFECT_CREATE,
                PermissionConstants.DEFECT_UPDATE,
                PermissionConstants.DEFECT_RESOLVE,
                PermissionConstants.DEFECT_LIST_READ,
                PermissionConstants.KNOWLEDGE_READ,
                PermissionConstants.KNOWLEDGE_CREATE,
                PermissionConstants.KNOWLEDGE_UPDATE,
                PermissionConstants.ANALYTICS_READ,
                PermissionConstants.ANALYTICS_EXPORT,
                PermissionConstants.WORK_ORDER_READ,
                PermissionConstants.REPAIR_REQUEST_READ
        ));
        defaults.put("FOREMAN", List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.REPAIR_REQUEST_READ,
                PermissionConstants.REPAIR_REQUEST_UPDATE,
                PermissionConstants.REPAIR_REQUEST_APPROVE,
                PermissionConstants.REPAIR_REQUEST_ASSIGN,
                PermissionConstants.REPAIR_REQUEST_REJECT,
                PermissionConstants.REPAIR_REQUEST_CLOSE,
                PermissionConstants.WORK_ORDER_READ,
                PermissionConstants.WORK_ORDER_CREATE,
                PermissionConstants.WORK_ORDER_UPDATE,
                PermissionConstants.WORK_ORDER_APPROVE,
                PermissionConstants.WORK_ORDER_START,
                PermissionConstants.WORK_ORDER_COMPLETE,
                PermissionConstants.WORK_ORDER_CLOSE,
                PermissionConstants.DEFECT_READ,
                PermissionConstants.DEFECT_CREATE,
                PermissionConstants.DEFECT_UPDATE,
                PermissionConstants.DEFECT_RESOLVE,
                PermissionConstants.DEFECT_LIST_READ,
                PermissionConstants.DEFECT_LIST_CREATE,
                PermissionConstants.DEFECT_LIST_UPDATE,
                PermissionConstants.DEFECT_LIST_APPROVE,
                PermissionConstants.DEFECT_LIST_CLOSE,
                PermissionConstants.EQUIPMENT_READ,
                PermissionConstants.METER_READ,
                PermissionConstants.METER_READING_CREATE,
                PermissionConstants.CALIBRATION_RECORD_READ,
                PermissionConstants.CALIBRATION_RECORD_CREATE,
                PermissionConstants.CALIBRATION_RECORD_UPDATE,
                PermissionConstants.EMPLOYEE_READ,
                PermissionConstants.TIMESHEET_READ,
                PermissionConstants.TIMESHEET_CREATE,
                PermissionConstants.TIMESHEET_UPDATE,
                PermissionConstants.TIMESHEET_DELETE,
                PermissionConstants.TIMESHEET_APPROVE,
                PermissionConstants.KNOWLEDGE_READ,
                PermissionConstants.ANALYTICS_READ,
                PermissionConstants.NOTIFICATION_READ,
                PermissionConstants.NOTIFICATION_MARK_READ
        ));
        defaults.put("TECHNICIAN", List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.REPAIR_REQUEST_READ,
                PermissionConstants.WORK_ORDER_READ,
                PermissionConstants.WORK_ORDER_UPDATE,
                PermissionConstants.WORK_ORDER_START,
                PermissionConstants.WORK_ORDER_COMPLETE,
                PermissionConstants.EQUIPMENT_READ,
                PermissionConstants.DEFECT_READ,
                PermissionConstants.PPR_TASK_READ,
                PermissionConstants.INSPECTION_READ,
                PermissionConstants.INSPECTION_START,
                PermissionConstants.INSPECTION_COMPLETE,
                PermissionConstants.TIMESHEET_CREATE,
                PermissionConstants.KNOWLEDGE_READ,
                PermissionConstants.NOTIFICATION_READ,
                PermissionConstants.NOTIFICATION_MARK_READ
        ));
        defaults.put("TECHNICAL_DIRECTOR", List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.EQUIPMENT_READ,
                PermissionConstants.EQUIPMENT_CREATE,
                PermissionConstants.EQUIPMENT_UPDATE,
                PermissionConstants.EQUIPMENT_TRANSFER,
                PermissionConstants.METER_READ,
                PermissionConstants.METER_CREATE,
                PermissionConstants.METER_UPDATE,
                PermissionConstants.METER_DELETE,
                PermissionConstants.METER_READING_CREATE,
                PermissionConstants.METER_READING_DELETE,
                PermissionConstants.CALIBRATION_RECORD_READ,
                PermissionConstants.CALIBRATION_RECORD_CREATE,
                PermissionConstants.CALIBRATION_RECORD_UPDATE,
                PermissionConstants.CALIBRATION_RECORD_DELETE,
                PermissionConstants.REPAIR_REQUEST_READ,
                PermissionConstants.REPAIR_REQUEST_UPDATE,
                PermissionConstants.REPAIR_REQUEST_APPROVE,
                PermissionConstants.REPAIR_REQUEST_ASSIGN,
                PermissionConstants.REPAIR_REQUEST_REJECT,
                PermissionConstants.REPAIR_REQUEST_CLOSE,
                PermissionConstants.WORK_ORDER_READ,
                PermissionConstants.WORK_ORDER_CREATE,
                PermissionConstants.WORK_ORDER_UPDATE,
                PermissionConstants.WORK_ORDER_APPROVE,
                PermissionConstants.WORK_ORDER_START,
                PermissionConstants.WORK_ORDER_COMPLETE,
                PermissionConstants.WORK_ORDER_CLOSE,
                PermissionConstants.DEFECT_READ,
                PermissionConstants.DEFECT_CREATE,
                PermissionConstants.DEFECT_UPDATE,
                PermissionConstants.DEFECT_RESOLVE,
                PermissionConstants.DEFECT_LIST_READ,
                PermissionConstants.DEFECT_LIST_CREATE,
                PermissionConstants.DEFECT_LIST_UPDATE,
                PermissionConstants.DEFECT_LIST_APPROVE,
                PermissionConstants.DEFECT_LIST_CLOSE,
                PermissionConstants.PPR_PLAN_READ,
                PermissionConstants.PPR_PLAN_CREATE,
                PermissionConstants.PPR_PLAN_UPDATE,
                PermissionConstants.PPR_PLAN_APPROVE,
                PermissionConstants.PPR_PLAN_GENERATE,
                PermissionConstants.PPR_TASK_READ,
                PermissionConstants.PPR_TASK_CREATE,
                PermissionConstants.PPR_TASK_APPROVE,
                PermissionConstants.PPR_TASK_START,
                PermissionConstants.PPR_TASK_COMPLETE,
                PermissionConstants.PPR_TASK_POSTPONE,
                PermissionConstants.INSPECTION_READ,
                PermissionConstants.INSPECTION_CREATE,
                PermissionConstants.INSPECTION_UPDATE,
                PermissionConstants.INSPECTION_START,
                PermissionConstants.INSPECTION_COMPLETE,
                PermissionConstants.KNOWLEDGE_READ,
                PermissionConstants.KNOWLEDGE_CREATE,
                PermissionConstants.KNOWLEDGE_UPDATE,
                PermissionConstants.ANALYTICS_READ,
                PermissionConstants.ANALYTICS_EXPORT,
                PermissionConstants.NOTIFICATION_READ,
                PermissionConstants.NOTIFICATION_MARK_READ,
                PermissionConstants.NOTIFICATION_ADMIN
        ));
        List<String> chiefMaintenancePermissions = List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.REPAIR_REQUEST_READ,
                PermissionConstants.REPAIR_REQUEST_UPDATE,
                PermissionConstants.REPAIR_REQUEST_APPROVE,
                PermissionConstants.REPAIR_REQUEST_ASSIGN,
                PermissionConstants.REPAIR_REQUEST_REJECT,
                PermissionConstants.REPAIR_REQUEST_CLOSE,
                PermissionConstants.WORK_ORDER_READ,
                PermissionConstants.WORK_ORDER_CREATE,
                PermissionConstants.WORK_ORDER_UPDATE,
                PermissionConstants.WORK_ORDER_APPROVE,
                PermissionConstants.WORK_ORDER_START,
                PermissionConstants.WORK_ORDER_COMPLETE,
                PermissionConstants.WORK_ORDER_CLOSE,
                PermissionConstants.DEFECT_READ,
                PermissionConstants.DEFECT_CREATE,
                PermissionConstants.DEFECT_UPDATE,
                PermissionConstants.DEFECT_RESOLVE,
                PermissionConstants.DEFECT_LIST_READ,
                PermissionConstants.DEFECT_LIST_CREATE,
                PermissionConstants.DEFECT_LIST_UPDATE,
                PermissionConstants.DEFECT_LIST_APPROVE,
                PermissionConstants.DEFECT_LIST_CLOSE,
                PermissionConstants.EQUIPMENT_READ,
                PermissionConstants.METER_READ,
                PermissionConstants.METER_READING_CREATE,
                PermissionConstants.CALIBRATION_RECORD_READ,
                PermissionConstants.EMPLOYEE_READ,
                PermissionConstants.TIMESHEET_READ,
                PermissionConstants.TIMESHEET_APPROVE,
                PermissionConstants.KNOWLEDGE_READ,
                PermissionConstants.ANALYTICS_READ,
                PermissionConstants.PPR_PLAN_READ,
                PermissionConstants.PPR_TASK_READ,
                PermissionConstants.INSPECTION_READ,
                PermissionConstants.INSPECTION_START,
                PermissionConstants.INSPECTION_COMPLETE,
                PermissionConstants.NOTIFICATION_READ,
                PermissionConstants.NOTIFICATION_MARK_READ
        );
        defaults.put("CHIEF_MECHANIC", chiefMaintenancePermissions);
        defaults.put("CHIEF_POWER_ENGINEER", chiefMaintenancePermissions);
        defaults.put("CHIEF_INSTRUMENT_ENGINEER", chiefMaintenancePermissions);
        List<String> shopLeadPermissions = List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.EQUIPMENT_READ,
                PermissionConstants.METER_READ,
                PermissionConstants.METER_READING_CREATE,
                PermissionConstants.CALIBRATION_RECORD_READ,
                PermissionConstants.CALIBRATION_RECORD_CREATE,
                PermissionConstants.CALIBRATION_RECORD_UPDATE,
                PermissionConstants.REPAIR_REQUEST_READ,
                PermissionConstants.REPAIR_REQUEST_UPDATE,
                PermissionConstants.REPAIR_REQUEST_APPROVE,
                PermissionConstants.REPAIR_REQUEST_ASSIGN,
                PermissionConstants.WORK_ORDER_READ,
                PermissionConstants.WORK_ORDER_UPDATE,
                PermissionConstants.WORK_ORDER_APPROVE,
                PermissionConstants.WORK_ORDER_START,
                PermissionConstants.WORK_ORDER_COMPLETE,
                PermissionConstants.DEFECT_READ,
                PermissionConstants.DEFECT_CREATE,
                PermissionConstants.DEFECT_UPDATE,
                PermissionConstants.DEFECT_LIST_READ,
                PermissionConstants.DEFECT_LIST_APPROVE,
                PermissionConstants.PPR_PLAN_READ,
                PermissionConstants.PPR_TASK_READ,
                PermissionConstants.EMPLOYEE_READ,
                PermissionConstants.TIMESHEET_READ,
                PermissionConstants.TIMESHEET_APPROVE,
                PermissionConstants.ANALYTICS_READ,
                PermissionConstants.KNOWLEDGE_READ,
                PermissionConstants.NOTIFICATION_READ,
                PermissionConstants.NOTIFICATION_MARK_READ
        );
        defaults.put("WORKSHOP_HEAD", shopLeadPermissions);
        defaults.put("SECTION_HEAD", shopLeadPermissions);
        defaults.put("DEPARTMENT_HEAD", List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.EQUIPMENT_READ,
                PermissionConstants.METER_READ,
                PermissionConstants.METER_READING_CREATE,
                PermissionConstants.MAINTENANCE_REGULATION_READ,
                PermissionConstants.MAINTENANCE_EVENT_READ,
                PermissionConstants.MAINTENANCE_EVENT_APPROVE,
                PermissionConstants.MAINTENANCE_EVENT_CANCEL,
                PermissionConstants.MAINTENANCE_AUTOMATION_RUN,
                PermissionConstants.PPR_PLAN_READ,
                PermissionConstants.PPR_TASK_READ,
                PermissionConstants.PPR_TASK_APPROVE,
                PermissionConstants.WORK_ORDER_READ,
                PermissionConstants.WORK_ORDER_CREATE,
                PermissionConstants.WORK_ORDER_UPDATE,
                PermissionConstants.WORK_ORDER_APPROVE,
                PermissionConstants.WORK_ORDER_START,
                PermissionConstants.WORK_ORDER_COMPLETE,
                PermissionConstants.NOTIFICATION_READ,
                PermissionConstants.NOTIFICATION_MARK_READ,
                PermissionConstants.OPERATIONAL_ISSUE_READ,
                PermissionConstants.OPERATIONAL_ISSUE_RESOLVE
        ));
        defaults.put("STOREKEEPER", List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.WAREHOUSE_READ,
                PermissionConstants.WAREHOUSE_EQUIPMENT_READ,
                PermissionConstants.WAREHOUSE_EQUIPMENT_STATUS_UPDATE,
                PermissionConstants.STOCK_READ,
                PermissionConstants.STOCK_RECEIVE,
                PermissionConstants.STOCK_ISSUE,
                PermissionConstants.STOCK_MOVE,
                PermissionConstants.INVENTORY_READ,
                PermissionConstants.INVENTORY_RECEIPT,
                PermissionConstants.INVENTORY_ISSUE,
                PermissionConstants.MATERIAL_USAGE_READ,
                PermissionConstants.MATERIAL_USAGE_ISSUE,
                PermissionConstants.SPARE_PART_READ,
                PermissionConstants.SPARE_PART_CREATE,
                PermissionConstants.SPARE_PART_UPDATE,
                PermissionConstants.WORK_ORDER_READ,
                PermissionConstants.EQUIPMENT_READ,
                PermissionConstants.METER_READ,
                PermissionConstants.CALIBRATION_RECORD_READ,
                PermissionConstants.PROCUREMENT_READ
        ));
        defaults.put("SUPPLY_SPECIALIST", List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.PROCUREMENT_READ,
                PermissionConstants.PROCUREMENT_CREATE,
                PermissionConstants.PROCUREMENT_SUBMIT,
                PermissionConstants.PROCUREMENT_ORDER,
                PermissionConstants.PROCUREMENT_RECEIVE,
                PermissionConstants.PROCUREMENT_CANCEL,
                PermissionConstants.WAREHOUSE_READ,
                PermissionConstants.STOCK_READ,
                PermissionConstants.INVENTORY_READ,
                PermissionConstants.INVENTORY_RECEIPT,
                PermissionConstants.SPARE_PART_READ,
                PermissionConstants.SPARE_PART_CREATE,
                PermissionConstants.SPARE_PART_UPDATE,
                PermissionConstants.ANALYTICS_READ
        ));
        defaults.put("ECONOMIST", List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.ACTUAL_COST_READ,
                PermissionConstants.ACTUAL_COST_CREATE,
                PermissionConstants.BUDGET_READ,
                PermissionConstants.BUDGET_CREATE,
                PermissionConstants.BUDGET_UPDATE,
                PermissionConstants.ANALYTICS_READ,
                PermissionConstants.ANALYTICS_EXPORT,
                PermissionConstants.APPROVAL_READ,
                PermissionConstants.APPROVAL_CREATE
        ));
        defaults.put("FINANCE_MANAGER", List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.ACTUAL_COST_READ,
                PermissionConstants.ACTUAL_COST_CREATE,
                PermissionConstants.ACTUAL_COST_APPROVE,
                PermissionConstants.ACTUAL_COST_REJECT,
                PermissionConstants.BUDGET_READ,
                PermissionConstants.BUDGET_CREATE,
                PermissionConstants.BUDGET_UPDATE,
                PermissionConstants.BUDGET_APPROVE,
                PermissionConstants.FINANCE_ROUTE_OVERRIDE_READ,
                PermissionConstants.FINANCE_ROUTE_OVERRIDE_APPLY,
                PermissionConstants.FINANCE_ROUTE_OVERRIDE_CLEAR,
                PermissionConstants.ANALYTICS_READ,
                PermissionConstants.ANALYTICS_EXPORT,
                PermissionConstants.APPROVAL_READ,
                PermissionConstants.APPROVAL_UPDATE,
                PermissionConstants.APPROVAL_APPROVE,
                PermissionConstants.APPROVAL_REJECT,
                PermissionConstants.APPROVAL_RETURN
        ));
        defaults.put("VIEWER", List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.EQUIPMENT_READ,
                PermissionConstants.REPAIR_REQUEST_READ,
                PermissionConstants.WORK_ORDER_READ,
                PermissionConstants.DEFECT_READ,
                PermissionConstants.DEFECT_LIST_READ,
                PermissionConstants.PPR_PLAN_READ,
                PermissionConstants.PPR_TASK_READ,
                PermissionConstants.METER_READ,
                PermissionConstants.CALIBRATION_RECORD_READ,
                PermissionConstants.WAREHOUSE_READ,
                PermissionConstants.STOCK_READ,
                PermissionConstants.INVENTORY_READ,
                PermissionConstants.SPARE_PART_READ,
                PermissionConstants.PROCUREMENT_READ,
                PermissionConstants.BUDGET_READ,
                PermissionConstants.ACTUAL_COST_READ,
                PermissionConstants.APPROVAL_READ,
                PermissionConstants.INSPECTION_READ,
                PermissionConstants.KNOWLEDGE_READ,
                PermissionConstants.ANALYTICS_READ,
                PermissionConstants.DEPARTMENT_READ,
                PermissionConstants.BRIGADE_READ,
                PermissionConstants.LOCATION_READ,
                PermissionConstants.EQUIPMENT_TYPE_READ,
                PermissionConstants.CATEGORY_READ
        ));
        defaults.put("CONTRACTOR", List.of(PermissionConstants.READ_LEGACY));
        List<String> performerPermissions = List.of(
                PermissionConstants.READ_LEGACY,
                PermissionConstants.REPAIR_REQUEST_READ,
                PermissionConstants.NOTIFICATION_READ,
                PermissionConstants.NOTIFICATION_MARK_READ,
                PermissionConstants.WORK_ORDER_READ,
                PermissionConstants.WORK_ORDER_UPDATE,
                PermissionConstants.WORK_ORDER_START,
                PermissionConstants.WORK_ORDER_COMPLETE,
                PermissionConstants.EQUIPMENT_READ,
                PermissionConstants.KNOWLEDGE_READ
        );
        defaults.put("TECHNICIAN", performerPermissions);
        defaults.put("MECHANIC", performerPermissions);
        return Map.copyOf(defaults);
    }
}
