package com.toir.dto.rcm;

public enum RiskReasonCode {
    OPEN_DEFECTS_CRITICAL,
    OPEN_DEFECTS_HIGH,
    OPEN_DEFECTS_MEDIUM,
    LOW_MTBF_HIGH,
    LOW_MTBF_MEDIUM,
    RECURRING_DEFECTS,
    OVERDUE_MAINTENANCE,
    BASELINE_PROBABILITY,
    CRITICAL_EQUIPMENT,
    HIGH_CRITICALITY,
    MEDIUM_CRITICALITY,
    LOW_CRITICALITY,
    RECENT_DOWNTIME,
    HIGH_MTTR,
    OPEN_HIGH_REPAIR_REQUEST,
    EQUIPMENT_UNAVAILABLE,
    INSPECTION_OR_CALIBRATION_ISSUE
}
