package com.toir.enums;

public enum ActualCostSourceType {
    WORK_ORDER,
    REPAIR_REQUEST,
    COUNTERAGENT_WORK,
    CONTRACTOR_WORK,
    MATERIAL_ISSUE,
    LABOR_ENTRY,
    PROCUREMENT_RECEIPT,
    WORK_ORDER_MANUAL_WITH_REASON
}
