package com.toir.enums;

public enum DocumentType {
    PASSPORT,
    MANUAL,
    DRAWING,
    CERTIFICATE,
    PHOTO,
    REPORT,
    ACT,
    INVOICE,
    DELIVERY_NOTE,
    WARRANTY,
    QUALITY_PASSPORT,
    DISCREPANCY_ACT,
    MATERIAL_ISSUE_SLIP,
    PICK_LIST,
    SIGNED_HANDOVER_ACT,
    MATERIAL_RETURN_ACT,
    COUNT_SHEET,
    VARIANCE_ACT,
    APPROVAL_PROTOCOL,
    WRITEOFF_ACT,
    COMMISSION_DECISION,
    OTHER
}
