package com.toir.enums;

public enum OperationalIssueType {
    OVERDUE_WORK_ORDER,
    OVERDUE_PPR_TASK,
    MAINTENANCE_DUE,
    MAINTENANCE_OVERDUE,
    EQUIPMENT_LIFETIME_WARNING,
    EQUIPMENT_LIFETIME_EXPIRED,
    MISSING_METERS,
    AUTOMATION_FAILURE,
    BLOCKED_PPR_GENERATION,
    OVERDUE_REPAIR_REQUEST,
    OVERDUE_CALIBRATION,
    CONTRACTOR_WORK_DELAY,
    BUDGET_REVIEW_ISSUE,
    APPROVAL_ESCALATION,
    INSPECTION_DEFECT
}
