package com.toir.enums;

public enum OperationalIssueType {
    OVERDUE_WORK_ORDER,
    MAINTENANCE_DUE,
    MAINTENANCE_OVERDUE,
    EQUIPMENT_LIFETIME_EXPIRING,
    EQUIPMENT_LIFETIME_EXPIRED,
    MISSING_METERS,
    AUTOMATION_FAILURE,
    BLOCKED_PPR_GENERATION
}
