package com.toir.enums;

public enum StockMovementSourceType {
    MANUAL,
    PROCUREMENT_REQUEST,
    PURCHASE_ORDER,
    WORK_ORDER_MATERIAL_USAGE,
    INVENTORY_TRANSACTION,
    RESERVATION,
    EQUIPMENT_COMMISSIONING,
    WAREHOUSE_TASK,
    INVENTORY_COUNT_SESSION,
    REPAIR_MATERIAL_RETURN,
    WAREHOUSE_WRITEOFF,
    QUALITY_STATUS_TRANSFER
}
