package com.toir.enums;

public enum StockMovementSourceType {
    MANUAL,
    PROCUREMENT_REQUEST,
    PURCHASE_ORDER,
    WORK_ORDER_MATERIAL_USAGE,
    INVENTORY_TRANSACTION,
    RESERVATION,
    EQUIPMENT_COMMISSIONING,
    REPAIR_MATERIAL_RETURN,
    QUALITY_STATUS_TRANSFER
}
