CREATE OR REPLACE FUNCTION append_role_permissions(role_code text, permissions_to_add text[])
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE roles r
    SET permissions = (
            SELECT COALESCE(jsonb_agg(DISTINCT permission), '[]'::jsonb)
            FROM (
                SELECT jsonb_array_elements_text(
                        CASE
                            WHEN jsonb_typeof(COALESCE(r.permissions, '[]'::jsonb)) = 'array'
                                THEN COALESCE(r.permissions, '[]'::jsonb)
                            ELSE '[]'::jsonb
                        END
                    ) AS permission
                UNION ALL
                SELECT unnest(permissions_to_add) AS permission
            ) merged_permissions
            WHERE permission IS NOT NULL AND btrim(permission) <> ''
        ),
        updated_at = now()
    WHERE r.code = role_code
      AND r.is_deleted = false;
END;
$$;

SELECT append_role_permissions('SYSTEM_ADMIN', ARRAY[
    'PLANNED_SHUTDOWN_READ', 'PLANNED_SHUTDOWN_CREATE', 'PLANNED_SHUTDOWN_UPDATE',
    'PLANNED_SHUTDOWN_APPROVE', 'PLANNED_SHUTDOWN_PREPARE', 'PLANNED_SHUTDOWN_CONFIRM_SAFE_STATE',
    'PLANNED_SHUTDOWN_START_REPAIR', 'PLANNED_SHUTDOWN_TEST', 'PLANNED_SHUTDOWN_STARTUP',
    'PLANNED_SHUTDOWN_CLOSE', 'PLANNED_SHUTDOWN_CANCEL', 'PLANNED_SHUTDOWN_RESCHEDULE',
    'PLANNED_SHUTDOWN_EXTEND', 'REPAIR_CAMPAIGN_READ', 'REPAIR_CAMPAIGN_CREATE',
    'REPAIR_CAMPAIGN_UPDATE', 'REPAIR_CAMPAIGN_APPROVE', 'REPAIR_CAMPAIGN_START',
    'REPAIR_CAMPAIGN_SUSPEND', 'REPAIR_CAMPAIGN_COMPLETE', 'REPAIR_CAMPAIGN_CLOSE',
    'REPAIR_CAMPAIGN_CANCEL', 'REPAIR_CAMPAIGN_GENERATE_WORK_ORDERS'
]);

SELECT append_role_permissions('MAINTENANCE_MANAGER', ARRAY[
    'PLANNED_SHUTDOWN_READ', 'PLANNED_SHUTDOWN_CREATE', 'PLANNED_SHUTDOWN_UPDATE',
    'PLANNED_SHUTDOWN_APPROVE', 'PLANNED_SHUTDOWN_PREPARE', 'PLANNED_SHUTDOWN_CONFIRM_SAFE_STATE',
    'PLANNED_SHUTDOWN_START_REPAIR', 'PLANNED_SHUTDOWN_TEST', 'PLANNED_SHUTDOWN_STARTUP',
    'PLANNED_SHUTDOWN_CLOSE', 'PLANNED_SHUTDOWN_CANCEL', 'PLANNED_SHUTDOWN_RESCHEDULE',
    'PLANNED_SHUTDOWN_EXTEND', 'REPAIR_CAMPAIGN_READ', 'REPAIR_CAMPAIGN_CREATE',
    'REPAIR_CAMPAIGN_UPDATE', 'REPAIR_CAMPAIGN_APPROVE', 'REPAIR_CAMPAIGN_START',
    'REPAIR_CAMPAIGN_SUSPEND', 'REPAIR_CAMPAIGN_COMPLETE', 'REPAIR_CAMPAIGN_CLOSE',
    'REPAIR_CAMPAIGN_CANCEL', 'REPAIR_CAMPAIGN_GENERATE_WORK_ORDERS'
]);

SELECT append_role_permissions('MAINTENANCE_ENGINEER', ARRAY[
    'PLANNED_SHUTDOWN_READ', 'PLANNED_SHUTDOWN_UPDATE', 'PLANNED_SHUTDOWN_PREPARE',
    'PLANNED_SHUTDOWN_CONFIRM_SAFE_STATE', 'PLANNED_SHUTDOWN_START_REPAIR',
    'PLANNED_SHUTDOWN_TEST', 'PLANNED_SHUTDOWN_STARTUP', 'REPAIR_CAMPAIGN_READ',
    'REPAIR_CAMPAIGN_UPDATE'
]);

DROP FUNCTION append_role_permissions(text, text[]);
