CREATE OR REPLACE FUNCTION append_role_permissions(role_code text, permissions_to_add text[])
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE roles r
    SET permissions = (
            SELECT COALESCE(jsonb_agg(DISTINCT permission), '[]'::jsonb)
            FROM (
                SELECT jsonb_array_elements_text(
                        CASE
                            WHEN jsonb_typeof(COALESCE(r.permissions, '[]'::jsonb)) = 'array'
                                THEN COALESCE(r.permissions, '[]'::jsonb)
                            ELSE '[]'::jsonb
                        END
                    ) AS permission
                UNION ALL
                SELECT unnest(permissions_to_add) AS permission
            ) merged_permissions
            WHERE permission IS NOT NULL AND btrim(permission) <> ''
        ),
        updated_at = now()
    WHERE r.code = role_code
      AND r.is_deleted = false;
END;
$$;

SELECT append_role_permissions('SYSTEM_ADMIN', ARRAY['*']);

SELECT append_role_permissions('PPR_ENGINEER', ARRAY[
    'PPR_PLAN_READ',
    'PPR_PLAN_CREATE',
    'PPR_PLAN_UPDATE',
    'PPR_PLAN_GENERATE',
    'PPR_TASK_READ',
    'PPR_TASK_CREATE',
    'PPR_TASK_START',
    'PPR_TASK_COMPLETE',
    'PPR_TASK_POSTPONE',
    'EQUIPMENT_READ',
    'WORK_ORDER_READ',
    'REPAIR_REQUEST_READ',
    'KNOWLEDGE_READ'
]);

SELECT append_role_permissions('RELIABILITY_ENGINEER', ARRAY[
    'EQUIPMENT_READ',
    'EQUIPMENT_UPDATE',
    'DEFECT_READ',
    'DEFECT_CREATE',
    'DEFECT_UPDATE',
    'DEFECT_RESOLVE',
    'DEFECT_LIST_READ',
    'KNOWLEDGE_READ',
    'KNOWLEDGE_CREATE',
    'KNOWLEDGE_UPDATE',
    'ANALYTICS_READ',
    'ANALYTICS_EXPORT',
    'WORK_ORDER_READ',
    'REPAIR_REQUEST_READ'
]);

SELECT append_role_permissions('FOREMAN', ARRAY[
    'REPAIR_REQUEST_READ',
    'REPAIR_REQUEST_UPDATE',
    'REPAIR_REQUEST_APPROVE',
    'REPAIR_REQUEST_ASSIGN',
    'REPAIR_REQUEST_REJECT',
    'REPAIR_REQUEST_CLOSE',
    'WORK_ORDER_READ',
    'WORK_ORDER_CREATE',
    'WORK_ORDER_APPROVE',
    'WORK_ORDER_START',
    'WORK_ORDER_COMPLETE',
    'WORK_ORDER_CLOSE',
    'DEFECT_READ',
    'DEFECT_CREATE',
    'DEFECT_UPDATE',
    'DEFECT_RESOLVE',
    'DEFECT_LIST_READ',
    'DEFECT_LIST_CREATE',
    'DEFECT_LIST_UPDATE',
    'DEFECT_LIST_APPROVE',
    'DEFECT_LIST_CLOSE',
    'EQUIPMENT_READ',
    'EMPLOYEE_READ',
    'TIMESHEET_READ',
    'TIMESHEET_APPROVE',
    'KNOWLEDGE_READ',
    'ANALYTICS_READ'
]);

SELECT append_role_permissions('TECHNICAL_DIRECTOR', ARRAY[
    'EQUIPMENT_READ',
    'EQUIPMENT_CREATE',
    'EQUIPMENT_UPDATE',
    'EQUIPMENT_TRANSFER',
    'REPAIR_REQUEST_READ',
    'REPAIR_REQUEST_UPDATE',
    'REPAIR_REQUEST_APPROVE',
    'REPAIR_REQUEST_ASSIGN',
    'REPAIR_REQUEST_REJECT',
    'REPAIR_REQUEST_CLOSE',
    'WORK_ORDER_READ',
    'WORK_ORDER_CREATE',
    'WORK_ORDER_APPROVE',
    'WORK_ORDER_START',
    'WORK_ORDER_COMPLETE',
    'WORK_ORDER_CLOSE',
    'DEFECT_READ',
    'DEFECT_CREATE',
    'DEFECT_UPDATE',
    'DEFECT_RESOLVE',
    'DEFECT_LIST_READ',
    'DEFECT_LIST_CREATE',
    'DEFECT_LIST_UPDATE',
    'DEFECT_LIST_APPROVE',
    'DEFECT_LIST_CLOSE',
    'PPR_PLAN_READ',
    'PPR_PLAN_CREATE',
    'PPR_PLAN_UPDATE',
    'PPR_PLAN_APPROVE',
    'PPR_PLAN_GENERATE',
    'PPR_TASK_READ',
    'PPR_TASK_CREATE',
    'PPR_TASK_APPROVE',
    'PPR_TASK_START',
    'PPR_TASK_COMPLETE',
    'PPR_TASK_POSTPONE',
    'INSPECTION_READ',
    'INSPECTION_CREATE',
    'INSPECTION_UPDATE',
    'INSPECTION_START',
    'INSPECTION_COMPLETE',
    'KNOWLEDGE_READ',
    'KNOWLEDGE_CREATE',
    'KNOWLEDGE_UPDATE',
    'ANALYTICS_READ',
    'ANALYTICS_EXPORT'
]);

SELECT append_role_permissions('CHIEF_MECHANIC', ARRAY[
    'REPAIR_REQUEST_READ',
    'REPAIR_REQUEST_UPDATE',
    'REPAIR_REQUEST_APPROVE',
    'REPAIR_REQUEST_ASSIGN',
    'REPAIR_REQUEST_REJECT',
    'REPAIR_REQUEST_CLOSE',
    'WORK_ORDER_READ',
    'WORK_ORDER_CREATE',
    'WORK_ORDER_APPROVE',
    'WORK_ORDER_START',
    'WORK_ORDER_COMPLETE',
    'WORK_ORDER_CLOSE',
    'DEFECT_READ',
    'DEFECT_CREATE',
    'DEFECT_UPDATE',
    'DEFECT_RESOLVE',
    'DEFECT_LIST_READ',
    'DEFECT_LIST_CREATE',
    'DEFECT_LIST_UPDATE',
    'DEFECT_LIST_APPROVE',
    'DEFECT_LIST_CLOSE',
    'EQUIPMENT_READ',
    'EMPLOYEE_READ',
    'TIMESHEET_READ',
    'TIMESHEET_APPROVE',
    'KNOWLEDGE_READ',
    'ANALYTICS_READ',
    'PPR_PLAN_READ',
    'PPR_TASK_READ',
    'INSPECTION_READ',
    'INSPECTION_START',
    'INSPECTION_COMPLETE'
]);

SELECT append_role_permissions('CHIEF_POWER_ENGINEER', ARRAY[
    'REPAIR_REQUEST_READ',
    'REPAIR_REQUEST_UPDATE',
    'REPAIR_REQUEST_APPROVE',
    'REPAIR_REQUEST_ASSIGN',
    'REPAIR_REQUEST_REJECT',
    'REPAIR_REQUEST_CLOSE',
    'WORK_ORDER_READ',
    'WORK_ORDER_CREATE',
    'WORK_ORDER_APPROVE',
    'WORK_ORDER_START',
    'WORK_ORDER_COMPLETE',
    'WORK_ORDER_CLOSE',
    'DEFECT_READ',
    'DEFECT_CREATE',
    'DEFECT_UPDATE',
    'DEFECT_RESOLVE',
    'DEFECT_LIST_READ',
    'DEFECT_LIST_CREATE',
    'DEFECT_LIST_UPDATE',
    'DEFECT_LIST_APPROVE',
    'DEFECT_LIST_CLOSE',
    'EQUIPMENT_READ',
    'EMPLOYEE_READ',
    'TIMESHEET_READ',
    'TIMESHEET_APPROVE',
    'KNOWLEDGE_READ',
    'ANALYTICS_READ',
    'PPR_PLAN_READ',
    'PPR_TASK_READ',
    'INSPECTION_READ',
    'INSPECTION_START',
    'INSPECTION_COMPLETE'
]);

SELECT append_role_permissions('CHIEF_INSTRUMENT_ENGINEER', ARRAY[
    'REPAIR_REQUEST_READ',
    'REPAIR_REQUEST_UPDATE',
    'REPAIR_REQUEST_APPROVE',
    'REPAIR_REQUEST_ASSIGN',
    'REPAIR_REQUEST_REJECT',
    'REPAIR_REQUEST_CLOSE',
    'WORK_ORDER_READ',
    'WORK_ORDER_CREATE',
    'WORK_ORDER_APPROVE',
    'WORK_ORDER_START',
    'WORK_ORDER_COMPLETE',
    'WORK_ORDER_CLOSE',
    'DEFECT_READ',
    'DEFECT_CREATE',
    'DEFECT_UPDATE',
    'DEFECT_RESOLVE',
    'DEFECT_LIST_READ',
    'DEFECT_LIST_CREATE',
    'DEFECT_LIST_UPDATE',
    'DEFECT_LIST_APPROVE',
    'DEFECT_LIST_CLOSE',
    'EQUIPMENT_READ',
    'EMPLOYEE_READ',
    'TIMESHEET_READ',
    'TIMESHEET_APPROVE',
    'KNOWLEDGE_READ',
    'ANALYTICS_READ',
    'PPR_PLAN_READ',
    'PPR_TASK_READ',
    'INSPECTION_READ',
    'INSPECTION_START',
    'INSPECTION_COMPLETE'
]);

SELECT append_role_permissions('WORKSHOP_HEAD', ARRAY[
    'EQUIPMENT_READ',
    'REPAIR_REQUEST_READ',
    'REPAIR_REQUEST_UPDATE',
    'REPAIR_REQUEST_APPROVE',
    'REPAIR_REQUEST_ASSIGN',
    'WORK_ORDER_READ',
    'WORK_ORDER_APPROVE',
    'WORK_ORDER_START',
    'WORK_ORDER_COMPLETE',
    'DEFECT_READ',
    'DEFECT_CREATE',
    'DEFECT_UPDATE',
    'DEFECT_LIST_READ',
    'DEFECT_LIST_APPROVE',
    'PPR_PLAN_READ',
    'PPR_TASK_READ',
    'EMPLOYEE_READ',
    'TIMESHEET_READ',
    'TIMESHEET_APPROVE',
    'ANALYTICS_READ',
    'KNOWLEDGE_READ'
]);

SELECT append_role_permissions('SECTION_HEAD', ARRAY[
    'EQUIPMENT_READ',
    'REPAIR_REQUEST_READ',
    'REPAIR_REQUEST_UPDATE',
    'REPAIR_REQUEST_APPROVE',
    'REPAIR_REQUEST_ASSIGN',
    'WORK_ORDER_READ',
    'WORK_ORDER_APPROVE',
    'WORK_ORDER_START',
    'WORK_ORDER_COMPLETE',
    'DEFECT_READ',
    'DEFECT_CREATE',
    'DEFECT_UPDATE',
    'DEFECT_LIST_READ',
    'DEFECT_LIST_APPROVE',
    'PPR_PLAN_READ',
    'PPR_TASK_READ',
    'EMPLOYEE_READ',
    'TIMESHEET_READ',
    'TIMESHEET_APPROVE',
    'ANALYTICS_READ',
    'KNOWLEDGE_READ'
]);

SELECT append_role_permissions('STOREKEEPER', ARRAY[
    'WAREHOUSE_READ',
    'WAREHOUSE_EQUIPMENT_READ',
    'WAREHOUSE_EQUIPMENT_STATUS_UPDATE',
    'STOCK_READ',
    'STOCK_RECEIVE',
    'STOCK_ISSUE',
    'STOCK_MOVE',
    'MATERIAL_USAGE_READ',
    'MATERIAL_USAGE_ISSUE',
    'SPARE_PART_READ',
    'SPARE_PART_CREATE',
    'SPARE_PART_UPDATE',
    'WORK_ORDER_READ',
    'EQUIPMENT_READ',
    'PROCUREMENT_READ'
]);

SELECT append_role_permissions('SUPPLY_SPECIALIST', ARRAY[
    'PROCUREMENT_READ',
    'PROCUREMENT_CREATE',
    'PROCUREMENT_SUBMIT',
    'PROCUREMENT_ORDER',
    'PROCUREMENT_RECEIVE',
    'PROCUREMENT_CANCEL',
    'WAREHOUSE_READ',
    'STOCK_READ',
    'SPARE_PART_READ',
    'SPARE_PART_CREATE',
    'SPARE_PART_UPDATE',
    'ANALYTICS_READ'
]);

SELECT append_role_permissions('ECONOMIST', ARRAY[
    'ACTUAL_COST_READ',
    'ACTUAL_COST_CREATE',
    'BUDGET_READ',
    'BUDGET_CREATE',
    'BUDGET_UPDATE',
    'ANALYTICS_READ',
    'ANALYTICS_EXPORT',
    'APPROVAL_READ',
    'APPROVAL_CREATE'
]);

SELECT append_role_permissions('FINANCE_MANAGER', ARRAY[
    'ACTUAL_COST_READ',
    'ACTUAL_COST_CREATE',
    'ACTUAL_COST_APPROVE',
    'ACTUAL_COST_REJECT',
    'BUDGET_READ',
    'BUDGET_CREATE',
    'BUDGET_UPDATE',
    'BUDGET_APPROVE',
    'FINANCE_ROUTE_OVERRIDE_READ',
    'FINANCE_ROUTE_OVERRIDE_APPLY',
    'FINANCE_ROUTE_OVERRIDE_CLEAR',
    'ANALYTICS_READ',
    'ANALYTICS_EXPORT',
    'APPROVAL_READ',
    'APPROVAL_APPROVE',
    'APPROVAL_REJECT'
]);

SELECT append_role_permissions('INSPECTOR', ARRAY[
    'INSPECTION_READ',
    'INSPECTION_CREATE',
    'INSPECTION_UPDATE',
    'INSPECTION_START',
    'INSPECTION_COMPLETE',
    'EQUIPMENT_READ',
    'DEFECT_READ',
    'DEFECT_CREATE',
    'KNOWLEDGE_READ'
]);

SELECT append_role_permissions('HR_MANAGER', ARRAY[
    'EMPLOYEE_READ',
    'EMPLOYEE_CREATE',
    'EMPLOYEE_UPDATE',
    'EMPLOYEE_DELETE',
    'TIMESHEET_READ',
    'TIMESHEET_CREATE',
    'TIMESHEET_UPDATE',
    'TIMESHEET_APPROVE',
    'TIMESHEET_DELETE',
    'BRIGADE_READ',
    'BRIGADE_CREATE',
    'BRIGADE_UPDATE',
    'DEPARTMENT_READ'
]);

SELECT append_role_permissions('VIEWER', ARRAY[
    'EQUIPMENT_READ',
    'REPAIR_REQUEST_READ',
    'WORK_ORDER_READ',
    'DEFECT_READ',
    'DEFECT_LIST_READ',
    'PPR_PLAN_READ',
    'PPR_TASK_READ',
    'WAREHOUSE_READ',
    'STOCK_READ',
    'SPARE_PART_READ',
    'PROCUREMENT_READ',
    'BUDGET_READ',
    'ACTUAL_COST_READ',
    'APPROVAL_READ',
    'INSPECTION_READ',
    'KNOWLEDGE_READ',
    'ANALYTICS_READ',
    'DEPARTMENT_READ',
    'BRIGADE_READ',
    'LOCATION_READ',
    'EQUIPMENT_TYPE_READ',
    'CATEGORY_READ'
]);

DROP FUNCTION append_role_permissions(text, text[]);
