ALTER TABLE vehicle_details
    DROP CONSTRAINT IF EXISTS chk_vehicle_details_plate_type;

UPDATE vehicle_details
SET plate_type = CASE
    WHEN plate_type IN ('INDIVIDUAL', 'INDIVIDUAL_TWO_LINE') THEN 'INDIVIDUAL'
    WHEN plate_type IN ('LEGAL_ENTITY', 'LEGAL_ENTITY_TWO_LINE') THEN 'LEGAL_ENTITY'
    WHEN plate_type IN ('INDIVIDUAL_ECO', 'INDIVIDUAL_ECO_TWO_LINE') THEN 'INDIVIDUAL_ECO'
    WHEN plate_type IN ('LEGAL_ENTITY_ECO', 'LEGAL_ENTITY_ECO_TWO_LINE') THEN 'LEGAL_ENTITY_ECO'
    WHEN plate_type IN ('HIGH_GOVERNMENT', 'HIGH_GOVERNMENT_TWO_LINE', 'GOVERNMENT_DAV', 'GOVERNMENT_DAV_TWO_LINE') THEN 'GOVERNMENT'
    WHEN plate_type IN ('AMBULANCE_STY', 'AMBULANCE_ECO_STY') THEN 'EMERGENCY'
    WHEN plate_type IN (
        'DIPLOMATIC_CMD',
        'DIPLOMATIC_CMD_TWO_LINE',
        'DIPLOMATIC_D',
        'DIPLOMATIC_D_TWO_LINE',
        'DIPLOMATIC_TECHNICAL_T',
        'DIPLOMATIC_TECHNICAL_T_TWO_LINE'
    ) THEN 'DIPLOMATIC'
    WHEN plate_type IN ('UN', 'UN_TWO_LINE', 'INTERNATIONAL_ORG_X', 'INTERNATIONAL_ORG_X_TWO_LINE') THEN 'INTERNATIONAL_ORG'
    WHEN plate_type IN ('FOREIGN_INDIVIDUAL_H', 'FOREIGN_INDIVIDUAL_H_TWO_LINE') THEN 'FOREIGN_PERSON'
    WHEN plate_type IN ('FOREIGN_ORG_M', 'FOREIGN_ORG_M_TWO_LINE') THEN 'FOREIGN_ORG'
    WHEN plate_type IN (
        'MOTORCYCLE',
        'ELECTRIC_MOTORCYCLE',
        'SCOOTER',
        'MOPED',
        'FOREIGN_MOTORCYCLE',
        'FOREIGN_MOPED_SCOOTER'
    ) THEN 'MOTORCYCLE'
    WHEN plate_type = 'TRAILER' THEN 'TRAILER'
    WHEN plate_type IN ('TEMPORARY_TRANSIT', 'TEMPORARY_TRANSIT_TWO_LINE') THEN 'TRANSIT'
    WHEN plate_type = 'UNKNOWN' THEN 'UNKNOWN'
    ELSE 'UNKNOWN'
END;

ALTER TABLE vehicle_details
    ALTER COLUMN plate_type SET DEFAULT 'UNKNOWN',
    ALTER COLUMN plate_type SET NOT NULL;

ALTER TABLE vehicle_details
    ADD CONSTRAINT chk_vehicle_details_plate_type CHECK (
        plate_type IN (
            'INDIVIDUAL',
            'LEGAL_ENTITY',
            'INDIVIDUAL_ECO',
            'LEGAL_ENTITY_ECO',
            'GOVERNMENT',
            'EMERGENCY',
            'DIPLOMATIC',
            'INTERNATIONAL_ORG',
            'FOREIGN_PERSON',
            'FOREIGN_ORG',
            'MOTORCYCLE',
            'TRAILER',
            'TRANSIT',
            'UNKNOWN'
        )
    );
