package com.toir.dto.equipment;

import com.toir.dto.equipmentattribute.EquipmentAttributeValueRequest;
import com.toir.dto.equipmentmanualattribute.EquipmentManualAttributeRequest;
import com.toir.enums.EquipmentCategory;
import com.toir.enums.EquipmentStatus;
import com.toir.enums.MeterType;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public record EquipmentCreateRequest(
        String code,
        @NotBlank String name,
        @NotBlank String inventoryNumber,
        String technicalNumber,
        String serialNumber,
        String model,
        @Min(1900) @Max(2100) Integer producedYear,
        @NotNull UUID equipmentTypeId,
        UUID departmentId,
        UUID warehouseId,
        UUID locationId,
        UUID parentId,
        UUID criticalityClassId,
        UUID responsibleId,
        String manufacturer,
        EquipmentStatus status,
        EquipmentCategory category,
        LocalDate commissionedAt,
        LocalDate arrivalDate,
        LocalDate warrantyUntil,
        Boolean hasWarranty,
        UUID warrantyAttachmentId,
        LocalDate warrantyStartDate,
        LocalDate warrantyEndDate,
        String description,
        LocalDate operationStartDate,
        @Positive Integer expectedLifetimeMonths,
        @Positive Integer expectedLifetimeYears,
        @Positive Long expectedLifetimeHours,
        List<EquipmentAttributeValueRequest> attributes,
        List<EquipmentManualAttributeRequest> manualAttributes,
        EquipmentLocationRequest location,
        MeterType lifetimeCounterType,
        UUID lifetimeMeterId,
        @Positive Double lifetimeLimitValue,
        @PositiveOrZero Double lifetimeBaselineValue,
        @Positive Double lifetimeWarningPercent,
        @Positive Double averageDailyUsage,
        UUID supplierId,
        UUID warrantySupplierId,
        UUID mxikId
) {
        public EquipmentCreateRequest(
                String code,
                @NotBlank String name,
                @NotBlank String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                @Min(1900) @Max(2100) Integer producedYear,
                @NotNull UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                LocalDate warrantyStartDate,
                LocalDate warrantyEndDate,
                String description,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location,
                MeterType lifetimeCounterType,
                UUID lifetimeMeterId,
                @Positive Double lifetimeLimitValue,
                @PositiveOrZero Double lifetimeBaselineValue,
                @Positive Double lifetimeWarningPercent,
                @Positive Double averageDailyUsage,
                UUID supplierId,
                UUID warrantySupplierId
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, producedYear, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, warrantyStartDate, warrantyEndDate, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears, expectedLifetimeHours, attributes,
                        manualAttributes, location, lifetimeCounterType, lifetimeMeterId, lifetimeLimitValue,
                        lifetimeBaselineValue, lifetimeWarningPercent, averageDailyUsage, supplierId, warrantySupplierId,
                        null);
        }

        public EquipmentCreateRequest(
                String code,
                @NotBlank String name,
                @NotBlank String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                @Min(1900) @Max(2100) Integer producedYear,
                @NotNull UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                LocalDate warrantyStartDate,
                LocalDate warrantyEndDate,
                String description,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location,
                MeterType lifetimeCounterType,
                UUID lifetimeMeterId,
                @Positive Double lifetimeLimitValue,
                @PositiveOrZero Double lifetimeBaselineValue,
                @Positive Double lifetimeWarningPercent,
                @Positive Double averageDailyUsage
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, producedYear, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, warrantyStartDate, warrantyEndDate, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears, expectedLifetimeHours, attributes,
                        manualAttributes, location, lifetimeCounterType, lifetimeMeterId, lifetimeLimitValue,
                        lifetimeBaselineValue, lifetimeWarningPercent, averageDailyUsage, null, null);
        }

        public EquipmentCreateRequest(
                String code,
                @NotBlank String name,
                @NotBlank String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                @Min(1900) @Max(2100) Integer producedYear,
                @NotNull UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                LocalDate warrantyStartDate,
                LocalDate warrantyEndDate,
                String description,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, producedYear, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, warrantyStartDate, warrantyEndDate, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears, expectedLifetimeHours, attributes,
                        manualAttributes, location, null, null, null, null, null, null, null, null);
        }

        public EquipmentCreateRequest(
                String code,
                @NotBlank String name,
                @NotBlank String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                @NotNull UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                LocalDate warrantyStartDate,
                LocalDate warrantyEndDate,
                String description,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location,
                UUID supplierId,
                UUID warrantySupplierId
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, warrantyStartDate, warrantyEndDate, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears, expectedLifetimeHours, attributes,
                        manualAttributes, location, null, null, null, null, null, null, supplierId, warrantySupplierId);
        }

        public EquipmentCreateRequest(
                String code,
                @NotBlank String name,
                @NotBlank String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                @NotNull UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                LocalDate warrantyStartDate,
                LocalDate warrantyEndDate,
                String description,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, warrantyStartDate, warrantyEndDate, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears, expectedLifetimeHours, attributes,
                        manualAttributes, location, null, null, null, null, null, null, null, null);
        }

        public EquipmentCreateRequest(
                String code,
                @NotBlank String name,
                @NotBlank String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                @NotNull UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                LocalDate warrantyStartDate,
                LocalDate warrantyEndDate,
                String description,
                Long expectedLifetimeHoursFallback,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, warrantyStartDate, warrantyEndDate, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears,
                        expectedLifetimeHours != null ? expectedLifetimeHours : expectedLifetimeHoursFallback,
                        attributes, manualAttributes, location, null, null, null, null, null, null, null, null);
        }

        public EquipmentCreateRequest(
                String code,
                @NotBlank String name,
                @NotBlank String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                @NotNull UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                String description,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, null, null, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears, expectedLifetimeHours, attributes, manualAttributes,
                        location, null, null, null, null, null, null, null, null);
        }

        public EquipmentCreateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate warrantyUntil,
                String description,
                List<EquipmentAttributeValueRequest> attributes
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, null, warrantyUntil, false, null,
                        null, null, description, null, null, null, null, attributes, null, null,
                        null, null, null, null, null, null, null, null);
        }

        public EquipmentCreateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate warrantyUntil,
                String description
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, null, warrantyUntil, false, null,
                        null, null, description, null, null, null, null, null, null, null,
                        null, null, null, null, null, null, null, null);
        }

        public EquipmentCreateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate warrantyUntil,
                String description,
                Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, null, warrantyUntil, false, null,
                        null, null, description, null, null, null, expectedLifetimeHours, attributes, null, null,
                        null, null, null, null, null, null, null, null);
        }

        public EquipmentCreateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate warrantyUntil,
                String description,
                Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, null, warrantyUntil, false, null,
                        null, null, description, null, null, null, expectedLifetimeHours, attributes, manualAttributes, null,
                        null, null, null, null, null, null, null, null);
        }

        public EquipmentCreateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate warrantyUntil,
                String description,
                Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, null, warrantyUntil, false, null,
                        null, null, description, null, null, null, expectedLifetimeHours, attributes, manualAttributes, location,
                        null, null, null, null, null, null, null, null);
        }

        public EquipmentCreateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID warehouseId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate warrantyUntil,
                String description,
                Long expectedLifetimeHours
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, equipmentTypeId,
                        departmentId, warehouseId, locationId, parentId, criticalityClassId, responsibleId,
                        manufacturer, status, category, commissionedAt, warrantyUntil, description, expectedLifetimeHours, null);
        }
}
