package com.toir.dto.equipment;

import com.toir.dto.equipmentattribute.EquipmentAttributeValueRequest;
import com.toir.dto.equipmentmanualattribute.EquipmentManualAttributeRequest;
import com.toir.enums.EquipmentCategory;
import com.toir.enums.EquipmentStatus;
import com.toir.enums.MeterType;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public record EquipmentUpdateRequest(
        String code,
        String name,
        String inventoryNumber,
        String technicalNumber,
        String serialNumber,
        String model,
        @Min(1900) @Max(2100) Integer producedYear,
        UUID equipmentTypeId,
        UUID departmentId,
        UUID locationId,
        UUID parentId,
        UUID criticalityClassId,
        UUID responsibleId,
        String manufacturer,
        EquipmentStatus status,
        EquipmentCategory category,
        LocalDate commissionedAt,
        LocalDate arrivalDate,
        LocalDate warrantyUntil,
        Boolean hasWarranty,
        UUID warrantyAttachmentId,
        LocalDate warrantyStartDate,
        LocalDate warrantyEndDate,
        String description,
        LocalDate operationStartDate,
        @Positive Integer expectedLifetimeMonths,
        @Positive Integer expectedLifetimeYears,
        @Positive Long expectedLifetimeHours,
        List<EquipmentAttributeValueRequest> attributes,
        List<EquipmentManualAttributeRequest> manualAttributes,
        EquipmentLocationRequest location,
        MeterType lifetimeCounterType,
        UUID lifetimeMeterId,
        @Positive Double lifetimeLimitValue,
        @PositiveOrZero Double lifetimeBaselineValue,
        @Positive Double lifetimeWarningPercent,
        @Positive Double averageDailyUsage,
        UUID supplierId,
        UUID warrantySupplierId,
        UUID mxikId
) {
        public EquipmentUpdateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                @Min(1900) @Max(2100) Integer producedYear,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                LocalDate warrantyStartDate,
                LocalDate warrantyEndDate,
                String description,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location,
                MeterType lifetimeCounterType,
                UUID lifetimeMeterId,
                @Positive Double lifetimeLimitValue,
                @PositiveOrZero Double lifetimeBaselineValue,
                @Positive Double lifetimeWarningPercent,
                @Positive Double averageDailyUsage,
                UUID supplierId,
                UUID warrantySupplierId
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, producedYear, equipmentTypeId,
                        departmentId, locationId, parentId, criticalityClassId, responsibleId, manufacturer,
                        status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, warrantyStartDate, warrantyEndDate, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears, expectedLifetimeHours, attributes,
                        manualAttributes, location, lifetimeCounterType, lifetimeMeterId, lifetimeLimitValue,
                        lifetimeBaselineValue, lifetimeWarningPercent, averageDailyUsage, supplierId,
                        warrantySupplierId, null);
        }

        public EquipmentUpdateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                @Min(1900) @Max(2100) Integer producedYear,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                LocalDate warrantyStartDate,
                LocalDate warrantyEndDate,
                String description,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location,
                MeterType lifetimeCounterType,
                UUID lifetimeMeterId,
                @Positive Double lifetimeLimitValue,
                @PositiveOrZero Double lifetimeBaselineValue,
                @Positive Double lifetimeWarningPercent,
                @Positive Double averageDailyUsage
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, producedYear, equipmentTypeId,
                        departmentId, locationId, parentId, criticalityClassId, responsibleId, manufacturer,
                        status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, warrantyStartDate, warrantyEndDate, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears, expectedLifetimeHours, attributes,
                        manualAttributes, location, lifetimeCounterType, lifetimeMeterId, lifetimeLimitValue,
                        lifetimeBaselineValue, lifetimeWarningPercent, averageDailyUsage, null, null);
        }

        public EquipmentUpdateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                @Min(1900) @Max(2100) Integer producedYear,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                LocalDate warrantyStartDate,
                LocalDate warrantyEndDate,
                String description,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, producedYear, equipmentTypeId,
                        departmentId, locationId, parentId, criticalityClassId, responsibleId, manufacturer,
                        status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, warrantyStartDate, warrantyEndDate, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears, expectedLifetimeHours, attributes,
                        manualAttributes, location, null, null, null, null, null, null, null, null);
        }

        public EquipmentUpdateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                LocalDate warrantyStartDate,
                LocalDate warrantyEndDate,
                String description,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, locationId, parentId, criticalityClassId, responsibleId, manufacturer,
                        status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, warrantyStartDate, warrantyEndDate, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears, expectedLifetimeHours, attributes,
                        manualAttributes, location, null, null, null, null, null, null, null, null);
        }

        public EquipmentUpdateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                LocalDate warrantyStartDate,
                LocalDate warrantyEndDate,
                String description,
                Long expectedLifetimeHoursFallback,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, locationId, parentId, criticalityClassId, responsibleId, manufacturer,
                        status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, warrantyStartDate, warrantyEndDate, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears,
                        expectedLifetimeHours != null ? expectedLifetimeHours : expectedLifetimeHoursFallback,
                        attributes, manualAttributes, location, null, null, null, null, null, null, null, null);
        }

        public EquipmentUpdateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate arrivalDate,
                LocalDate warrantyUntil,
                Boolean hasWarranty,
                UUID warrantyAttachmentId,
                String description,
                LocalDate operationStartDate,
                @Positive Integer expectedLifetimeMonths,
                @Positive Integer expectedLifetimeYears,
                @Positive Long expectedLifetimeHours,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes,
                EquipmentLocationRequest location
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, locationId, parentId, criticalityClassId, responsibleId, manufacturer,
                        status, category, commissionedAt, arrivalDate, warrantyUntil, hasWarranty,
                        warrantyAttachmentId, null, null, description, operationStartDate,
                        expectedLifetimeMonths, expectedLifetimeYears, expectedLifetimeHours, attributes, manualAttributes,
                        location, null, null, null, null, null, null, null, null);
        }

        public EquipmentUpdateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate warrantyUntil,
                String description,
                List<EquipmentAttributeValueRequest> attributes
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, locationId, parentId, criticalityClassId, responsibleId, manufacturer,
                        status, category, commissionedAt, null, warrantyUntil, null, null, null, null,
                        description, null, null, null, null, attributes, null, null,
                        null, null, null, null, null, null, null, null);
        }

        public EquipmentUpdateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate warrantyUntil,
                String description
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, locationId, parentId, criticalityClassId, responsibleId, manufacturer,
                        status, category, commissionedAt, null, warrantyUntil, null, null, null, null,
                        description, null, null, null, null, null, null, null,
                        null, null, null, null, null, null, null, null);
        }

        public EquipmentUpdateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate warrantyUntil,
                String description,
                Long expectedLifetimeHours
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, locationId, parentId, criticalityClassId, responsibleId, manufacturer,
                        status, category, commissionedAt, null, warrantyUntil, null, null, null, null,
                        description, null, null, null, expectedLifetimeHours, null, null, null,
                        null, null, null, null, null, null, null, null);
        }

        public EquipmentUpdateRequest(
                String code,
                String name,
                String inventoryNumber,
                String technicalNumber,
                String serialNumber,
                String model,
                UUID equipmentTypeId,
                UUID departmentId,
                UUID locationId,
                UUID parentId,
                UUID criticalityClassId,
                UUID responsibleId,
                String manufacturer,
                EquipmentStatus status,
                EquipmentCategory category,
                LocalDate commissionedAt,
                LocalDate warrantyUntil,
                String description,
                List<EquipmentAttributeValueRequest> attributes,
                List<EquipmentManualAttributeRequest> manualAttributes
        ) {
                this(code, name, inventoryNumber, technicalNumber, serialNumber, model, null, equipmentTypeId,
                        departmentId, locationId, parentId, criticalityClassId, responsibleId, manufacturer,
                        status, category, commissionedAt, null, warrantyUntil, null, null, null, null,
                        description, null, null, null, null, attributes, manualAttributes, null,
                        null, null, null, null, null, null, null, null);
        }
}
