package com.toir.service.users;

import com.toir.dto.role.RoleRequest;
import com.toir.exception.RestException;
import com.toir.repository.users.RoleRepository;
import com.toir.util.AuditBuilderService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
class RoleServiceTest {

    @Mock
    RoleRepository repository;

    @Mock
    AuditBuilderService auditBuilderService;

    @InjectMocks
    RoleService service;

    @Test
    void createRejectsClientProvidedCode() {
        RoleRequest request = new RoleRequest(
                "ROLE-CLIENT",
                "Planner",
                "Planning role",
                List.of("PPR_READ")
        );

        assertThatThrownBy(() -> service.create(request))
                .isInstanceOfSatisfying(RestException.class, ex -> {
                    assertThat(ex.getStatus()).isEqualTo(HttpStatus.BAD_REQUEST);
                    assertThat(ex.getMessage()).contains("code is generated by backend");
                });

        verify(repository, never()).save(any());
    }
}
